### ISSUE TITLE
Looping through locales gives error

### ISSUE THREAD

**Issue by codedge** [statamic/cms#1224] opened 2020-01-18 01:49 UTC
Hi, 

when looping through locales, like this

```html
{{ locales }}
    <li class="nav-item">
        <a class="123 px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75" href="{{ url }}">
            {{ locale:flag }}
        </a>
    </li>
{{ /locales }}
```

with these `sites.yml` configuration

```php
<?php

return [
    'sites' => [

        'default' => [
            'name' => config('app.name'),
            'locale' => 'de_DE',
            'url' => '/',
            'flag' => 'de',
        ],

        'en' => [
            'name' => config('app.name') . '(en)',
            'locale' => 'en_US',
            'url' => '/en',
            'flag' => 'en',
        ]

    ]
];
```

I get this error `Call to a member function toAugmentedArray() on null`.

![image](https://user-images.githubusercontent.com/4409904/72656616-d76abf00-399c-11ea-9c62-4646e163c6fe.png)

```
Facade\Ignition\Exceptions\ViewException: Call to a member function toAugmentedArray() on null in file /Users/holger/code/stmr/stmr-website/resources/views/_navigation.antlers.html on line 0

#0 /Users/holger/code/stmr/stmr-website/resources/views/_navigation.antlers.html(0): ()
#1 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Locales.php(106): ()
#2 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Locales.php(90): Statamic\Tags\Locales->getLocalizedData('en')
#3 [internal function]: Statamic\Tags\Locales->Statamic\Tags\{closure}(Array, 'en')
#4 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#5 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Locales.php(95): Illuminate\Support\Collection->map(Object(Closure))
#6 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Locales.php(59): Statamic\Tags\Locales->addData(Object(Illuminate\Support\Collection))
#7 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(612): Statamic\Tags\Locales->Statamic\Tags\{closure}(Object(Illuminate\Support\Collection))
#8 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Locales.php(60): Illuminate\Support\Collection->pipe(Object(Closure))
#9 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Locales.php(28): Statamic\Tags\Locales->getLocales()
#10 [internal function]: Statamic\Tags\Locales->index()
#11 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#12 [internal function]: Statamic\View\Antlers\Engine::renderTag(Object(Statamic\View\Antlers\Parser), 'locales', Array, '\n              ...', Array)
#13 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Parser.php(579): call_user_func_array(Array, Array)
#14 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Parser.php(173): Statamic\View\Antlers\Parser->parseCallbackTags('<nav class="top...', Array)
#15 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Parser.php(126): Statamic\View\Antlers\Parser->parse('<nav class="top...', Array)
#16 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\View\Antlers\Parser->parseView('/Users/holger/c...', '<nav class="top...', Array)
#17 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/View/View.php(143): Statamic\View\Antlers\Engine->get('/Users/holger/c...', Array)
#18 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#19 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#20 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Partial.php(21): Illuminate\View\View->render()
#21 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Tags/Tags.php(139): Statamic\Tags\Partial->wildcard('_navigation')
#22 [internal function]: Statamic\Tags\Tags->__call('navigation', Array)
#23 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Engine.php(152): call_user_func(Array)
#24 [internal function]: Statamic\View\Antlers\Engine::renderTag(Object(Statamic\View\Antlers\Parser), 'partial', Array, '', Array)
#25 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Parser.php(579): call_user_func_array(Array, Array)
#26 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Parser.php(173): Statamic\View\Antlers\Parser->parseCallbackTags('<!doctype html>...', Array)
#27 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Parser.php(126): Statamic\View\Antlers\Parser->parse('<!doctype html>...', Array)
#28 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/Antlers/Engine.php(89): Statamic\View\Antlers\Parser->parseView('/Users/holger/c...', '<!doctype html>...', Array)
#29 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/View/View.php(143): Statamic\View\Antlers\Engine->get('/Users/holger/c...', Array)
#30 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#31 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#32 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/View/View.php(80): Illuminate\View\View->render()
#33 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Http/Responses/DataResponse.php(139): Statamic\View\View->render()
#34 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Http/Responses/DataResponse.php(44): Statamic\Http\Responses\DataResponse->contents()
#35 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Entries/Entry.php(278): Statamic\Http\Responses\DataResponse->toResponse(Object(Illuminate\Http\Request))
#36 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Structures/Page.php(281): Statamic\Entries\Entry->toResponse(Object(Illuminate\Http\Request))
#37 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(734): Statamic\Structures\Page->toResponse(Object(Illuminate\Http\Request))
#38 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#39 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Statamic\Structures\Page))
#40 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#60 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#61 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#62 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#63 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#64 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PoweredByHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Http/Middleware/VanityRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\VanityRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /Users/holger/code/stmr/stmr-website/vendor/statamic/cms/src/Http/Middleware/PermanentRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PermanentRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Users/holger/code/stmr/stmr-website/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /Users/holger/code/stmr/stmr-website/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#84 /Users/holger/code/stmr/stmr-website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#85 /Users/holger/code/stmr/stmr-website/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#86 /Users/holger/.composer/vendor/laravel/valet/server.php(158): require('/Users/holger/c...')
#87 {main}
```

**Comment by Konafets** [comment] 2020-06-17 15:15
The key `flag` just does not exist inside `locals` and for my understanding of the code in https://github.com/statamic/cms/blob/master/src/Tags/Locales.php#L67-L78 you can not just add a custom key to the array and its not documented: https://statamic.dev/tags/locales

**Comment by AndreasSchantl** [comment] 2020-07-24 08:50
I think #2004 is a duplicate of this bug. Also, there is a PR available with #2005

**Comment by Pixney-William** [comment] 2020-08-05 18:23
Got this too

**Comment by Pixney-William** [comment] 2020-08-05 18:24
It works fine on all 1st level pages
but as soon as you go `domain.com/level1/level2` it bombs out

**Comment by Pixney-William** [comment] 2020-08-05 18:25
```
{{ locales current_first=true }}
        <li>
            <a href="{{ url }}">{{ locale:name }}</a>
        </li>
 {{ /locales }}
```

**Comment by AndreasSchantl** [comment] 2020-08-05 18:40
In my experience, this only occurs on entries that don't have a localised version yet. Meaning, right now you need two identical locales (entry wise) to make the locales tag work. Otherwise you'll receive an error, cause it can't find the localised version for the other locale (the link for it) resulting in that error.

**Comment by Pixney-William** [comment] 2020-08-05 18:57
Yes, just figured that out so hacked the locales tag

**Comment by AndreasSchantl** [comment] 2020-08-05 19:07
Yep. #2005 is what you need.

**Comment by Pixney-William** [comment] 2020-08-05 19:15
actually i needed:
```
if (is_null($this->getData()->in($locale))) {
            return null;
        }
```

**Comment by cgrisar** [comment] 2020-08-10 10:55
There's more to it.

I dd'ed ```$this->getData()->in($locale)->toAugmentedArray()``` and got a value...

**Comment by el-schneider** [comment] 2020-08-21 06:26
I also ran into this ...

**Closed** 2020-08-27 20:31 UTC
Labels: augmentation, multisite

**Comment by Eworm** [comment] 2020-09-07 10:03
I ran into this problem today.

Sites.php:
```
'sites' => [

        'default' => [
            'name' => 'Dutch',
            'locale' => 'nl_NL',
            'url' => '/',
        ],

        'de' => [
            'name' => 'German',
            'locale' => 'de_DE.UTF-8',
            'url' => '/de/',
        ],

    ],
```

If I do this:

```
{{ locales }}
  <a href="{{ url }}">View in {{ locale:name }}</a>
{{ /locales }}
```

I only see 'View in Dutch'.

**Comment by Eworm** [comment] 2020-09-07 10:09
The migrate script didn't add ```sites:
  - default
  - de``` to pages.yaml, that's why the locales were missing. It did add those lines to the different collections though.

**Comment by AndreasSchantl** [comment] 2020-09-07 10:20
That's true. In v3, you have to enable the sites for each collections either by manually adding it, or by using the "configure blueprint" view
