### ISSUE TITLE
focus_css and focal point editing not working since 3.0.26

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#2836] opened 2020-11-11 23:23 UTC
## Bug Description
Updated to 3.0.26 and noticed focus_css not returning results. In addition, if I go in to edit a focal point for an asset, it will write to file (for example, updates in asset yaml to focus: 53-68-1). However, opening the same image again to edit focal point does not show the set values, but instead reverts to 50% 50%. The focus_css tag returns no results.

Reverted to 3.0.35 and all works as expected.

## How to Reproduce
Examine focus_css reverts for set focal points in 3.0.25 vs. 3.0.26

## Environment

**Statamic version:** 3.0.26

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment] 2020-11-11 23:27
Duplicate of #2831 and #2834, fix to come shortly!

**Comment by damcclean** [comment] 2020-11-11 23:27
Duplicate/same issue as #2831.

**Closed** 2020-11-11 23:27 UTC
