### ISSUE TITLE
Stack selector -> create new should always save & continue

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2557] opened 2020-09-29 10:55 UTC
## Bug Description
When you create a new item using the stack selector the save button defaults to save and go back to listing. This ruins the current process. It should always save & continue.
<img width="1504" alt="Screenshot 2020-09-29 at 12 54 17" src="https://user-images.githubusercontent.com/69107412/94549833-143cc480-0253-11eb-942c-7d78035e8d01.png">

**Comment by damcclean** [comment] 2020-09-29 10:57
Duplicate of #2469. 🙂

**Closed by damcclean** 2020-09-29 10:57 UTC

**Comment by robdekort** [comment] 2020-09-29 10:59
Why can't I remember to search? Thanks Duncan.
