### ISSUE TITLE
Can't edit taxonomy route

### ISSUE THREAD

**Issue by MariusSpring** [statamic/cms#6197] opened 2022-06-13 07:43 UTC
### Bug description

In collections, we can set the permalink with the "route" parameter. Example:

`products.yml`:
```
title: Products
template: templates/product
layout: layout
revisions: false
route: 'product/{id}/{slug}'
```

The same is not possible for taxonomies. I tried adding the "route" parameter to my categories, as I want the categories to be accessible at the root. For example: "The Midnight Sun" category should be at `/the-midnight-sun` and not `/categories/the-midnight-sun`.

### How to reproduce

1. Create taxonomy.
2. Attempt to set "route" param.

### Versions

Statamic 3.3.15 Pro
Laravel 8.83.15
PHP 8.1.3
doublethreedigital/runway 2.3.6
spatie/statamic-health 1.0.0
statamic/collaboration 0.4.0

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment] 2022-06-14 14:03
Duplicate of #2403

**Closed by jasonvarga** 2022-06-14 14:03 UTC
Labels: taxonomies
