### ISSUE TITLE
Error after saving root page (home)

### ISSUE THREAD

**Issue by freshface** [statamic/cms#3135] opened 2021-01-20 12:35 UTC
## Bug Description

``` Argument 1 passed to Statamic\Structures\Tree::page() must be of the type string, null given, called in /Users/frederikheyninck/Figure8/mamp/harvest fund/website/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php on line 182 ```

## How to Reproduce

Save the home page.

## Environment

Statamic 3.0.39 Pro
Laravel 7.30.3
PHP 7.3.20
No addons installed

**Statamic version:**  3.0.39 Pro

**PHP version:**  7.3.20

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment] 2021-01-20 12:53
Duplicate of #3132. Will be fixed in next release.

**Closed** 2021-01-20 12:53 UTC
