### ISSUE TITLE
"to_json" modifier problems after updating to Statamic version 3.3.*

### ISSUE THREAD

**Issue by dryven-lukas** [statamic/cms#5527] opened 2022-03-16 15:51 UTC
### Bug description

After updating to Statamic version 3.3.* I had issues with the "to_json" modifier. When trying to parse an array the modifiers return an empty array. However when using the modifier inside a collection loop, it works just fine.

In conclusion:

`{{ collapse_items | to_json }}`

doesn't work anymore. The "collapse_items" are grid-items that got defined in the CP.
It just returns an empty array with the number of items defined in the grid.
`[{},{},{}]`

However the following code still produces the expected outcome:

`{{ collection:example as="items" }}
    {{ items | to_json }}
{{ /collection:example }}`

gives:
`[{"text":"Lorem ipsum"},{"text":"dolor sit amet"}]`

### How to reproduce

1. Add a grid to the page and fill it with values (for example with text)
2. Try parsing them in the antlers-file with the "to_json" modifier.
3. Try displaying the result on the page

### Versions

Statamic 3.3.0 Pro
Laravel 8.83.2
PHP 8.0.10
aryehraber/statamic-logbook 2.0.2
ddm-studio/cookie-byte 1.0.13
spatie/statamic-responsive-images 2.8.5

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment] 2022-03-16 16:30
Duplicate of #5518, and already fixed for 3.3.1

**Closed by jasonvarga** 2022-03-16 16:30 UTC
