### ISSUE TITLE
Globals not translated when rendering localized entries with Statamic\View::render() 

### ISSUE THREAD

**Issue by wanze** [statamic/cms#5205] opened 2022-02-04 21:49 UTC
### Bug description

Suppose you need to render multiple localized entries with a single request. We noticed that everything is translated correctly in the rendered HTML except for data of globals. They were always rendered in the locale of the default site because they are not translated in the cascade. Here is some pseudo code:

```php
$currentSite = Site::current();

foreach (Config::getLocales() as $locale) {
  $localizedEntry = $entry->in($locale);
  
  Site::setCurrent($locale);
  
  // Render a localized entry -> globals are not translated in the cascade.
  $html = (new View)
    ->template('foo')
    ->layout('bar')
    ->cascadeContent($localizedEntry)
    ->render();

  Site::setCurrent($currentSite->handle());
}
```

### Problem

The cascade used when calling `Statamic\View::gatherData()` always holds the same `site` object (it's a singleton). This site object does not correspond to the currently active site. It is also not possible to pass the correct `site` or `cascade` to the view object before calling `View::render()`.

### Solution

One solution would be to have a setter for the `cascade` so that the view object does not use a cached instance of the cascade holding the wrong site.

```php
// Statamic\View

public function withCascade(Statamic\View\Cascade $cascade) {
  $this->cascade = $cascade;
}
```

Happy to send a pull request if the above solution makes sense to you. :)

### How to reproduce

Run the above code example.

### Versions

Statamic 3.2.32 Pro
Laravel 8.81.0
PHP 7.4.25

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2024-07-25 14:07
I can't seem to reproduce this issue on the latest version of Statamic. 

I have two sites - an English site and a German site. I also have a `stuff` global which has a `text` field, the text value is different in the different sites.

The outputted `$html` seems to be returning the localized global data:

```antlers
<h1>{{ stuff:text }} - {{ title }}</h1>
```

```php
use Statamic\View\View;
use Statamic\Facades\Site;
use Statamic\Facades\Entry;

$entry = Entry::find('4e18d07e-f218-4a8a-a860-809c06bd9ee2');

$currentSite = Site::current();

foreach (['default', 'de'] as $locale) {
  $localizedEntry = $entry->in($locale);
  
  Site::setCurrent($locale);
  
  // Render a localized entry -> globals are not translated in the cascade.
  $html = (new View)
    ->template('foo')
    ->layout('bar')
    ->cascadeContent($localizedEntry)
    ->render();

  echo $html;

  Site::setCurrent($currentSite->handle());
}
```

```html
english - Select dropdown cells with Laravel Excel
german - Select dropdown cells im Laravel Excel
```

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2024-07-25 14:07 UTC
Labels: custom
