### ISSUE TITLE
Asset's focal point broken in 3.0.26

### ISSUE THREAD

**Issue by afonic** [statamic/cms#2834] opened 2020-11-11 18:17 UTC
## Bug Description
The 3.0.26 upgrade broke the focal point functionality.

## How to Reproduce
Upload an asset and set a focal point. After saving and opening again it doesn't appear in the control panel, nor the focus_css gets populated in the frontend.

Already uploaded assets lose the focus_css variable.

## Extra Detail
Downgrading to 3.0.25 fixes this issue.

## Environment

**Statamic version:** 3.0.26

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by tomhelmer** [comment] 2020-11-11 18:43
FYI, this is a duplicate of : https://github.com/statamic/cms/issues/2831

**Comment by damcclean** [comment] 2020-11-11 19:55
Yup, looks like the same thing. I'll close this issue and mark as a duplicate.

**Closed by damcclean** 2020-11-11 19:55 UTC
Labels: bug, critical
