### ISSUE TITLE
Control Panel (markdown editor) doesn't support RTL languages

### ISSUE THREAD

**Issue by tao** [statamic/cms#5942] opened 2022-04-28 17:45 UTC
### Bug description

The Statamic Sites config allows you to enter sites with RTL support but the Statamic Control panel doesn't work with them.

![Screenshot 2021-09-20 at 13 09 25](https://user-images.githubusercontent.com/1446331/133993353-de16a6ac-6c45-49fc-986f-6abc8fdd8b79.png)

It should be right aligned text, but it seems like the cursor also behaves strangely in RTL mode with the markdown parser. It's not really detecting well where the end of the line is and keeps putting the full-stop on the next line.

![Screenshot 2021-09-20 at 13 10 50](https://user-images.githubusercontent.com/1446331/133993376-f374cf73-8b7d-4899-9ede-3a3b8f0afd9d.png)

I also need to support Persian/Farsi which is RTL. I don't mind if the Control Panel remains the same for now with the same LTR layout but for editing RTL text it's difficult to use at the moment.

![Screenshot 2022-04-28 at 19 41 48](https://user-images.githubusercontent.com/1446331/165814687-cf527eb5-213d-407d-a541-d880d6cf7e78.png)

This is the RTL version:

![Screenshot 2022-04-28 at 19 44 20](https://user-images.githubusercontent.com/1446331/165815108-5b4c1d1f-c52c-410a-ae96-da28accdfc23.png)

We need some `direction: rtl;` css on the form fields.

### How to reproduce

Use some RTL text in the Markdown Editor.

### Versions

Statamic 3.2.39 Pro
Laravel 8.83.8
PHP 8.0.17
statamic/ssg 0.9.0

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment] 2022-04-29 06:19
Duplicate of https://github.com/statamic/ideas/issues/248

**Comment by tao** [comment] 2022-04-29 09:35
@jasonvarga Sorry, but it's not an idea anymore it's a bug.

**Comment by tao** [comment] 2022-04-29 15:45
I've been looking at a solution for this today and this is what I have as a work in progress (unless there's a more elegant solution).

If we could get something like `$direction` added to `Statamic\Http\Controllers\CP\Collections\EntriesController.php`

![Screenshot 2022-04-29 at 17 40 17](https://user-images.githubusercontent.com/1446331/165977969-80cbb848-9a76-4245-88cc-b974d9735d9d.png)

And then add it to the body tag:

![Screenshot 2022-04-29 at 17 40 32](https://user-images.githubusercontent.com/1446331/165978171-95ac2e9d-c16f-4ae0-91ef-b71056f741ae.png)

Or just adding it directly:

![Screenshot 2022-04-29 at 17 45 22](https://user-images.githubusercontent.com/1446331/165978777-dc6d4ecb-6fe9-4512-97f8-a466eb2d6b09.png)

I can start adding custom css like this in `resources/css/cp.css`:

```css
.rtl * input[type="text"] {
    direction: rtl;
    background: lightyellow;
}

.rtl * editor {
    direction: rtl;
}
```

And it makes it a bit easier to see the form input in the correct direction, which would be a nice temporary solution as our translators can read English, just the Hebrew and Persian text at the moment needs to be right-to-left.

![Screenshot 2022-04-29 at 17 42 10](https://user-images.githubusercontent.com/1446331/165978593-91edfe21-6b31-4d1d-a34c-6b4e1b42e9d4.png)

**Comment by jackmcdade** [comment] 2022-04-29 15:56
I got you 😊

**Closed by jackmcdade** 2022-04-29 15:56 UTC
Labels: i18n

**Comment by jasonvarga** [comment] 2022-04-30 06:27
Not a bug either, it just wasn't supported in the CP. The rtl site setting was a frontend thing. But looks like Jack has sorted you out.
