### ISSUE TITLE
Incorrect Stache - Returning entries in collection tag loop which should not be there

### ISSUE THREAD

**Issue by philipboomy** [statamic/cms#6062] opened 2022-05-19 09:56 UTC
### Bug description

I am getting entries in the collection tag loop which shouldnt be there.

`collection:products features:exists="true"`

A newly created entry is showing up despite the features grid field is empty. I think it only happens when creating new entries but might also be for edited entries.

I have to manually go and clear the stache before wrong entries are removed from the loop suggesting the stache is "wrong" and not any templating issues.

### How to reproduce

Support can't reproduce as replied in email to me but try creating a collection tag loop

`collection:products features:exists="true"`

Where features is a grid field.

Create a new entry without adding any rows to the grid field.

Refresh page with loop on and see if entry shows up.

### Versions

Statamic 3.3.11 Pro
Laravel 8.83.12
PHP 7.4

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

Happens with both regex and runtime antlers

**Comment by duncanmcclean** [comment] 2023-12-18 11:18
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. Only the entries with rows in the Grid are being returned by the `{{ collection }}` tag.

I'm going to close this issue now. If you're still experiencing this issue, please provide a fresh Statamic site where you can reproduce the issue and we can re-open the issue. Thanks.

**Closed by duncanmcclean** 2023-12-18 11:18 UTC
Labels: stache

**Comment by philipboomy** [comment] 2023-12-18 11:49
I cant remember 1.5 years later however I think it was fixed.
