### ISSUE TITLE
Querying an Entries Field in GraphQL returns null

### ISSUE THREAD

**Issue by rigestshala** [statamic/cms#8448] opened 2023-07-14 15:49 UTC
### Bug description

I am trying to query in GraphQL an Entries Field found inside a Bard field in my projects' homepage. No matter what I try it returns `null`.

![image](https://github.com/statamic/cms/assets/44037037/d779dbe4-7f96-409a-afd4-3eb4bdbb198f)
![image](https://github.com/statamic/cms/assets/44037037/5be604f0-fb4a-4947-ba37-b40cd33de884)
![](https://cdn.discordapp.com/attachments/1129135602583998474/1129408580102127747/Screenshot_2023-07-14_at_3.46.23_PM.png)
![](https://cdn.discordapp.com/attachments/1129135602583998474/1129409265216540732/Screenshot_2023-07-14_at_3.48.53_PM.png)

### How to reproduce

Create an Entries field within a Bard and query it from GraphQL

### Environment

```yaml
Environment
Application Name: B
Laravel Version: 10.13.5
PHP Version: 8.1.17
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: phoenix.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.10.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment] 2023-07-14 17:40
Is the entry you selected a draft?

**Comment by rigestshala** [comment] 2023-07-14 19:10
Thank you for your reply @jasonvarga!
The entry is published.

**Comment by duncanmcclean** [comment] 2023-12-12 18:32
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I can get a Bard field (`body` in my case), then query the related entry (which I have in the "promoted entry" set) without any issues.

![CleanShot 2023-12-12 at 18 31 12](https://github.com/statamic/cms/assets/19637309/7e1935e2-2799-4c88-8b72-049f6b417f9f)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-12-12 18:32 UTC
Labels: graphql
