### ISSUE TITLE
Cant save entries after enabled published date on mode range

### ISSUE THREAD

**Issue by abuhurairah-aar** [statamic/cms#4818] opened 2021-11-24 21:04 UTC
### Bug description

I tried to enable publish date in my collection and configure the date field inside the blueprint to mode 'range'. However, when I go to create a new entry, after inserting all the required fields, setting the date range, and clicking the save button, an error notification appeared saying `Argument #1 ($string) must be of type string, array given`, thus I cant save the entry.

### How to reproduce

You may reproduce the error by using these steps:-

1. Create a new collection, here I've created an `Articles` collection
![image](https://user-images.githubusercontent.com/18186856/143308510-67738327-482e-42e2-8af9-f0f55087713c.png)

2. Click into `Configure Collection` 
![image](https://user-images.githubusercontent.com/18186856/143309188-cb8adf7a-e7c2-4874-b8d4-301c63ac6f03.png)

3. Enable the `Enable Publish Dates` and click save
![image](https://user-images.githubusercontent.com/18186856/143309342-56d092a8-8c29-4ddb-8cf1-10a6463964c8.png)

4. Then on the same page of the `Configure Collection` page, go to the `Content Model` section, and click the `edit` on the Blueprint
![image](https://user-images.githubusercontent.com/18186856/143309731-1c89ae5b-7bac-45bc-b69a-4292deb7cef4.png)

5. Edit the default created blueprint of the collection by clicking on it, in this case, the blueprint name is `Articles`
![image](https://user-images.githubusercontent.com/18186856/143309948-9e6a9095-a6db-4bb8-beb4-f1fbc808c99b.png)

6. In the blueprint edit page, on the sidebar you will see a field name date created after enabling the publish date, click the date field to edit it
![image](https://user-images.githubusercontent.com/18186856/143310089-7034b4fd-6524-4e1e-9c68-6955501c138f.png)

7. I've edited the Display input field to `Date` and updated the `Mode` to `range`, and hit the button Finish on the top right, then save the blueprint.
![image](https://user-images.githubusercontent.com/18186856/143310541-206cd01b-0008-4c07-b6bb-d245a1fac7a0.png)

8. Then go to the Articles collection and create an entry
![image](https://user-images.githubusercontent.com/18186856/143310689-c24ac243-3fd6-438f-b5d9-ffd41b1bd787.png)

9. Try to insert the entry as per the following, then you will see an error pop up saying that `strlen(): Argument #1 ($string) must be of type string, array given`
![image](https://user-images.githubusercontent.com/18186856/143310975-d17e1e0d-5c00-447b-8d2d-5092955d333e.png)

10. Another issue also happened after setup the mode 'single` with some date format like these
![image](https://user-images.githubusercontent.com/18186856/143313303-75d47125-1c8e-44f2-a6a8-43daddeaae29.png)

11. Then go create an entry like the following and save it
![image](https://user-images.githubusercontent.com/18186856/143311822-b5473843-b019-4608-8012-4d0bbfb5c162.png)

12. Go to the collection again to edit the created entry just now by clicking on it
![image](https://user-images.githubusercontent.com/18186856/143311974-0e5e1c5e-518d-4a46-a0a8-2204de2310b9.png)

13. Voila, you will this error
![image](https://user-images.githubusercontent.com/18186856/143312058-46ffa823-c02c-43fc-9802-a1d600e65c53.png)

### Logs

```shell
`[2021-11-24 20:53:02] local.ERROR: strlen(): Argument #1 ($string) must be of type string, array given {"userId":"2365fc2c-8f79-463e-af03-280d9e874555","exception":"[object] (TypeError(code: 0): strlen(): Argument #1 ($string) must be of type string, array given at /var/www/html/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php:438)
[stacktrace]
#0 /var/www/html/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(438): strlen()
#1 /var/www/html/vendor/statamic/cms/src/Http/Controllers/CP/Collections/EntriesController.php(341): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->formatDateForSaving()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Collections\\EntriesController->store()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#10 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle()
#12 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle()
#14 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AddToasts->handle()
#16 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle()
#18 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 /var/www/html/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#42 /var/www/html/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle()
#44 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#46 /var/www/html/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#48 /var/www/html/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#60 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#67 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#68 /var/www/html/server.php(21): require_once('...')
#69 {main}
"} `
```

### Versions

Statamic 3.2.23 Pro
Laravel 8.73.1
PHP 8.0.11
4rn0/statamic-v3-image-optimizer 1.0.8
aryehraber/statamic-captcha 1.6.0
aryehraber/statamic-impersonator 2.3.0
aryehraber/statamic-logbook 2.0.2
codedge/statamic-move-entries 1.1
ddm-studio/cookie-byte 1.0.11
doublethreedigital/duplicator 2.0.1
doublethreedigital/runway 2.1.34
doublethreedigital/yumyum 1.1.0
goellner/table-on-steroids 1.1.0
goldnead/statamic-collapse-fieldtype 1.0.4
jacksleight/bard-paragraph-style 1.2.2
jonassiewertsen/statamic-external-link 1.4.1
kolaente/statamic-snippet 1.1.1
octoper/statamic-inline-assets 4.0.3
optimoapps/statamic-bard-text-align 1.0.2
phpsa/statamic-analytics 1.3.0
rias/statamic-data-import 1.1.2
rias/statamic-link-it 2.2.3
rias/statamic-redirect 1.8.0
roorda-ict/statamic-entries-export 1.0.0
spatie/statamic-responsive-images 2.8.5
statamic/seo-pro 2.3.2
statamic/ssg 0.8.0
visuellverstehen/statamic-classify 2.3.1
xndbogdan/statamic-bard-text-color 2.2

### Installation

Existing Laravel app

### Additional details

Ubuntu 18
Nginx 
PHP-FPM
Composer
YARN
Tailwind
AlpineJS

**Comment by duncanmcclean** [comment] 2021-11-24 21:08
WOW, that's a lot of addons.

**Comment by abuhurairah-aar** [comment] 2021-11-24 21:15
> WOW, that's a lot of addons.

Yeah wonder if any of the addons causing the misbehavior :sweat_smile:

**Comment by duncanmcclean** [comment] 2021-11-24 21:28
It's possible but I don't think that'll be the issue.

**Comment by j3ll3yfi5h** [comment] 2021-11-29 11:47
Duplicate of #3655 ?

**Closed** 2023-12-11 16:45 UTC
Labels: dates
