### ISSUE TITLE
Asset upload join() deprecation warning

### ISSUE THREAD

**Issue by jdsimcoe** [statamic/cms#1063] opened 2019-12-04 17:26 UTC
I've tested this on `PHP 7.3.12` and `PHP 7.4.0`. When I try to upload an asset to a local asset container I always get this same deprecation error warning and stack trace:

```log
join(): Passing glue string after array is deprecated. Swap the parameters
/Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Facades/Endpoint/Path.php#139
ErrorException
            return null;
        }

        return self::tidy(join($args, '/'));
    }

    /**

#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'join(): Passing...', '/Users/jdsimcoe...', 139, Array)
#1 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Facades/Endpoint/Path.php(139): join(Array, '/')
#2 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(245): Statamic\Facades\Endpoint\Path->assemble(Array)
#3 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Facades/Endpoint/URL.php(40): Illuminate\Support\Facades\Facade::__callStatic('assemble', Array)
#4 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(245): Statamic\Facades\Endpoint\URL->assemble(Array, 'headshot.jpg')
#5 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Assets/Asset.php(260): Illuminate\Support\Facades\Facade::__callStatic('assemble', Array)
#6 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Statamic\Assets\Asset->absoluteUrl()
#7 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php(132): Illuminate\Http\Resources\Json\JsonResource->forwardCallTo(Object(Statamic\Assets\Asset), 'absoluteUrl', Array)
#8 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Http/Resources/CP/Assets/Asset.php(18): Illuminate\Http\Resources\Json\JsonResource->__call('absoluteUrl', Array)
#9 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(94): Statamic\Http\Resources\CP\Assets\Asset->toArray(Object(Illuminate\Http\Request))
#10 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceResponse.php(39): Illuminate\Http\Resources\Json\JsonResource->resolve(Object(Illuminate\Http\Request))
#11 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(201): Illuminate\Http\Resources\Json\ResourceResponse->toResponse(Object(Illuminate\Http\Request))
#12 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(733): Illuminate\Http\Resources\Json\JsonResource->toResponse(Object(Illuminate\Http\Request))
#13 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Statamic\Http\Resources\CP\Assets\Asset))
#14 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Statamic\Http\Resources\CP\Assets\Asset))
#15 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\CP\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\CP\Authorize->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#38 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#39 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#40 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#41 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PoweredByHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/VanityRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\VanityRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/jdsimcoe/Sites/statamic/vendor/statamic/cms/src/Http/Middleware/PermanentRedirects.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Statamic\Http\Middleware\PermanentRedirects->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/jdsimcoe/Sites/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/jdsimcoe/Sites/statamic/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /Users/jdsimcoe/Sites/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#62 /Users/jdsimcoe/Sites/statamic/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#63 /Users/jdsimcoe/.composer/vendor/laravel/valet/server.php(158): require('/Users/jdsimcoe...')
#64 {main}
```

**Comment by jasonvarga** [comment] 2019-12-04 17:26
Duplicate of #1055

**Closed by jasonvarga** 2019-12-04 17:26 UTC

**Comment by jdsimcoe** [comment] 2019-12-04 17:29
Thanks @jasonvarga FWIW I tried doing a search before posting.

**Comment by jasonvarga** [comment] 2019-12-04 17:30
I believe you! The error you ran into was in a screenshot in the other issue which is why it probably didn't come up in search for you.

**Comment by jdsimcoe** [comment] 2019-12-04 17:33
Ah got it! Do you know when this will make it into the next beta release?

**Comment by jasonvarga** [comment] 2019-12-04 17:34
It's already fixed, will tag a release shortly.
