### ISSUE TITLE
{{ if email_sent }} var not working on forgot password form.

### ISSUE THREAD

**Issue by twd3** [statamic/cms#2086] opened 2020-07-15 17:44 UTC
The {{if email_sent}} var is not working on the forgot password form. The email gets sent, that "success" message just never shows.

## How to Reproduce
Make sure it's on forgot password form and enter your user email and send. Using this format from docs:
```
    {{ if email_sent }}
        <p>Email sent!</p>
    {{ else }}

        {{ if errors }}
            <div class="alert alert-danger">
                {{ errors }}
                    {{ value }}<br>
                {{ /errors }}
            </div>
        {{ /if }}

        <label>Email Address</label>
        <input type="text" name="email" />
        <button>Send Reset Email</button>
    {{ /if }}
```

## Environment

**Statamic version:** 3.0.0.-beta-37

**PHP version:** 7.3

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by twd3** [comment] 2020-07-15 17:50
Shoot, not sure if this closed issue fixed this issue I'm having: https://github.com/statamic/cms/issues/2078

**Comment by jasonvarga** [comment] 2020-07-15 17:50
Don't think so. Looks separate.

**Comment by twd3** [comment] 2020-07-15 19:33
I thought maybe I was logged in when I  was testing this forgot password flow so I added that hop tip from the docs that says wrap this form in {{ if logged_out }} and I tested again and still does not show email_sent...

**Comment by jasonvarga** [comment] 2020-07-15 19:34
It's not hooked up. You've given enough info 👍

**Comment by vitor-ao** [comment] 2020-07-19 18:30
This issue is the same as https://github.com/statamic/cms/issues/1777

**Comment by mikemartin** [comment] 2020-08-08 02:43
@jasonvarga @vitor-ao @twd3 

I was able to do this using the `session:status` var:

```
  {{ if {session:status} }}
    {{ session }}
      {{ partial:auth/success :success_message="status" }}
    {{ /session }}
  {{ /if }}
```

**Comment by jesseleite** [comment] 2020-09-24 20:48
Duplicate of #1777

**Closed by jesseleite** 2020-09-24 20:48 UTC
Labels: bug, ux
