### ISSUE TITLE
Can't set additional limit="x" and offset="x" on collections when using aliasing

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#2303] opened 2020-08-26 16:02 UTC
## Bug Description
In v2, I was able to able to generate a set of collection records like the following to allow admins to set up a blog summary module. This would allow me to retrieve 4 total records, then use a partial to either display all 4 or break them up further:
`{{ collection:blog paginate="{paginate}" limit="{entry_limit }" offset="{offset}" sort="{sorting}" as="posts" taxonomy:tags={get:tag} }}`

Admins could then select a display template that would load from a partial. One of those was a summary view that had a section for the latest post plus a list of next posts listed differently underneath. Those were generated by additionally limiting the results of the aliased post set, like `{{ posts limit="1" }}` and `{{ posts limit="3" offset="1" }}`.

## How to Reproduce
Create a template to find a set number of records from a collection with aliasing, then set additional _limit_ and _offset_ parameters on the aliased set of records.

## Environment

**Statamic version:** 3.0.*

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic` with migrated v2 site

**Comment by jasonvarga** [comment] 2020-08-26 16:05
I don't think paginate and offset/limit together makes sense. Try getting rid of paginate.

**Comment by theblacksheepltd** [comment] 2020-08-26 16:08
I already took that out and had same result. The paginate field is a toggle to allow them to paginate in certain view modes. I'm rewriting now to put the collection tag into each view partial, which might be better for clarity later on anyway. Just not sure if we're supposed to be able to filter a filtered set.

**Comment by jackmcdade** [comment] 2020-09-01 15:56
It's not clear what the issue is exactly as you didn't describe the output, but if you're finding yourself with the wrong number of results, try doing the offset first, and _then_ the limit. They're performed in order.

**Comment by jasonvarga** [comment] 2020-09-30 14:16
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it or feel free start a fresh one anytime. Either is fine by us!

**Closed by jasonvarga** 2020-09-30 14:16 UTC
Labels: needs more info
