### ISSUE TITLE
Validation error not appearing on grid in stacked mode

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#5252] opened 2022-02-10 12:25 UTC
### Bug description

I have required fields inside a grid, inside a replicator, inside another replicator. When I try to save the entry without choosing a link I get the "The given data was invalid." error, as expected. Yet there is no indication on the link field that it is causing the error.

In the screenshot below you can see the 'Items' label is highlighted in red, but the link and image fields have no error messages:

![image](https://user-images.githubusercontent.com/20210934/153408205-04a5c0a3-b388-4d22-93e6-dc94c537da6a.png)

This problem only occurs when using Stacked mode for the grid. Table mode is fine.

### How to reproduce

I'm not sure if the replicators matter but this is the structure I have:

```
Sections (Replicator)
    - Blocks (Replicator)
          - Special Block (Fieldset)
                - Items (Grid)
                     - Link (Required Link Field)
                     - Image (Required Asset Field)

```

### Versions

Statamic 3.2.32 Pro
Laravel 8.83.0
PHP 7.4.19
edalzell/blade-directives 3.5.2
statamic/seo-pro 2.3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by robdekort** [comment] 2022-02-13 11:21
Same, if someone wants to reproduce it quickly, use peak, add an article block to an entry, then add a buttons set and in there add a button.

**Comment by duncanmcclean** [comment] 2023-11-20 18:28
This seems to be fixed now in the latest version of Statamic.

![CleanShot 2023-11-20 at 18 27 48](https://github.com/statamic/cms/assets/19637309/ae3b1641-d89f-42a9-8845-f1401b1bad7a)

**Closed by duncanmcclean** 2023-11-20 18:28 UTC
