### ISSUE TITLE
Can’t set default for blueprint fields via control panel

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2295] opened 2020-08-25 22:42 UTC
## Bug Description
When trying to add blueprint fields via the control panel, the default option seems to be missing.

## How to Reproduce
1. Add or edit a blueprint in the control panel.
2. Add or edit a field in the blueprint.
3. There is no default option.

## Extra Detail
It appears that you can add the default option in the blueprint file itself, but that is awkward if you’re in the midst of building blueprints via the control panel.

## Environment
Statamic 3.0.0 Pro
Laravel 7.25.0
PHP 7.3.17
No addons installed

- Fresh install from `statamic/statamic`, followed by migration from v2

**Comment by jasonvarga** [comment] 2020-08-25 22:43
Duplicate of #672

**Comment by fitzage** [comment] 2020-08-25 22:44
Ha! How come my search couldn’t find that? Anyway…

**Closed by jasonvarga** 2020-08-25 22:43 UTC
