### ISSUE TITLE
Unable to select integer options in Button Group

### ISSUE THREAD

**Issue by michaellindahl** [statamic/cms#2331] opened 2020-08-29 19:16 UTC
## Bug Description

I created a button group in Blueprint and the buttons were not selectable despite them looking identical to a button group I created earlier when looking at the yaml. (`- 25%` vs `- 0`)

When creating a button group, either in the yaml or Blueprint, integers must not be used, or if they are, the user must wrap them in quotes in the yaml after creating them in the control panel.

## How to Reproduce

Create a button group in the Control Panel using Blueprint:
![image](https://user-images.githubusercontent.com/692663/91644359-21665980-e9f0-11ea-8b98-98d8de5aa2f2.png)

or create them in the Blueprint yaml:
```
        handle: image_padding
        field:
          options:
            - 0
            - 1
            - 2
            - 3
          type: button_group
          listable: hidden
          display: Padding
```

And then attempt to select the buttons in that button group, this fails. 

Despite it working for other button groups in the yaml:
```
          options:
            - 25%
            - 33%
            - 50%
            - 75%
            - 100%
```

In order to fix this issue the user must modify the integers with quotes in the yaml:
```
        handle: image_padding
        field:
          options:
            - '0'
            - '1'
            - '2'
            - '3'
          type: button_group
          listable: hidden
          display: Padding
```

## Environment

**Statamic version:** 3.0.2
**PHP version:** 7.4
**Install method (choose one):**  Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment] 2020-08-29 20:51
There has been a similar issue with select fields. Not 100% sure if they are connected somehow, but it may be worth checking that out:
https://github.com/statamic/cms/issues/1217

**Comment by jcohlmeyer** [comment] 2020-09-07 15:27
Seems like it may be related to #2215 and #2066 as well.

**Comment by jasonvarga** [comment] 2020-09-30 14:26
Duplicate of #2215

**Closed by jasonvarga** 2020-09-30 14:26 UTC
