### ISSUE TITLE
Error when renaming an asset file and saving an entry

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/cms#2715] opened 2020-10-22 09:19 UTC
When I upload an asset to a directory, rename the asset and then attempt to save the entry, I get this error

```
"exception":"[object] (Error(code: 0): Call to a member function path() on null at /Users/user/Sites/xxx/vendor/statamic/cms/src/Fieldtypes/Assets/Assets.php:98)
[stacktrace]
```
https://d.pr/i/ns3HvL

I can resolve by refreshing the entry, and reapplying the assets (the assets have been renamed at this point).

![alt text](https://d.pr/i/ns3HvL+ "")

Statamic version:** 3.0.20

PHP version:** 7.4.10

**Comment by damcclean** [comment] 2020-10-22 09:36
Looks like a duplicate of #2401.

**Closed** 2020-10-22 16:15 UTC
Labels: duplicate
