### ISSUE TITLE
Template selection vaia fieldtype not working in child entries

### ISSUE THREAD

**Issue by PMahlke** [statamic/cms#6962] opened 2022-10-26 14:59 UTC
### Bug description

When selecting a template via the template fieldtype in an entry, the template won't be used, if the entry has a parent with a different selected template. The parent template will be used instead.

### How to reproduce

1. Create a new Collection ("Config" in my case) (Orderable, no max-depth, template: default, route: {{ parent_uri ?= parent_uri | ensure_left="/" }}/{{slug}}, slug required: true)
2. Create a Blueprint and add a "Template" field
3. Create entry and set a template other than default
4. Create a second entry, select first entry as parent, set a different template than first entry and default

Second entry will now use first entries template

Edit: spelling

### Environment

```yaml
Statamic 3.3.47 Pro
Laravel 8.83.25
PHP 8.0.22
doublethreedigital/duplicator 2.3.2
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)

### Additional details

Don't know if it makes a difference, but the page is a multisite

**Comment by duncanmcclean** [comment] 2023-12-06 15:42
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. The child entry is using the correct template. 

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-12-06 15:42 UTC
