### ISSUE TITLE
Issue with Partials without `antlers.html` being parsed anyway

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1179] opened 2020-01-08 07:56 UTC
Currently if you have a template file `index.html`, tags and variables and rendering sort of work, but there's issues that are hard to debug. If you name the file correctly to `index.antlers.html` all the issues disappear.

So it would be nice to get a warning or exception when referencing a template file that doesn't have either `antlers` or `blade` in them.

**Comment by jasonvarga** [comment] 2020-01-08 17:50
There's nothing invalid about having a .html template though.
Same with having a .php template and forgetting to add .blade.php

**Comment by jackmcdade** [comment] 2020-01-08 21:40
In fact, the file name is an indicator on which engine to parse with.

- `.html` – No parsing
- `.antlers.html` – Antlers
- `.blade.php` - Blade
- `.php` - HTML with PHP (e.g. `<?php echo "what the heck are you doing"?>`)
- `.twig.php` – Twig parsing (if installed)

**Comment by riasvdv** [comment] 2020-01-09 07:58
I was getting errors in my tags though when not using .antlers.html

**Comment by riasvdv** [comment] 2020-01-09 08:02
This is a partial being referenced as a set within a bard:

`teasers.antlers.html`

![Screen Shot 2020-01-09 at 09 01 31](https://user-images.githubusercontent.com/3626559/72049195-bb8d5c00-32be-11ea-803b-36d1b446f05d.png)

`teasers.html`

![Screen Shot 2020-01-09 at 09 01 25](https://user-images.githubusercontent.com/3626559/72049214-c2b46a00-32be-11ea-8927-ca231bdcd21c.png)

The "Who needs this" block just disappears when it's not an `antlers.html` partial

**Comment by jackmcdade** [comment] 2020-01-09 15:10
What were the errors? When you're missing the `antlers.` part it should simply not parse, which is 100% intentional. The use case for this is being able to write straight HTML and use JavaScript `{{ curlies }}` and stuff without worrying about escaping everything.

**Comment by riasvdv** [comment] 2020-01-09 15:21
I'm getting:

```
debug
log
[15:21:11] LOG.debug: Cannot loop over non-loopable variable: {{ b6256dc3918c84862dc6cc4d468613ed }}
debug
log
[15:21:11] LOG.debug: Cannot loop over non-loopable variable: {{ 10ad53d80806b096f3dd569eca8f5ef8 }}
```

In the debugbar, they're both normal text variables, not loopable variables.

**Comment by riasvdv** [comment] 2020-01-09 15:38
Might this be because it's being included as such in a template that **is** an antlers template? 

```
{{ partial src="teasers" }}
```

So it finds the `teasers.html` and then tries to parse it since it's already parsing the parent template?

**Comment by jackmcdade** [comment] 2020-01-09 16:59
Ahh yes I bet that's what's happening. We'll take a look!

**Comment by jackmcdade** [comment] 2020-04-07 14:48
I'm passing this one off to you @jasonvarga, I thought it might be a parser thing but the issue is in the view abstraction somewhere. Not my speciality :)

**Comment by jasonvarga** [comment] 2020-04-07 17:27
This is happening because the contents of the partial (non-antlers, but with some antlers code) gets included, and then the parent view (antlers) sees the unparsed antlers and parses it.

Maybe we could do some noparse trickery.

**Comment by jasonvarga** [comment] 2020-06-16 20:13
Getting a chance to dig into this, and I can't seem to replicate it. I'm going to close this, but feel free to let us know if you're still running into it, and provide some more specific details (template code, etc), and we'll reopen.

**Closed by jasonvarga** 2020-06-16 20:13 UTC
Labels: bug
