### ISSUE TITLE
Orderable Collections Tree Order Changed After Updating

### ISSUE THREAD

**Issue by twd3** [statamic/cms#4018] opened 2021-07-17 01:33 UTC
My pages collection tree's entry positions went crazy after updating. Not really a big deal but it actually through me for a loop. I'm not sure this is reproducible and I'd be worried I have some misconfig if it isn't. 

## How to Reproduce
Have an ordered collection with home page and update from 3.1.27 to 3.1.29. Some other entry should now show as the home page when you view the site but when you look at the collection tree YAML all is well. Then when you look in the CP it's clear what happened like in the image below...all the trees entries got rearranged.

![Firefox_Screenshot_2021-07-17T01-07-56 639Z](https://user-images.githubusercontent.com/16004958/126021365-3d0c7ef3-78dc-4c0c-bdb4-cd3ad4b4e55d.png)

## Environment
Statamic 3.1.29 Pro
Laravel 8.50.0
PHP 7.4.13
aryehraber/statamic-captcha 1.5.2
spatie/statamic-responsive-images 2.7.1

**Install method (choose one):**
- Existing Laravel app

**Comment by jasonvarga** [comment] 2021-07-17 02:07
Can you roll back and try the update again? Does it happen again the second try?

**Comment by twd3** [comment] 2021-07-17 02:33
Well it happened last night upgrading to .28 and I rolled back, and it fixed it. Then tonight I went straight to .29 from .27 and it happened again.

**Comment by juresrpcic** [comment] 2021-07-17 16:53
I also experienced this issue - but it only happens on my local Windows environment (same Laravel & PHP versions as original issue above) - it ignores the existing `trees/collections/collection-name.yaml` file which still has the original structure (before 3.1.28 when this started happening).

Weirdly enough, if I start manually ordering it does update that trees/collections yaml file, but if I copy over the one from (Unix) server with the proper structure, it just ignores it, as if it was caching the tree somewhere else, can't figure it out. The only way to get it working locally is to manually rebuild the structure again.

I'd guess this is connected to https://github.com/statamic/cms/pull/3948 - perhaps something about Windows directory path checking if there is a matching collection. My trees and collections match of course.

On the server the exact same file setup works fine (running composer update on both envs).

**Comment by juresrpcic** [comment] 2021-07-17 17:00
I can confirm that rolling back just this file: `https://github.com/statamic/cms/blob/6454e620c50a3191ed69279c61fa79ef838b35dd/src/Stache/Stores/CollectionTreeStore.php` it fixes the issue - it now properly reads the "non-scrambled" original YAML (after clearing all caches which makes sense).

I'll try to pinpoint the exact issue as I've got an easy to reproduce setup on my local dev - still sounds like more fun than manually dragging a few 30+ page trees into the old structure.

**Comment by twd3** [comment] 2021-07-17 17:14
Oh, so glad it wasn't just me. Thanks for posting this juresrpcic!

**Comment by juresrpcic** [comment] 2021-07-17 17:15
Here it is - when extracting `$handle` it balks at the Windows path, I've caught all the intermediate results with Ray for clarity:

```
public function getItemFilter(SplFileInfo $file)
    {
        if (! parent::getItemFilter($file)) {
            return false;
        }

        [, $handle] = $this->parseTreePath($file->getPathname());

        // $file->getPathname() ... 'C:/web/igrec/content/trees/collections\blogauthors.yaml'

        // $this->parseTreePath($file->getPathname()) ...
        // array:6 [▼
        //     0 => "C:"
        //     1 => "web"
        //     2 => "igrec"
        //     3 => "content"
        //     4 => "trees"
        //     5 => "collections\blogauthors"
        // ]

        // $handle ... 'web'

        if (! ($collection = Collection::findByHandle($handle))) {
            return false;
        }

        return $collection->hasStructure();
    }
 ```

As you can see the `$handle` extraction becomes just the first directory (in my case `web`) so it tries to compare that to collection name and it doesn't work. The `getPathname()` probably returns just `collections/collection.yaml` on Linux which is where it works fine.

I tried just using `getRelativePathname()` from `SplFileInfo` instead of current `getPathname()` and it works fine on Windows (didn't test on Linux yet).

Fyi @arthurperton

**Comment by jasonvarga** [comment] 2021-07-18 01:33
Nice find!

**Comment by arthurperton** [comment] 2021-07-19 08:31
Thanks @juresrpcic!

And your info is very helpful. What stands out is that the returned path `C:/web/igrec/content/trees/collections\blogauthors.yaml` contains both forward slashes and backslashes, which leads to trouble. I googled it an it looks like a [known issue](https://www.php.net/manual/en/splfileinfo.getpathname.php#102987).

Currently working on a fix for this.

**Comment by juresrpcic** [comment] 2021-07-19 08:45
No problem @arthurperton .

I did research this path issue a bit deeper before making the pull request - it's one of those "hopefully someone solved it already" things and it appears that that's what Symfony did in their extended `Symfony\Component\Finder\SplFileInfo` - it's just for relative paths which then bypasses the forward slash issue in Windows (but you could also try `getRealPath()` to bypass the slashes issue manually - as you're taking the last array member anyway, both approaches work). You were already importing the Symfony version of `SplFileInfo` so the only change needed was that `getPathname()` -> `getRelativePathname()`.

```
14: /**
15:  * Extends \SplFileInfo to support relative paths
16:  *
17:  * @author Fabien Potencier <fabien@symfony.com>
18:  */
19: class SplFileInfo extends \SplFileInfo
```

I like to have a Windows setup for local dev for this very reason - when other devs work on these projects they often work on Windows and while everything tends to work in Linux land, the paths are hard to debug without a replicatable setup.

**Comment by juresrpcic** [comment] 2021-07-19 09:13
Sure @arthurperton no worries, thanks for sorting this out properly! 🙏

**Comment by arthurperton** [comment] 2021-07-19 09:24
Your welcome!

**Closed** 2021-07-19 17:31 UTC
