### ISSUE TITLE
Portrait images are overflowing in the editor

### ISSUE THREAD

**Issue by stefankempf** [statamic/cms#5674] opened 2022-03-28 15:37 UTC
### Bug description

Whenever I want to view an image with some portrait like dimensions in the editor, the three buttons "focal point", "rename", and "move" are overflowing the bottom border.

I cannot get them within the viewport, even if I zoom out like in https://github.com/statamic/cms/issues/4023 where the same issue already appeared. Workaround is to resize the browser window.

<img width="2202" alt="Bildschirmfoto 2022-03-28 um 17 29 45" src="https://user-images.githubusercontent.com/20299885/160434757-6dd223e7-fe95-47e6-aa47-0d230de3754b.png">
<img width="1350" alt="Bildschirmfoto 2022-03-28 um 17 29 37" src="https://user-images.githubusercontent.com/20299885/160434790-b943bd77-e244-425a-9b6d-252f249f8aaa.png">

### How to reproduce

Upload 9/16 image and view within editor.

### Versions

Statamic 3.3.3 Pro
Laravel 8.83.5
PHP 8.1.3
sortarad/lol 1.0.3
spatie/statamic-responsive-images 2.11.0

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by duncanmcclean** [comment] 2022-03-28 15:38
Duplicate of #5664.

**Closed by duncanmcclean** 2022-03-28 15:38 UTC
