### ISSUE TITLE
Multi-sites adds dates to new entry translations even when the collection doesn't use dates

### ISSUE THREAD

**Issue by tao** [statamic/cms#3247] opened 2021-02-15 13:22 UTC
## Bug Description

I have a collection of books without dates, and new entries are created without dates. We do this because books don't really have an exact date we want to assign to them. New multi-site translations add the dates to the filename.

```
- books
  - en
    - secrets-of-the-ufo.md
    - the-hobbit.md
    - return-of-the-king.md
```
When I create a new book on the collection, with the slug `test-book` for example... it just uses the slug:

```
- books
  - en
    - test-book.md
```

When I create a new translation it prepends the date, which I don't think is correct if the collection doesn't use dates.

```
- books
  - en
    - secrets-of-the-ufo.md
    - the-hobbit.md
    - return-of-the-king.md
    - test-book.md
  - german
    - 2020-10-06-2208.the-hobbit.md
```

## Environment

Statamic 3.0.38 Pro
Laravel 8.22.1
PHP 7.4.12

**Comment by duncanmcclean** [comment] 2021-02-15 21:06
You show some code snippets there, where are they from? I'm not sure you mentioned..

**Comment by jasonvarga** [comment] 2021-03-02 01:04
If I'm understanding correctly, this is a duplicate of #2296

**Closed by jasonvarga** 2021-03-02 01:04 UTC
Labels: multisite
