### ISSUE TITLE
Asset "trash" icon not visible in Safari

### ISSUE THREAD

**Issue by mscruse** [statamic/cms#4389] opened 2021-10-05 03:07 UTC
## Bug Description
When editing a page in the CP using the Safari browser the trash can icon next to assets (e.g. images) is now visible. If you click around the location it is there, you just can't see it.

The icon is visible in Firefox and Chrome OK.

## How to Reproduce

Add an asset field to your blueprint, create a page and set the asset field. Use Safari, log into CP, edit page and note the trash icon is not visible.

## Extra Detail

2 screenshots, the first is using Firefox, the second using Safari.

<img width="789" alt="screenshot - firefox" src="https://user-images.githubusercontent.com/22737928/135953599-128ba863-f325-4f01-b6b4-bf4743c4e7ea.png">
<img width="744" alt="screenshot - safari" src="https://user-images.githubusercontent.com/22737928/135953603-be24801a-2eeb-4bb9-a64f-f4c41204716b.png">

## Environment

Statamic 3.2.11 Pro
Laravel 8.62.0
PHP 8.0.1
doublethreedigital/duplicator 2.0.0

**Statamic version:** 3.2.11

**PHP version:** 8.01

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment] 2021-10-05 07:07
Duplicate of #4328.

**Closed by robdekort** 2021-10-05 07:07 UTC
