### ISSUE TITLE
Redirect tag no longer supports "to" parameter

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#3598] opened 2021-04-27 12:14 UTC
## Bug Description

The redirect tag no longer works as expected. The following tag results in a `The to modifier was not found.` error.

```
{{ redirect to="/login" }}
```

## Extra Detail
<img width="1249" alt="Screen Shot 2021-04-27 at 10 10 14 pm" src="https://user-images.githubusercontent.com/414211/116239080-94091e00-a7a5-11eb-9700-d3ba0a58e4c1.png">

## Environment

Statamic 3.1.10 Pro
Laravel 7.30.4
PHP 7.4.14
aryehraber/statamic-impersonator 2.2.0
doublethreedigital/duplicator 1.3.0
doublethreedigital/runway 1.0.13
mikemartin/helpscout-beacon 1.0.1
mikemartin/samcart 1.0.4
statamic/seo-pro 2.2.0

**Comment by jasonvarga** [comment] 2021-04-27 13:41
Do you have a field called redirect?

**Comment by duncanmcclean** [comment] 2021-04-27 19:02
I'm unable to reproduce this issue. 

Like Jason says, it could happen if you have a field called `redirect` where Antlers will treat it like a variable instead of a tag and therefore that's why it's trying to use `to` as a modifier.

You can quickly verify by putting `{{ redirect | dump }}` in your template, what/if anything does it return?

**Comment by mikemartin** [comment] 2021-04-27 22:13
Thanks guys, sorry I didn't think of that. I do have a redirect field but it is needed for this collection. 
Is there a workaround I could use here? I noticed that Erin added a route parameter recently, would that help?

**Comment by duncanmcclean** [comment] 2021-04-27 22:16
If changing the field name is out of the question, then you could probably get away with creating a custom tag with the same code as the core redirect tag.

I could whip something up for you if needed? (Although, not until tomorrow 😉)

**Comment by mikemartin** [comment] 2021-04-27 23:02
Thanks @duncanmcclean. I've created my own `redirectUrl` tag as you suggested:

`{{ redirect_url to="/login" }}`

Any thoughts to prevent this tag/field naming conflict in Statamic or would you consider this an edge case?

**Comment by duncanmcclean** [comment] 2021-04-28 03:50
redirect_url should work fine, is it causing issues?

**Comment by mikemartin** [comment] 2021-04-28 04:24
@duncanmcclean The custom tag works totally fine. :)

**Comment by duncanmcclean** [comment] 2021-04-28 19:31
Closing as it’s not really a big.

**Closed by duncanmcclean** 2021-04-28 19:31 UTC
Labels: discussion, parser
