### ISSUE TITLE
UI - disabled primary button looks like active primary button

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1698] opened 2020-04-17 09:09 UTC
## Bug Description
After an entry has been edited, it happens that users try to "publish" the entry without saving. Maybe it would help if the button could be recognized visually as disabled?

## How to Reproduce
- edit entry
- button looks like it's active

## Environment

**Statamic version:** https://github.com/statamic/cms/commit/2c0592ac093e3389606ae3258a481e18c90be9bc

**PHP version:** 7.3.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jackmcdade** [comment] 2020-04-17 12:03
Duplicate of #1615, but it doesn't look disabled because it's not. Some people like to save even when there's nothing to save because it makes you feel nice and safe. We haven't decided if we want to change this pattern yet.

**Closed** 2020-04-17 12:04 UTC

**Comment by WiebkeVog** [comment] 2020-04-17 12:10
Maybe I did not explain it correctly, it is about the button "publish". When I inspect the element it says that the button is "disabled", but it still looks clickable. Maybe it would change if the button had a different shade of blue?

<img width="777" alt="Bildschirmfoto 2020-04-17 um 14 06 58" src="https://user-images.githubusercontent.com/54707973/79567785-1819c780-80b5-11ea-905a-b46ffb637246.png">
