### ISSUE TITLE
Bard-field - css class only added to the first element?

### ISSUE THREAD

**Issue by carnevalle** [statamic/cms#1051] opened 2019-12-03 10:01 UTC
Hi!

This is my first time ever using Statamic, so I don't know if the is just me being clueless or if it is actually a bug.

I am trying to render a Bard-field using the example from the documentation:
https://statamic.dev/fieldtypes/bard

![Skærmbillede 2019-12-03 kl  10 58 41](https://user-images.githubusercontent.com/54747/70040513-f9121180-15bb-11ea-9911-b9113e4c9ec0.png)

I have this structure in my document

![Skærmbillede 2019-12-03 kl  10 59 52](https://user-images.githubusercontent.com/54747/70040587-1646e000-15bc-11ea-8b84-b003d146514e.png)

I would expect that this would add the mb-2 class to every text-type, but it is only added to the first paragraph which somehow is an empty paragraph.

![Skærmbillede 2019-12-03 kl  10 58 28](https://user-images.githubusercontent.com/54747/70040650-324a8180-15bc-11ea-9dbe-962d1312ea2b.png)

**Comment by jackmcdade** [comment] 2019-12-03 14:07
That's because all those paragraphs are all in one `text` set, effectively an open-ended WYSIWYG chunk of markup. It could contain paragraphs, lists, headers, you name it. It will continue until it hits _another_ set, like those you configure yourself (see screenshot of Set configurator).

![image](https://user-images.githubusercontent.com/44739/70057481-328e5100-15ab-11ea-8565-95a3deb99278.png)

Your `<p class="mb-2">` is the wrapper around your text content. You'll see in our docs example we're using a div for that purpose.

I highly recommend styling this type of content in css. I usually create a `.markdown` or `.content` class and use Tailwind `@apply` directives to style it. For example:

```css
.content {
    @apply font-sans text-grey-dark;

    > h1 {
        @apply text-5xl font-display font-bold mb-6 leading-none;
    }

    > h2 {
        @apply text-2xl font-bold pb-4 leading-tight mt-12 pt-4;
    }
    
> p, > blockquote > p {
        @apply text-base mb-6;
    }
}
```

Adam Wathan also recommends this approach with Tailwind and is working on a plugin to set a default class and style for this scenario: <https://github.com/tailwindcss/typography>.

I'm going to close this issue because it's not a bug, but feel free to reply if you need more pointers!

**Closed by jackmcdade** 2019-12-03 14:07 UTC
