### ISSUE TITLE
Translation files cause fatal error: htmlspecialchars() expects parameter 1 to be string, array given 

### ISSUE THREAD

**Issue by vlasscontreras** [statamic/cms#3339] opened 2021-03-05 16:44 UTC
## Bug Description

If you have a translation file in `resources/lang/en` that somehow matches a Statamic translation _namespace_ (even if there's no file with the same in [statamic/resources/lang/en](https://github.com/statamic/cms/tree/3.0/resources/lang/en)), the control panel stops working and shows:

```
ErrorException
htmlspecialchars() expects parameter 1 to be string, array given (View: .../vendor/statamic/cms/resources/views/partials/nav-main.blade.php)
```

## How to Reproduce

Create a new project and create `resources/lang/en/forms.php` with the content:

```php
<?php

return [
    'anything' => 'Anything',
];
```

Now the obscure part. By this time the files are cached, so the translation works. But if you pull the project in a different computer with no `vendor` directory (or you remove the `vendor` directory in the current computer and then `composer install`), that's when the error appears.

## Environment

Statamic 3.0.45 Solo
Laravel 8.31.0
PHP 7.3.24 (also PHP 8.0.2)
No addons installed

**Install method:**
- Fresh install from `statamic/statamic`

## Workaround

To get around this bug in the current version just name the translation file something else (like `form.php`) and repeat the `vendor` directory removal/composer install.

**Comment by duncanmcclean** [comment] 2021-03-05 17:35
Confirmed. I seem to remember someone having a similar issue in the past when using a custom translation file, the same as one in the Statamic namespace. Although, I can't find the issue.

**Comment by jasonvarga** [comment] 2021-03-05 17:53
Duplicate of #2341

**Comment by duncanmcclean** [comment] 2021-03-05 17:54
That's the one.

**Closed by jasonvarga** 2021-03-05 17:53 UTC
Labels: bug, i18n
