### ISSUE TITLE
Cannot Use The API To Fetch Navigation Data

### ISSUE THREAD

**Issue by ty3sc** [statamic/cms#2560] opened 2020-09-29 15:24 UTC
## Bug Description

Hi, I'm not sure if this is a bug or a feature request, but it doesn't seem possible to use the API to fetch navigation data.

![statamic](https://user-images.githubusercontent.com/44230608/94578738-faf64100-026f-11eb-9914-b60f4956f857.png)

I added a "Test" navigation in a fresh install of Statamic but couldn't find an endpoint to fetch that data. The documentation (https://statamic.dev/content-api#endpoints) doesn't mention navigation at all so I'm guessing this isn't supported?

**Statamic version:**

3.0.12

**PHP version:**

7.4.10

**Install method:**

Existing Laravel App

**Comment by jasonvarga** [comment] 2020-09-29 15:26
Duplicate of statamic/ideas#176

Go give that a thumbs up 👍

**Closed by jasonvarga** 2020-09-29 15:26 UTC

**Comment by ty3sc** [comment] 2020-09-29 15:31
Ah, sorry I missed that. Will do! :)
