### ISSUE TITLE
Entries fieldtype / RelationshipController pre-processes entries of one collection using another collections' blueprint

### ISSUE THREAD

**Issue by sauerbraten** [statamic/cms#2862] opened 2020-11-18 15:19 UTC
## Bug Description

Using the entries fieldtype with two collections (say, A and B, configuration order is important), which both have a field with the same handle (for example, `foo`) in their blueprint, RelationshipController's index() will result in a call to preProcessForIndex() on the fieldtype of A's `foo` field with the `foo` value of an entry in collection B.

As far as I understand the code, the bug is in the Entries fieldtype's getResourceCollection() method: it sets the first collection's blueprint for all Entry resources. ListedEntry's values() method (via toArray()) will then use that wrong blueprint and call preProcessForIndex() with a field value from an Entry that should use a different blueprint.

I'll open a PR with a suggested fix for this.

## How to Reproduce

1. have two collections, Apples, Oranges and Fruits
2. use the same field handle `foo` in both Apples' and Oranges' blueprint, with incompatible field types (for example, make one a text field and the other an array)
3. in Fruits' blueprint, build an entries field with `collections: [Apples, Oranges]`
4. have working entries in Apples and Oranges
5. try to link from a Fruits entry to one of them by opening the entries' selector stack

## Environment

**Statamic version:** 3.0.26

**Laravel version:** 6.20.2

**PHP version:** 7.3.18

**Comment by sauerbraten** [comment] 2021-02-01 12:10
This is also not solved yet, is it?

**Comment by damcclean** [comment] 2021-02-01 12:29
Don't think so.

**Comment by duncanmcclean** [comment] 2023-11-27 17:59
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I'm not getting any errors when opening the relationship stack selector, using the reproduction steps you provided.

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-27 17:59 UTC
