### ISSUE TITLE
Entries fieldtype needs collection

### ISSUE THREAD

**Issue by aerni** [statamic/cms#3819] opened 2021-06-09 16:01 UTC
## Bug Description
If you don't select at least one collection in the config of the `Entries` fieldtype, you will end up with an error when trying to link an entry:

```
array_key_exists(): The first argument should be either a string or an integer
```

I'm expecting to be able to link to entries of any collection if I don't specify the collections in the fieldtype config.

## How to Reproduce
1. Add an `Entries` fieldtype to your blueprint and don't select any collection in the config
2. Create a new entry and try to link an entry with the fieldtype
3. Error

## Environment
Statamic 3.1.20 Pro
Laravel 8.46.0
PHP 7.4.16

**Comment by jasonvarga** [comment] 2021-06-09 16:12
I can't reproduce this. It works as you expect. No collections = all collections.

Could you provide the entire stack trace?

**Comment by aerni** [comment] 2021-06-09 16:34
Ha funny …

```
[2021-06-09 15:58:42] local.ERROR: array_key_exists(): The first argument should be either a string or an integer {"userId":"ead7bcad-6985-471d-a38a-37af1644d2c6","exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:155)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/michael/...', 155, Array)
#1 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(155): array_key_exists(0.5, Array)
#2 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(296): Illuminate\\Support\\Arr::exists(Array, 0.5)
#3 /Users/michael/Code/apotheker/vendor/laravel/helpers/src/helpers.php(129): Illuminate\\Support\\Arr::get(Array, 0.5, 0.5)
#4 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Fieldtypes/Select.php(92): array_get(Array, 0.5, 0.5)
#5 [internal function]: Statamic\\Fieldtypes\\Select->Statamic\\Fieldtypes\\{closure}(0.5, 0)
#6 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(642): array_map(Object(Closure), Array, Array)
#7 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Fieldtypes/Select.php(93): Illuminate\\Support\\Collection->map(Object(Closure))
#8 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Fields/Field.php(259): Statamic\\Fieldtypes\\Select->preProcessIndex(0.5)
#9 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Data/DataCollection.php(224): Statamic\\Fields\\Field->preProcessIndex()
#10 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Statamic\\Data\\DataCollection->Statamic\\Data\\{closure}(Object(Statamic\\Entries\\Entry), 4)
#11 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Data/DataCollection.php(228): Illuminate\\Support\\Collection->each(Object(Closure))
#12 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Statamic\\Data\\DataCollection->preProcessForIndex()
#13 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Extensions/Pagination/LengthAwarePaginator.php(42): Illuminate\\Pagination\\AbstractPaginator->forwardCallTo(Object(Statamic\\Entries\\EntryCollection), 'preProcessForIn...', Array)
#14 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Fieldtypes/Entries.php(79): Statamic\\Extensions\\Pagination\\LengthAwarePaginator->__call('preProcessForIn...', Array)
#15 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Controllers/CP/Fieldtypes/RelationshipFieldtypeController.php(18): Statamic\\Fieldtypes\\Entries->getIndexItems(Object(Statamic\\Http\\Requests\\FilteredRequest))
#16 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Fieldtypes\\RelationshipFieldtypeController->index(Object(Statamic\\Http\\Requests\\FilteredRequest))
#17 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#18 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Fieldtypes\\RelationshipFieldtypeController), 'index')
#19 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#20 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#21 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#40 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#50 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#51 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#52 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#53 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/michael/Code/apotheker/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/michael/Code/apotheker/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/michael/Code/apotheker/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/michael/Code/apotheker/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#80 /Users/michael/Code/apotheker/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#81 /Users/michael/Code/apotheker/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#82 /Users/michael/.composer/vendor/laravel/valet/server.php(219): require('/Users/michael/...')
#83 {main}
"} 
```

**Comment by jasonvarga** [comment] 2021-06-09 17:57
Do you have any `select` fields with `0.5` as a value?

**Comment by aerni** [comment] 2021-06-09 18:32
Yes, I do. The error triggers as soon as I open the stack selector.

**Comment by duncanmcclean** [comment] 2021-06-09 18:36
Related (possible duplicate) of #3254

**Comment by jasonvarga** [comment] 2021-06-09 20:18
Can you show the field?

Do you get the error when browsing the regular listing of whatever collection that's in? (ie. not the stack selector, just hit the collection via the nav)

**Comment by aerni** [comment] 2021-06-10 12:22
This is actually the exact same issue as in #3254. It doesn't happen when browsing the regular listing. Only happens in the stack selector.

**Field that causes the issue:**
```
handle: sitemap_priority
    field:
      options:
        '0.0': '0.0'
        '0.1': '0.1'
        '0.2': '0.2'
        '0.3': '0.3'
        '0.4': '0.4'
        '0.5': '0.5'
        '0.6': '0.6'
        '0.7': '0.7'
        '0.8': '0.8'
        '0.9': '0.9'
        '1.0': '1.0'
      clearable: false
      multiple: false
      searchable: true
      taggable: false
      push_tags: false
      cast_booleans: false
      type: select
      instructions: 'Choose the priorty of this entry in the sitemap. `1.0` is the most important.'
      width: 50
      default: '0.5'
      listable: hidden
      display: Priority
```

**Comment by jasonvarga** [comment] 2021-06-10 13:53
Closing in favor of that, then. Thanks!

**Closed by jasonvarga** 2021-06-10 13:53 UTC
Labels: can't recreate, needs more info
