### ISSUE TITLE
Deleting multiple Taxonomy Terms doesn't work

### ISSUE THREAD

**Issue by lateshift** [statamic/cms#2527] opened 2020-09-24 08:10 UTC
## Bug Description
Deleting multiple Taxonomy Terms doesn't work as expected (also the checkbox is slighty misplaced 😉)

## How to Reproduce

![image](https://user-images.githubusercontent.com/179465/94118468-e10ec580-fe4d-11ea-8125-dead6e05499f.png)

![image](https://user-images.githubusercontent.com/179465/94118503-ea982d80-fe4d-11ea-93e1-9f1733dd8d15.png)

Terms aren't deleted:
![image](https://user-images.githubusercontent.com/179465/94118543-fab00d00-fe4d-11ea-84bf-61c2a8ca4397.png)

## Environment

**Statamic version:** 3.0.12

**PHP version:** 7.3.11

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by robdekort** [comment] 2020-09-24 10:14
Are the terms still being used? Possibly related or a duplicate of https://github.com/statamic/cms/issues/1349

**Comment by Pfeifakopf** [comment] 2020-09-24 12:48
Try to clear the cache. This worked for me here: #1569

**Comment by jasonvarga** [comment] 2020-09-24 14:15
Duplicate of #1349

**Closed by jasonvarga** 2020-09-24 14:15 UTC
Labels: bug, taxonomies
