### ISSUE TITLE
Array validation syntax doesn't work inside Replicator etc

### ISSUE THREAD

**Issue by jasonvarga** [statamic/cms#1702] opened 2020-04-17 17:12 UTC
## Bug Description

There's no great way to validate against fields in the same context/set inside replicator.

## How to Reproduce

```yaml
-
  handle: replicator
  field:
    type: replicator
    sets:
      intro:
        fields:
          -
            handle: add_cta
            field:
              type: toggle
          -
            handle: cta_text
            field:
              type: text
              validate: make this required if add_cta in the same set is true        
```

You might try `validate: 'require_if:replicator.*.add_cta,true'` but the `*` doesn't get replaced as expected.

## Extra Detail

Replicator already duplicates the validation rules for all the sets.
If you have `validate: somerule` on a `foo` field, it actually duplicates it for as many times as that set was used in the submitted data.

Lets say you submitted a replicator field and the first and fourth sets had that `foo` field, it would generate these rules:

```
replicator.0.foo => 'somerule',
replicator.3.foo => 'somerule',
```

I think the solution should be to allow an asterisk to represent "this field and this index".

```
validate: 'require_if:*.add_cta,true'
```
or maybe leave the asterisk to mean the index, and have a separate thing as a placeholder for the field:
```
validate: 'require_if:{parent}.*.add_cta,true'
```

Should generate something like:

```
replicator.0.foo => 'required_if:replicator.0.add_cta',
replicator.3.foo => 'required_if:replicator.3.add_cta',
```

You shouldn't need to put the name of the field you're in. It may cause issues if you're using importing that field from a fieldset etc.

## Environment

**Statamic version:** 3.0.0.-beta.26

**Comment by jasonvarga** [comment] 2020-04-17 17:57
Settled on using `{this}` as a placeholder for the parent and index.

```
validate: 'require_if:{this}.add_cta,true'
```

**Comment by lukeyouell** [comment] 2020-04-18 10:02
@jasonvarga thanks for creating this issue, I did a little more digging and found that the context of the validation wasn't being communicated in the validation process:

```
"page_builder.0.cta_text" => array:1 [
    0 => "required_if:page_builder.*.add_cta,1"
  ]
```

By the looks of things there needs to be some way of ensuring that the relative index is included in the rule. `{this}.add_cta` looks ideal!

**Comment by robdekort** [comment] 2020-08-24 11:41
Would this also apply to conditional logic? And how the syntax in the YAML file look?
```
if:
        {this}.thing: something
```

**Comment by robdekort** [comment] 2020-08-25 18:07
You can use #2289 for an example where nested validation doesn't work. It's contains an example using the `{this}` syntax if you need to test.

**Comment by jesseleite** [comment] 2020-08-25 21:19
> Would this also apply to conditional logic?

@robdekort, Nope.  Unlike validation, field conditions always check current field level context, unless you prepend root to access top-level fields (see docs on [field context](https://statamic.dev/conditional-fields#field-context)).

**Comment by robdekort** [comment] 2020-08-26 06:53
Yep, makes sense now!

**Comment by stuffedmotion** [comment] 2020-09-14 21:44
Our team is hoping this gets fixed soon as well

**Comment by twd3** [comment] 2020-12-25 20:10
Can I confirm this is still an issue? The only reason I'm asking is I think I saw validation working in the Peak starter kit and it was doing exactly what I am trying to do. I have a simple replicator that has a bard in it. The sets for both the replicator and the bard in the replicator are imported fieldsets. The issue is the simple "required" validation on the bard sets doesn't work. Says something is required when it's filled and I try to save. Only way to make imported bard sets work is nothing required.

**Comment by robdekort** [comment] 2020-12-26 16:50
Yep. Still an issue.

**Comment by twd3** [comment] 2020-12-26 18:53
Thank Rob. Hold on though, in Peak I see you have a replicator (page builder) with a set for article that is a bard. Then a bard set in there for button. How is this required validation working? I tried the same and no deal.
```
  validate:
    - 'required_if:{this}.link_type,entry'
```

**Comment by robdekort** [comment] 2020-12-28 10:44
Hi Tom. Good to hear, super nice. Tbh I'm not sure anymore under what circumstances validation works. I remember {this}. or {root}. is the proposed new syntax that isn't available yet atm. Sorry, can't help you further for now.

**Comment by jakubjo** [comment] 2021-12-04 14:51
Are there any news on the progress? 
IMHO this should be fixed as it's really a great UX enhancements.

**Closed** 2022-01-26 20:58 UTC
Labels: enhancement, fieldtypes
