### ISSUE TITLE
Bard Fieldtype: Buttons for headings are not marked as active

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#1899] opened 2020-06-05 08:48 UTC
## Bug Description
Toolbar Buttons:
The buttons for setting a heading are not aware of their active status when the text is marked again in the editor after a reload.

## How to Reproduce
1. select a text in Bard Fieldtype
2. make a heading from the selected text (e.g. h3)
3. reload the entry
4. select the headung in the text editor
5. the heading button has no active status

## Extra Detail

**Current state:**
<img width="498" alt="Bildschirmfoto 2020-06-05 um 10 43 43" src="https://user-images.githubusercontent.com/54707973/83856296-9b50b480-a719-11ea-8195-db5f0aa2568f.png">

**Expected state:**
<img width="458" alt="Bildschirmfoto 2020-06-05 um 10 44 21" src="https://user-images.githubusercontent.com/54707973/83856354-b1f70b80-a719-11ea-8ced-f45839bae2b1.png">

## Environment

**Statamic version:** 72615c4b3946db60b4550693872e9d93d208d0cc

**PHP version:** 7.{?}

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jasonvarga** [comment] 2020-09-22 16:19
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by WiebkeVog** [comment] 2021-01-04 12:15
Unfortunately, we still running into this issue (version 3.0.31). 
Could also reproduce the behavior when I specified only h1, h2 or h3 in the button configuration. Can I help with any extra details here?

**Comment by arthurperton** [comment] 2021-04-20 10:40
> Unfortunately, we still running into this issue (version 3.0.31).
> Could also reproduce the behavior when I specified only h1, h2 or h3 in the button configuration. Can I help with any extra details here?

Hi @WiebkeVog, I can't seem to reproduce your issue in Statamic 3.1.9. I tried your steps in Chrome, Safari and Firefox. The highlighting works correct in all of them. So some extra details may be helpful:

- Do you still have the issue in the current version (3.1.9 +)?
- What browser are you using?
- Any other info that comes to mind?

**Comment by WiebkeVog** [comment] 2021-05-17 08:37
Yes, under version 3.1.11 I still run into the issue. I use Chrome Version 90.0.4430.212 but could also reproduce it on Firefox and Safari browser. 
For me, the highlighting when I format a text to a H3 also works until the page reload. After I have reloaded the page and select the text again, the H3 button is no longer highlighted.

**Comment by arthurperton** [comment] 2021-05-20 08:30
Sorry @WiebkeVog, I'm still not able to reproduce, even after a page reload. Maybe there is some small detail in the steps we're doing differently. 
* Do you save before the page reload?
* What is your 'after saving' option set to?
* Is it possible for you to post a screencast of what's happening maybe?

**Comment by jasonvarga** [comment] 2021-05-20 16:07
Don't you guys have a customized Bard field?

**Comment by WiebkeVog** [comment] 2021-05-25 10:00
Oh, you're absolutely right. That seems to be due to our custom fieldtype. Funny, actually I had tested it with the Bard Fieldtype 🤔 . Well, thanks for the effort and I will close this ticket.

**Comment by WiebkeVog** [comment] 2021-05-25 12:49
I just searched further through our code, maybe it can be reproduced for you if you enable "save_html" for the Bard field. 🤷‍♀️ If not, feel free to close the ticket again. Then it's probably completely up to us :)

**Comment by arthurperton** [comment] 2021-06-22 18:50
Hi Wiebke, I just tried again with `save_html` set to `true`. Everything keeps working fine, I can't get it to malfunction. I'm closing the issue again. Thanks for your thorough investigation!

**Closed by arthurperton** 2021-06-22 18:50 UTC
Labels: bard, needs more info
