### ISSUE TITLE
Beta20: minor UI glitch on the default Home page (Visit URL)

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#1531] opened 2020-03-24 20:23 UTC
Visible when using a non-English CP: see the Visit URL button
![Capture d'écran 2020-03-24 21 22 18](https://user-images.githubusercontent.com/1823359/77473352-a338d200-6e15-11ea-836a-7e5af2fbcb6e.png)

**Comment by jasonvarga** [comment] 2020-03-24 21:04
Duplicate of #1463

**Closed by jasonvarga** 2020-03-24 21:04 UTC
Labels: UI
