### ISSUE TITLE
Iteration over terms of taxonomy field fails

### ISSUE THREAD

**Issue by mmodler** [statamic/cms#2193] opened 2020-08-07 13:19 UTC
## Bug Description

Iteration over terms of a taxonomy field fails on non-multisite install:

```
{{ relate:my_tags_field}}
{{ id }}
{{ /relate:my_tags_field}}
```

Call to a member function absoluteUrl() on null
Statamic\Taxonomies\LocalizedTerm::absoluteUrl
vendor/statamic/cms/src/Routing/Routable.php:49

## How to Reproduce

1. Create a "tags" taxonomy with some tags
2. Create a "my_tags_field" taxonomy field and assign some tags
3. Render the fields terms

```
{{ relate:my_tags_field}}
{{ id }}
{{ /relate:my_tags_field}}
```

## Extra Detail

The Routeable trait calls `$this->site()->absoluteUrl()` which depends on `$this->site()` in LocalizedTerm:

```
    public function site()
    {
        return Site::get($this->locale);
    }
```

Site::get fails because $this->locale is "de_DE" and the config key in sites.php is "default" for a non-multisite install

## Environment

**Statamic version:** 3.0.0.-beta-43

**PHP version:** 7.3.18

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by mmodler** [comment] 2020-08-07 13:27
Addition:

Site:get() looks for a site by handle, not a site by locale. It seems it is used in the codebase with handle (correct), with locale (Variables class for example) or with fallback:

```
    public function getSite($locale = null)
    {
        return Site::get($locale ?? Site::current()->handle());
    }
```

Perhaps usage of Site:get() is not refactored for v3 everywhere?

**Comment by jackmcdade** [comment] 2020-08-07 13:54
This appears to be a duplicate of #1825 and #1852 (tricky issue numbers for anyone dyslexic!(.

**Comment by mmodler** [comment] 2020-08-07 13:55
I would not wonder to see other bugs related to the Site::get() usage with locales. I saw it in other classes, too...

**Comment by mmodler** [comment] 2020-08-07 13:56
Getting a site by locale is always a bad idea, isn't it? Think of to sites configured, both with locale en_US?

**Comment by jasonvarga** [comment] 2020-08-07 14:05
The locale is always the site handle, even if the variable is named locale. We'll work it out, thanks for the info.

**Comment by jasonvarga** [comment] 2020-08-10 16:27
I lied. That was exactly the problem. The site's locale was being passed in at one spot where it should have been the handle.

It's going to be fixed for next release.

**Comment by jesseleite** [comment] 2020-08-10 16:31
Should be fixed.  Let us know if still an issue.

**Closed by jesseleite** 2020-08-10 16:31 UTC
Labels: duplicate

**Comment by mmodler** [comment] 2020-08-18 07:41
Thanks, we will try.
