### ISSUE TITLE
Empty object fro

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#6130] opened 2022-06-01 05:34 UTC
### Bug description

I have added a repeatable field and have dumped this onto my page `{{dump}}`. I can see the whole object including the vendor_logos array.

```
server_configs" => Statamic\Fields\Value {#2468 ▼
    #raw: array:2 [▼
      0 => array:4 [▼
        "server_type" => "blaze"
        "vendor_logos" => array:2 [▶]
        "type" => "new_set"
        "enabled" => true
      ]
      1 => array:4 [▼
        "server_type" => "enterprise"
        "vendor_logos" => array:3 [▶]
        "type" => "new_set"
        "enabled" => true
      ]
```

I'm using `vue.js` and passing this data to my components, but i'm just testing this right now with `{{ server_configs | to_json | entities }}`

**My Environment the object vendor_logos object is empty** 

`[{"server_type":{"value":"blaze","label":"Blaze","key":"blaze"},"vendor_logos":{},"type":"new_set"},{"server_type":{"value":"enterprise","label":"Enterprise","key":"enterprise"},"vendor_logos":{},"type":"new_set"}] 0: blaze`

**My work mates environment from the same branch has the full object**

`[{"server_type":{"value":"blaze","label":"Blaze","key":"blaze"},"vendor_logos":[{"id":"assets::logos\/vmware-ready.svg","title":"vmware-ready.svg","path":"logos\/vmware-ready.svg","filename":"vmware-ready","basename":"vmware-ready.svg","extension":"svg","is_asset":true,"is_audio":false,"is_previewable":false,"is_image":false,"is_video":false,"blueprint":{},"edit_url":"http:\/\/localhost:8000\/cp\/assets\/browse\/assets\/logos\/vmware-ready.svg\/edit","container":{},"folder":"logos","url":"\/assets\/logos\/vmware-ready.svg","permalink":"http:\/\/localhost:8000\/assets\/logos\/vmware-ready.svg","api_url":null,"size":"3.89 KB","size_bytes":3979,"size_kilobytes":3.89,"size_megabytes":0,"size_gigabytes":0,"size_b":3979,"size_kb":3.89,"size_mb":0,"size_gb":0,"last_modified":"2022-03-09T12:30:17.000000Z","last_modified_timestamp":1646789417,"last_modified_instance":"2022-03-09T12:30:17.000000Z","focus":"50-50-1","focus_css":"50% 50%","height":"187.1","width":"521.6","orientation":"landscape","ratio":2.7878140032068415,"mime_type":"image\/svg+xml"},{"id":"assets::logos\/microsoft-hyper-v.gif","title":"microsoft-hyper-v.gif","path":"logos\/microsoft-hyper-v.gif","filename":"microsoft-hyper-v","basename":"microsoft-hyper-v.gif","extension":"gif","is_asset":true,"is_audio":false,"is_previewable":false,"is_image":true,"is_video":false,"blueprint":{},"edit_url":"http:\/\/localhost:8000\/cp\/assets\/browse\/assets\/logos\/microsoft-hyper-v.gif\/edit","container":{},"folder":"logos","url":"\/assets\/logos\/microsoft-hyper-v.gif","permalink":"http:\/\/localhost:8000\/assets\/logos\/microsoft-hyper-v.gif","api_url":null,"size":"3.63 KB","size_bytes":3714,"size_kilobytes":3.63,"size_megabytes":0,"size_gigabytes":0,"size_b":3714,"size_kb":3.63,"size_mb":0,"size_gb":0,"last_modified":"2022-04-20T11:31:09.000000Z","last_modified_timestamp":1650418269,"last_modified_instance":"2022-04-20T11:31:09.000000Z","focus":"50-50-1","focus_css":"50% 50%","height":55,"width":128,"orientation":"landscape","ratio":2.327272727272727,"mime_type":"image\/gif"}],"type":"new_set"}]
`

Why is the vendor_logos object empty for me but my work mate can see the whole object using `{{ server_configs | to_json | entities }}`

### How to reproduce

Add a new repeatable field and add images to the set. This show empty on my environment but shows a full object on my work mates environment.

### Versions

Statamic 3.3.12 Pro

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2022-06-01 20:59
I can reproduce. I've created a [repository demonstrating the issue](https://github.com/StataSandboxes/cms-6130), clone it down and you'll see it straight away.

**Comment by jasonvarga** [comment] 2022-06-01 21:45
I believe this is a duplicate of #5866 although I don't know why your work mate can see the expanded items. Is he using the exact same setup as you? He's not using a different version of Statamic?

**Closed by jasonvarga** 2022-06-01 21:45 UTC
Labels: bug
