### ISSUE TITLE
I have video to explain weird behavior in CMS, I made the date field and this what I got. The behaviors:

### ISSUE THREAD

**Issue by HamzahPace** [statamic/cms#9147] opened 2023-12-07 06:17 UTC
### Bug description

When I want to sync from origin language, It doesn't work
When I change the date from the origin content, The content in different language will change UI but not functionality.

https://github.com/statamic/cms/assets/79359864/8f6ecfc1-1f67-4827-bda6-c6b926b

https://github.com/statamic/cms/assets/79359864/09992229-6c52-4748-a3c8-9db4bd43738e

43559

### How to reproduce

Create multisite, Add date-time field to any collection.
When I want to sync from origin language, It doesn't work
When I change the date from the origin content, The content in second language will change UI but not date field.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.34.2  
PHP Version: 8.2.4        
Composer Version: 2.5.8   
Environment: local        
Debug Mode: ENABLED       
URL: localhost
Maintenance Mode: OFF     

Cache
Config: NOT CACHED        
Events: NOT CACHED        
Routes: NOT CACHED        
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.36.0 PRO

Statamic Addons
aerni/social-links: 3.1.0
doublethreedigital/duplicator: 4.0.1
statamic/seo-pro: 5.3.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by HamzahPace** [comment] 2023-12-07 06:18
Another video describing the bug.
https://github.com/statamic/cms/assets/79359864/39d3c701-f4f4-4e9b-aa2a-c1341e00c1fe

**Comment by duncanmcclean** [comment] 2023-12-07 11:11
This sounds like a duplicate of #3440.

**Closed by duncanmcclean** 2023-12-07 11:11 UTC

**Comment by HamzahPace** [comment] 2023-12-20 07:54
@duncanmcclean I checked all the duplicate issues but still I can't find the solution.
