### ISSUE TITLE
Empty filter returns zero results

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#3155] opened 2021-01-26 17:53 UTC
## Bug Description

#2293 was fixed, but the same issue exists with other filtering (i.e., not taxonomy-based).

In #2293, a taxonomy filter on the collection tag would return zero results if the parameter was empty (for example, using get variables that don’t exist). This has been fixed, but other filters behave the same way and should also be fixed.

For example, to expand on the previous example:

```
{{ collection:blog limit="9" paginate="true" as="posts" taxonomy:tags="{ get:category }" author:is="{ get:author }" }}
```

- `taxonomy:tags=“{ get:category }"` is performing as expected after the fix of the previous issue. If no `category` parameter exists in the URL, it will return all items in the collection
- `author:is="{ get:author }” ` is not performing the same way, and therefore is not performing as expected. If an `author` parameter exists that matches some of the content files, the collection will be filtered correctly. If no `author` parameter exists, this will return zero results

## Environment

Statamic 3.0.40 Pro
Laravel 7.25.0
PHP 7.3.17
statamic/seo-pro 2.1.0
Fresh install from `statamic/statamic`, migrated from v2

**Comment by damcclean** [comment] 2021-01-26 18:09
This issue looks like it might be a duplicate of #3100?

**Comment by fitzage** [comment] 2021-01-26 18:10
Hmm…this doesn’t throw an error. I think it might be related, but not 100% sure it’s the same thing.

**Comment by damcclean** [comment] 2021-01-26 18:13
Okay! I'll keep it open.

**Comment by damcclean** [comment] 2021-02-02 20:47
Just confirmed with Jason, it's not a duplicate 🙂

**Closed** 2023-11-02 18:19 UTC
