### ISSUE TITLE
Cannot update asset data

### ISSUE THREAD

**Issue by pkarczmarczyk94** [statamic/cms#2839] opened 2020-11-12 14:41 UTC
## Bug Description
When I'm trying to udpate asset's alt text or set focal point Statamic shows success message "Saved!" but when entering asset again there are no changes. 

## How to Reproduce
1. Upload image assset
2. Enter asset edit view/modal
3. Change "Alt Text"
4. Click "Save" button
5. Enter asset edit view/modal 

## Environment
Statamic 3.0.26 Solo
Laravel 8.14.0
PHP 7.4.11
aerni/social-links 2.0.1
cnj/seotamic 2.0.2

**Statamic version:** 3.0.26

**PHP version:** 7.11

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by tomhelmer** [comment] 2020-11-12 14:43
Duplicate of https://github.com/statamic/cms/issues/2831

**Comment by damcclean** [comment] 2020-11-12 14:50
Yup, it' a duplicate. Closing in favor of #2831.

**Closed by damcclean** 2020-11-12 14:50 UTC
Labels: duplicate
