### ISSUE TITLE
Significantly worse loading times / TTFB on 3.3 and Larvel 9

### ISSUE THREAD

**Issue by klickreflex** [statamic/cms#5766] opened 2022-04-06 09:34 UTC
### Bug description

Not a bug, but still a huge problem I'm facing after upgrading a site to 3.3 and I'm wondering if I'm alone with these observations and/or it there's something that can be done about it.

I'm not an an expert in any (devops, webperf, php) of this, but I've received reports from clients/users about slow performance on a site running Statamic 3.3. 

So I started digging and found out this site has a local TTFB of almost one second with a completely empty frontend. My other local Statamic sites are somewhere around 150-350 ms. 

So I looked for the differences in those sites and disabled addons and the only difference standing out to me was that the slower site was running Statamic 3.3 and Laravel 9.

So I rolled back to Statamic 3.2 on both Laravel 8 and 9 and took the same measurement for loading the empty document (the bulk of which was time to first byte)

Statamic 3.3.4 / Laravel 9: 940ms 
Statamic 3.3.34 / Laravel 8: 581ms
Statamic 3.2.39 / Laravel 8: 355ms
 

![image](https://user-images.githubusercontent.com/435825/161943777-31f9fe9f-69c9-49e3-b3c2-dd54837ead64.png)

![image](https://user-images.githubusercontent.com/435825/161943849-f8238e66-cbe4-44bc-9842-6fd65fc54f43.png)

![image](https://user-images.githubusercontent.com/435825/161943710-d768404c-2f07-4730-9e9e-1323a7205cd7.png)

### How to reproduce

Compare the same site's loading time for a blank page before and after upgrading it to Statamic 3.3 and optionally Laravel 9

### Versions

Statamic 3.3.4 Pro
Laravel 9.6.0
PHP 8.0.16

---

Statamic 3.3.4 Pro
Laravel 8.83.6
PHP 8.0.16

---

Statamic 3.2.39 Pro
Laravel 8.79.0
PHP 8.0.16

### Installation

Starter Kit using via CLI

### Antlers Parser

regex (default)

### Additional details

- All measures were done locally with Valet and PHP 8.0 (but are also observable and even worse on a remote server)
- All measures were done with a completely blank layout.antlers.php, so no static assets influence results
- Addons were disabled 
- No static caching 
- No new antlers parser

**Comment by johncarter-** [comment] 2022-04-06 10:19
Might be related 🤷‍♂️ #5650

**Comment by elijahworkz** [comment] 2022-04-06 10:42
might also be related to #5752 and #5561

**Comment by jasonvarga** [comment] 2022-04-06 20:43
Do you have Laravel Telescope installed?

**Comment by klickreflex** [comment] 2022-04-07 05:04
> Do you have Laravel Telescope installed?

No.

**Comment by K3CK** [comment] 2022-04-09 08:07
I also have observed this behavior. Had the feeling it was somehow related with a page builder the site was using. I will dig further. 

@klickreflex Do you have the same problems with a blank page not using a starter kit?

**Comment by klickreflex** [comment] 2022-04-11 10:56
> @klickreflex Do you have the same problems with a blank page not using a starter kit?

A fresh installation is dramatically faster, both with and without Peak starter, though Peak is significantly slower:

Vanilla Statamic 3.3: 87ms
Fresh Statamic with Peak Starterkit: 179ms

@robdekort have you possibly noticed Peak sites being slower since 3.3 and even more with Laravel 9?

**Comment by robdekort** [comment] 2022-04-11 11:06
I had not really noticed this yet but also didn't check :-). Sorry to say.

**Comment by robdekort** [comment] 2022-04-11 11:58
Seems I get similar response times on both versions and I also get good results on a 3.3 site with Laravel 9. So I can't really replicate on my end.

**Comment by jelleroorda** [comment] 2022-04-21 09:15
I'm in the process of upgrading a large site from 3.1 -> 3.3 and had the same issues. All of a sudden a lot of pages just timed out (>30s load time).

So the upgrade contains:
- Laravel 7 -> Laravel 9
- Statamic 3.1 -> Statamic 3.3 
- PHP 7.4 -> PHP 8.1

I noticed in the debug log (once I got a single page loading within 30s) I had 80K+ deprecation warnings. Disabling debugbar got me from 28s -> 21s.

![Schermafbeelding 2022-04-21 om 11 01 10](https://user-images.githubusercontent.com/9193686/164421775-099bf1c5-8b6f-4d90-8064-13f564387215.png)

I thought the chance is pretty big that these warnings are the bottleneck, so I dropped PHP 8.1 -> PHP 8.0. After that I've updated my `composer.json` to contain `"php": "8.0.*"` after which I've run `composer update`. No dependencies were changed. The warning are now gone though, and my page now loads in 5s with debugbar of 3.5s without debugbar.

**Comment by K3CK** [comment] 2022-04-22 13:30
I can confirm the behaviour @jelleroorda reported for one of my relatively big sites. Using the debugbar I see a similar output and the same huge amount of warnings.

My upgrade contained:
- Laravel 8 -> Laravel 9
- Statamic 3.2 -> 3.3
- PHP 8.0 -> 8.1

Downgrading to PHP 8.0 with Laravel 9 and Statamic 3.3 made it slightly better, but the site was still much slower than before. So I tried a few combinations, seeing the best performance with this setup:

- Laravel 8
- Statamic 3.2
- PHP 8.1

**Comment by dryven** [comment] 2022-05-02 17:15
Same here. We updated the website of one of our customers from Statamic 3.2 to Statamic 3.3. It contains a few hundred entries (flat file). Reverted back to Statamic 3.2, hope that this can be solved soon.

**Before:**
- Statamic 3.2
- Laravel 8
- PHP 8.1
- Regex parser
- 1.4s of server side loading time

**After:** (nothing's changed except Statamic version)
- Statamic 3.3
- Laravel 8
- PHP 8.1
- Regex parser
- ~8s of server side loading time

**Comment by jackmcdade** [comment] 2022-05-03 18:49
Got a fix in the works – the issue definitely seems to be stemming from overflowing the logs with those deprecation notices.

**Comment by jackmcdade** [comment] 2022-05-03 21:15
If anyone here has a few minutes to try this PR it would be super helpful! https://github.com/statamic/cms/pull/5981

**Comment by dryven** [comment] 2022-05-06 05:27
Nice, definitely getting better!
There were 17.500 warnings in my log before and using this pull request it has improved to 4000 warnings.

It's not as fast as in 3.2, but we are moving closer.

You can find some more deprecation notices in my laravel.log: https://controlc.com/82ed996f

**Comment by jasonvarga** [comment] 2022-05-09 07:53
I've made more adjustments to deprecations in #6014 if you'd like to try that out and see if it helps any more.

@dryven would you mind letting us know what the number of log messages drops down to?

**Comment by dryven** [comment] 2022-05-09 08:26
@jasonvarga Great results, only two different deprecation warnings left (one is from Carbon):
**1st**
`Function strftime() is deprecated in /home/dryven/web/sargfabrik/vendor/nesbot/carbon/src/Carbon/Traits/Date.php on line 1853 `
**2nd**
`addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /home/dryven/web/sargfabrik/vendor/statamic/cms/src/View/Antlers/Parser.php on line 774
`

**Comment by jasonvarga** [comment] 2022-05-09 11:11
The first one is coming from the Carbon package, so I can't do anything about that. But I think it might be because you're using the `format_localized` modifier. You could try changing to the `iso_format` modifier. https://statamic.dev/modifiers/iso_format

Second one is done now. 👍

**Comment by jasonvarga** [comment] 2022-05-12 06:47
@dryven did the lower number of deprecations affect your load time at all?

**Comment by dryven** [comment] 2022-05-12 10:31
> @dryven did the lower number of deprecations affect your load time at all?

Yes, it definitely did. With all the deprecation warnings, the loading time was >30s** on my localhost (even went into a timeout sometimes). Now it's somewhere between 5s and 10s.

** _the 8s mentioned [here](https://github.com/statamic/cms/issues/5766#issuecomment-1115138776) refer to the prod. server_

**Comment by dryven** [comment] 2022-05-16 05:17
Here's what I _really_ get:

- Statamic 3.2: 1.7s
- Statamic 3.3: ~20s
- Statamic 3.3 (fix/deprecations): ~18s

I know, I mentioned 5-10s above (for the 3.3 deprecations fix) but I didn't have the exact same setup as with Statamic 3.2. What we are doing is checking if todays date is in a certain month. Before, we used `:event_date:starts_with="month"` (where month was e.g. "2022-05"). Now, that dates are Carbon instances, we had to change our system and use a custom scope where the query is extended with "$query->whereMonth(...)".

Could this lead to higher loading times?

Here you can check out the page where we are facing the above mentioned loading times: [sargfabrik.at](https://sargfabrik.at/kultur/kultur-veranstaltungen)

**Comment by jasonvarga** [comment] 2022-05-16 05:46
I'm not really sure where the problem lies. Following your link, the pages load pretty quickly, I'm guessing because you have some caching set up already. Would you be able to zip your site and send it to support@statamic.com ?

**Comment by jasonvarga** [comment] 2022-05-16 05:52
Since the original issue quotes these load times as the problem, I'm going to consider this issue closed. The time differences are measured in milliseconds which I think the deprecation messages would be the cause, fixed in #6014.

> Statamic 3.3.4 / Laravel 9: 940ms
> Statamic 3.3.34 / Laravel 8: 581ms
> Statamic 3.2.39 / Laravel 8: 355ms

@dryven Since you're experiencing many seconds of load times, I think it's a separate problem entirely. If you'd like to continue this in official support, that's probably better.

**Closed by jasonvarga** 2022-05-16 05:52 UTC
Labels: performance
