### ISSUE TITLE
Configure collection always shows 'Changes may not be saved' warning

### ISSUE THREAD

**Issue by arthurperton** [statamic/cms#3580] opened 2021-04-23 14:02 UTC
## Bug Description

Configure collection shows the "Changes that you made may not be saved" warning when you navigate away, even if you did not change anything.

## How to Reproduce

1. Go to Configure Collection
2. Go to another page or close the page

## Extra Detail

<img width="1019" alt="Screenshot 2021-04-23 at 16 01 08" src="https://user-images.githubusercontent.com/4067531/115882546-23809b00-a44d-11eb-8b98-f9a6174a7084.png">

## Environment

Statamic 3.1.9 Pro
Laravel 8.35.1
PHP 7.4.16
No addons installed

**Install method (choose one):**
Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment] 2021-04-23 14:10
Duplicate of #3500, it says it happens on both a collection configure page and an entry edit publish form.

**Closed by duncanmcclean** 2021-04-23 14:10 UTC

**Comment by arthurperton** [comment] 2021-04-23 14:16
Ah okay. There is a PR coming up though that only solves this one.. 🤔

**Comment by duncanmcclean** [comment] 2021-04-23 14:19
Oooh nice, not sure if you'd want to close that other one because it doesn't solve the whole problem.
