### ISSUE TITLE
Using a form field called message won't render in the email template

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#2242] opened 2020-08-17 15:52 UTC
## Bug Description
See [this issue](https://github.com/statamic/cms/issues/2240#issuecomment-674946078).
Using a form field called `message` prevents it from being rendered in the `email.antlers.html`template. 

## How to Reproduce
* Add a form with a field called `message` (in my case a textarea)
* Add a template for the form
* Submit the form and make sure an email goes out

## Extra Detail
The code I used can be found [here](https://github.com/studio1902/statamic-peak).
When you add a modifier to the field: `{{ message | nl2br }}` you actually get an error (got object, expected string). That might be a pointer.
Renaming the field to `message_body` solved the issue for me.

## Environment
Statamic 3.0.0-beta.44 Pro
Laravel 7.25.0
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment] 2020-08-19 04:35
This one seems to be caused by this chunk of code in Laravel here 🤔  https://github.com/laravel/framework/blob/7.x/src/Illuminate/Mail/Mailer.php#L266-L273

**Comment by jasonvarga** [comment] 2020-08-24 19:12
That's a bit of a bummer. 🤔 

Been there since literally the first commit of Laravel though.

![image](https://user-images.githubusercontent.com/105211/91085913-2310d580-e61c-11ea-896c-198f92d6bc1e.png)

We might just have to document it as being a reserved word.

**Comment by jasonvarga** [comment] 2020-08-24 19:20
Closing this in favor of https://github.com/statamic/ideas/issues/279

**Closed by jasonvarga** 2020-08-24 19:20 UTC
