### ISSUE TITLE
Can't edit page if it's not added to a structure

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1398] opened 2020-02-18 12:31 UTC
I cannot edit a page if it is not inside a structure. If I am trying to I get this error:

![image](https://user-images.githubusercontent.com/9936988/74736335-c8548680-5252-11ea-8f3c-beb28dbd9d0c.png)

This happens on Beta Version 17. To my understanding, Structures are optional. I'd like to have the default page structure to act as my navigation. Some sites should not be included.

**Comment by jasonvarga** [comment] 2020-02-18 15:21
Structures are optional, correct. But if you've opted to manage a collection with a structure, the pages all need to be in it.

**Comment by AndreasSchantl** [comment] 2020-02-19 14:20
Hmm. This should be clarified then. Having that error is not really customer friendly. So I either suggest that unlinking a page from a structure should be disabled, or making entries (even if opted to be in structures) optional to be inside a structure.

**Comment by jasonvarga** [comment] 2020-02-19 14:38
Yup. Haven't closed this issue because that outcome still sucks. Just letting you know the cause.

**Comment by jasonvarga** [comment] 2020-03-17 14:35
Most likely solved for next release with all the new structures stuff. Please re-open if that's not the case.

**Closed by jasonvarga** 2020-03-17 14:35 UTC

**Comment by AndreasSchantl** [comment] 2020-03-17 14:36
Alright. Thanks, will do!
