### ISSUE TITLE
Statamic API shows incorrect time when using the 'Now' button

### ISSUE THREAD

**Issue by nunoc66** [statamic/cms#11030] opened 2024-10-30 20:53 UTC
### Bug description

When you're publishing an entry and set the publish date/time to Now, the UI shows the time in the user's timezone, for example Pacific time, however, in the Statamic API, it shows the same time, but in the UTC timezone.

### How to reproduce

If you set the time to Now in an entry, or simply create a new entry which defaults to the publish time being the current time, it'll show your current time in your timezone, for example, 1:50 pm. However, when this entry is published, the Statamic API will show the same time (13:50), but it'll say the timezone is UTC, ruining the correct time of the entry.

### Environment

```yaml
Cache
Config: CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: database

Statamic
Addons: 1
Sites: 2 (...)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
statamic/eloquent-driver: 4.15.2

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: eloquent
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2024-10-31 11:35
Thanks for reporting!

However, it looks like this is a duplicate of #4270, so closing in favour of that one.

**Comment by duncanmcclean** [comment] 2024-10-31 19:34
I'll re-open this - I just saw the words API / UTC & Timezones, which made me think it was the same thing. 😅

**Comment by jasonvarga** [comment] 2024-10-31 19:40
> So when I create an entry, it has a datetime in my current timezone.

It's not really. When you pick June 5th at 8pm, what's to say it's your timezone? It gets saved as June 5th at 8pm in the configured timezone.

Saying that, we do have an issue open for general date/timezone improvements which would cover this.

https://github.com/statamic/ideas/issues/842

**Closed by jasonvarga** 2024-10-31 19:40 UTC
Labels: api, dates

**Comment by nunoc66** [comment] 2024-10-31 20:10
It's definitely using the user's current time (see gif below). When I create an entry, it's super confusing because it's creating it using my current time, but when I publish it, the API is going to use UTC, so I have to manually change the time to UTC.

1) Is this how it behaves for everyone? They need to manually change the time every time they publish something?

2) Ideally, the CP would display my local time, but convert and save it as UTC.

If that's difficult, then when an entry is created, it'd be nice if it displayed UTC time and not my local time. Same thing for the 'Now' button, it should default to the current time in UTC, not my current time.

![animation-8](https://github.com/user-attachments/assets/f54ab4a0-f243-41be-841f-5b76ae873a46)

**Comment by jasonvarga** [comment] 2024-10-31 20:23
Yes clicking the now button will use whatever the time is on your computer, true.

All I'm saying is that it's basically just submitting a date string. There's no timezone information going up. If you send up 2024-10-31 1:00pm it's going to use that date string and the timezone configured in `app.php`.

It's not ideal at all. We're aware of it. We should be using UTC everywhere and formatting it client side in the appropriate timezone. See https://github.com/statamic/ideas/issues/842 - it'll have to be fixed in a major version.

For now you should make your users aware that date fields are going to be expecting the timezone to be whatever is set in `app.php`, which by default is UTC.

**Comment by nunoc66** [comment] 2024-11-01 14:48
Great, thanks Jason. I'm happy to hear you're aware of the issue and are planning a fix.

In my opinion, this is a major short coming in using Statamic. If we could just have it use the timezone configured everywhere (when an entry is created and the Now button) then that would solve the problem, even if it's not formatting to the user's local time in the UI.

**Comment by jasonvarga** [comment] 2024-11-01 15:33
It should be simple to add an option that'll make the now button on the date field use the server timezone rather than the client timezone.
