### ISSUE TITLE
Search filter does not work as expected when searching a Entry fieldtype

### ISSUE THREAD

**Issue by lardnicus** [statamic/cms#4467] opened 2021-10-12 22:15 UTC
### Bug description

When using the "filter" search option in the control panel to filter a collection, if the fieldtype is an "Entries", you can only match by searching using the ID. You cannot search by using the slug, nor the Title that corresponds with that ID.

### How to reproduce

1. Add a collection that has an "Entries" fieldtype in the blueprint
2. Create a new record with a linked entry
3. Try to search for that entry using the title etc
4. Try to search for that entry using the ID or part of the ID

Image attached.

### Versions

Statamic 3.2.14

### Installation

Fresh statamic/statamic site via CLI

### Additional details

<img width="314" alt="Screen Shot 2021-10-13 at 9 02 44 am" src="https://user-images.githubusercontent.com/3169701/137036274-6a1f5d32-2397-4f49-80a1-17b99bccddec.png">

**Comment by jasonvarga** [comment] 2021-10-12 22:23
Duplicate of #2742

**Closed by jasonvarga** 2021-10-12 22:23 UTC
