### ISSUE TITLE
Sort entries behavior with toggle: false

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#4344] opened 2021-09-30 15:26 UTC
## Bug Description
I have entries, which should pushed to top by a toggle field. I want to sort them by `push:asc|date:asc` . When I activate the push toggle, the pushed entries are at first, like they should. But if I deactivate the toggle, the entries are still shown at first, because the entries yaml contains `push: false` . I think they should not be listed at first anymore. Perhaps I'm wrong or there is a better way to handle this. 

## Environment

**Statamic version:** 3.2.8

**PHP version:** 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by martink635** [comment] 2023-10-26 15:19
This is still present in the latest Statamic version.

How to reproduce:
1. Create a collection and fill it with some entries.
2. Add a new field toggle type: featured (default `false`)
3. Set the value of featured to true on some entries, do not touch the other entries
4. Try sorting them in antlers, you can't get the `true` entries on top, no matter what

If there is no value, the default blueprint field value should be used as a replacement…

I am open to creating a PR and fixing this issue, just need someone to confirm in which direction to go 🙂

**Comment by duncanmcclean** [comment] 2024-01-08 11:05
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I've followed your reproduction steps and "Entry A" (the only one I've set the toggle on) is showing first, as expected:

![CleanShot 2024-01-08 at 11 05 36](https://github.com/statamic/cms/assets/19637309/2e130a38-cc4a-4b76-b5b5-3bc288e7166e)

![CleanShot 2024-01-08 at 11 05 51](https://github.com/statamic/cms/assets/19637309/784ade8c-d9ce-4e60-a26b-4f06dc48fa49)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2024-01-08 11:05 UTC

**Comment by thomas4Bitcraft** [comment] 2024-04-06 17:26
@duncanmcclean  This error still persists in statamic 4.53.2. If i have a collection with existing entries, add a toggle field `featured` and then try to sort it by that in Graphql it does not work

**Comment by duncanmcclean** [comment] 2024-04-06 17:34
@thomas4Bitcraft It sounds like it might be specific to GraphQL, are you able to open a new issue? Thanks.
