### ISSUE TITLE
Language files break the Blueprint fieldtypes if they share the same name.

### ISSUE THREAD

**Issue by pryley** [statamic/cms#4038] opened 2021-07-22 00:04 UTC
## Bug Description

Language filenames can conflict with the Blueprint fieldtypes.

## How to Reproduce

1. Create a `/resources/lang/en/form.php` file and add some language strings to it.
2. Edit any Blueprint and click the "Create a Field" button.

## Extra Detail

It should look like this:
![image](https://user-images.githubusercontent.com/134939/126574351-cc874256-b1d8-4eed-822d-3f5ced1b4448.png)

Instead you get this:
![image](https://user-images.githubusercontent.com/134939/126574701-11ad5f96-9d49-4ab5-bffd-b7a0f9f51988.png)

## Environment

Statamic 3.1.29 Solo
Laravel 8.51.0
PHP 7.4.14
doublethreedigital/duplicator 1.3.3
edalzell/forma 0.8.12
silentz/mailchimp 2.5.6
webographen/statamic-dynamic-token 1.0.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2021-08-09 14:41
Duplicate of #2341

**Closed by jasonvarga** 2021-08-09 14:41 UTC
Labels: bug, i18n
