### ISSUE TITLE
Locales issue - translation connection issue

### ISSUE THREAD

**Issue by paliroop** [statamic/cms#6260] opened 2022-06-28 13:15 UTC
### Bug description

There are quite some time we have noticed translation connection issues. 

1. We are using German and English locales. Sometimes we experienced after creating long page in english when we click on German local it does not work. It shows strike through line on German local. But if I check the German `/cp` the page exists but Statamic can not establish connection between EN and DE.  

2. Along with that we have experienced one different translation issue. We have old collection entry which we disabled for some time but today we again enabled and updated the content and images for the existing entry.  If you check the images attached both English and German locales. It's showing published status but when I switch to EN it shows german translation disable and vice versa. On the frontend pages are existing but it does not show the connection between translations(EN+DE). 

![image](https://user-images.githubusercontent.com/40338331/176197389-cfe1f2f2-564d-473d-98f5-2288a5549d04.png)
<img width="421" alt="image" src="https://user-images.githubusercontent.com/40338331/176188290-bd22866c-487a-4faa-a736-18a8791c4b4b.png">

### How to reproduce

This problem does not appear everytime. But sometime it appears. It's so time consuming.

1. For first one, Create english page and then click on German locales then it shows strikes through line on German translation. However page will be there in `/cp`. If you click again on German local then it will create duplicate entry in DE `/cp`.
2. For second issue, you need to unpublish old collection entry and then need to update some content and publish it again. If you click on German then it shows English local disabled and if you click on English then it shows German local disabled. It could not make the connection with translation on the frontend.  

### Logs

```shell
No response
```

### Versions

Statamic 3.2.39
PHP 8.1.2
Laravel 8.83.7
Statamic Country Fieldtype 1.0.0
Statamic Redirect 2.0.0
Responsive Images 2.10.0
Seo Pro 2.3.2

### Installation

Fresh statamic/statamic site via CLI

**Comment by brandon698sherrick** [comment] 2024-05-30 07:59
Try creating shorter, separate English pages instead of one long page. This might help with the translation connection process.  Clear Statamic's cache by running php artisan statamic:cache:clear in your terminal. This can sometimes resolve temporary glitches. Check if there are newer versions of Statamic available. Newer versions might have bug fixes related to translation connections.

**Comment by duncanmcclean** [comment] 2024-08-29 16:44
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic.

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2024-08-29 16:44 UTC
Labels: multisite
