### ISSUE TITLE
The `to_json` modifier doesn't handle nested query builders

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#5866] opened 2022-04-20 06:37 UTC
### Bug description

I've added an Assets field inside of a replicator. I've uploaded 1 or multiple images which adds the image/s to the .md file. I can view and change the images in the CP, however when I view the object it is empty.

### How to reproduce

Create a Replicator, add images to the set. Show the image

```
imageset:
  -
    title: test
    logos:
      - logos/logo1.svg
      - logos/logo1.svg
      - logos/logo1.svg
    type: test1
    enabled: true
```

`{{imageset | to_json | entities }}`

Logos shows an empty object, I can view title

`[{"title”:”test”,”logos":{},"type”:”test1”},{“title”:”another,”logos":{},"type”:”test”2}]
`

### Versions

php 8.1

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Laravel Sail

**Comment by jasonvarga** [comment] 2022-04-20 19:27
The issue here is that each assets field is a query builder instance.

So it's moreso a problem with the `to_json` modifier.

Are you actually intending on just smushing the whole grid into a JSON object like that or were you just playing around before using it another way?

**Comment by ottz0** [comment] 2022-04-21 00:06
I'm just trying to display an image/s inside of a replicator set and it comes up empty, so I don't know how to output it to show the images in the browser. I want to pass the whole replicator set including the images into a `vue.js` component, so I need to the to_json to pass it to `vue.js`

**Comment by afonic** [comment] 2022-04-28 21:33
I have the same problem with 3.3.x. I think it was working OK in 3.2, I will need to check.

Until then I've created a custom modifier to augment these query builders before `json_encode`.

**Comment by afonic** [comment] 2022-05-23 22:08
Generally since 3.3.x several of our websites have issues. All of them have fairly complicated setups for example a `Replicator` field that has a set with an `Entries` field.

In this `Entries` field when using 3.2.x both `to_json` and `->toAugmentedArray()` (when using in a Tag), the values get passed just fine. In 3.3.x both are empty. I'll probably investigate and open a new issue but they seem related.

**Comment by ryanmitchell** [comment] 2022-05-24 20:23
Seems related to: https://github.com/statamic/cms/issues/6074

**Comment by afonic** [comment] 2022-05-24 21:23
They don't seem related, but I could be wrong.

It seems related to this change: https://statamic.dev/upgrade-guide/3-2-to-3-3#entries-fieldtype

My guess, when this query build is nested inside another fieldtype it's not being augmented correctly when passed to a modifier like `to_json`.

However since `{{ field | to_json | entities }}` is probably the best way to pass data to something like Vue I would like to learn if this can / will be fixed, otherwise we need to make drastic changes, blueprint-wise.

**Comment by duncanmcclean** [comment] 2022-06-01 22:15
I've managed to reproduce this bug and created [a repository demonstrating it](https://github.com/StataSandboxes/cms-6130) (from #6130)..

**Comment by duncanmcclean** [comment] 2024-04-15 16:35
This has been added/fixed in Statamic 5, which we're hoping to release in the next few days/weeks.

**Closed by duncanmcclean** 2024-04-15 16:35 UTC
Labels: assets, modifiers
