### ISSUE TITLE
Multisite 500 Error when using global header site switcher and browsing to globals

### ISSUE THREAD

**Issue by adnankussair** [statamic/cms#2932] opened 2020-11-27 23:28 UTC
## Bug Description

When attempting to visit /cp/globals when in a language other than the default using the global header site switcher, a 500 error occurs. In order to visit the globals cp editor must browser back > select the default language from the global header site switcher > then visit /cp/globals and then use the on page language switcher to change language.

## How to Reproduce

1. Select a language other than default from global header > site swticher (ie. spanish if default is english)
2. Visit /cp/globals
3. enjoy laravel 500 error page :)

## Extra Detail

<img width="253" alt="Screen Shot 2020-11-27 at 3 20 58 PM" src="https://user-images.githubusercontent.com/239259/100488727-dcbc8e00-30c4-11eb-88a2-660b66fbf5bd.png">

<img width="522" alt="Screen Shot 2020-11-27 at 3 21 13 PM" src="https://user-images.githubusercontent.com/239259/100488729-dfb77e80-30c4-11eb-888a-38fd4d9693b8.png">

<img width="819" alt="Screen Shot 2020-11-27 at 3 27 37 PM" src="https://user-images.githubusercontent.com/239259/100488784-1b524880-30c5-11eb-9245-1c70b2bc1d00.png">

## Environment

Statamic 3.0.31 Pro
Laravel 8.15.0
PHP 7.4.10
No addons installed
**Install method:** Fresh install from `statamic/statamic`

**Comment by damcclean** [comment] 2020-11-28 09:23
Duplicate of #2319.

**Closed by damcclean** 2020-11-28 09:23 UTC
