### ISSUE TITLE
Select on nav tag broken in 5.6.0

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#10215] opened 2024-05-29 11:51 UTC
### Bug description

After updating to 5.6.0 I'm greeted with errors when I run `{{ nav handle="docs" select="title|url" }}`. I think this might have to do with the new `select` modifier in #10183?

When I remove the select argument stuff works again.

### How to reproduce

Use the above code to render a nav called docs.

### Logs

```shell
[2024-05-29 11:50:27] local.ERROR: method_exists(): Argument #1 ($object_or_class) must be of type object|string, int given {"userId":"9ac4b1f3-7a4a-41d9-a8cf-acc92fd87bf5","exception":"[object] (TypeError(code: 0): method_exists(): Argument #1 ($object_or_class) must be of type object|string, int given at /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Modifiers/CoreModifiers.php:1844)
[stacktrace]
#0 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Modifiers/CoreModifiers.php(1844): method_exists(2, 'value')
#1 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(632): Statamic\\Modifiers\\CoreModifiers->Statamic\\Modifiers\\{closure}('docs', 0)
#2 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(806): Illuminate\\Support\\Arr::mapWithKeys(Array, Object(Closure))
#3 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Modifiers/CoreModifiers.php(1839): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#4 [internal function]: Statamic\\Modifiers\\CoreModifiers->Statamic\\Modifiers\\{closure}(2, 'depth')
#5 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map(Object(Closure), Array, Array)
#6 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(758): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#7 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Modifiers/CoreModifiers.php(1838): Illuminate\\Support\\Collection->map(Object(Closure))
#8 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Modifiers/Modify.php(197): Statamic\\Modifiers\\CoreModifiers->select(Object(Illuminate\\Support\\Collection), Array, Array)
#9 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Modifiers/Modify.php(154): Statamic\\Modifiers\\Modify->runModifier('select', Array)
#10 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Modifiers/Modify.php(131): Statamic\\Modifiers\\Modify->modify('select', Array)
#11 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(2624): Statamic\\Modifiers\\Modify->__call('select', Array)
#12 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1403): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->runModifier('select', Array, Object(Statamic\\Fields\\Value), Array)
#13 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(2324): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#14 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#15 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#16 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{#\\n    @name S...', Array)
#17 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/robdekor...', '{{#\\n    @name S...', Array)
#18 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(208): Statamic\\View\\Antlers\\Engine->get('/Users/robdekor...', Array)
#19 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#20 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#21 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Tags/Partial.php(29): Illuminate\\View\\View->render()
#22 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('navigation/side...')
#23 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Tags/Tags.php(152): Statamic\\Tags\\Partial->wildcard('navigation/side...')
#24 [internal function]: Statamic\\Tags\\Tags->__call('navigation/side...', Array)
#25 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func(Array)
#26 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#27 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#28 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{#\\n    @name S...', Array)
#29 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/robdekor...', '{{#\\n    @name S...', Array)
#30 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(208): Statamic\\View\\Antlers\\Engine->get('/Users/robdekor...', Array)
#31 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#32 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#33 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Tags/Partial.php(29): Illuminate\\View\\View->render()
#34 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Tags/Partial.php(13): Statamic\\Tags\\Partial->render('layout/sidebar')
#35 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Tags/Tags.php(152): Statamic\\Tags\\Partial->wildcard('layout/sidebar')
#36 [internal function]: Statamic\\Tags\\Tags->__call('layout/sidebar', Array)
#37 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(1597): call_user_func(Array)
#38 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/NodeProcessor.php(750): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->reduce(Array)
#39 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(381): Statamic\\View\\Antlers\\Language\\Runtime\\NodeProcessor->render(Array)
#40 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Language/Runtime/RuntimeParser.php(773): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->renderText('{{#\\n    @name D...', Array)
#41 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/Antlers/Engine.php(93): Statamic\\View\\Antlers\\Language\\Runtime\\RuntimeParser->parseView('/Users/robdekor...', '{{#\\n    @name D...', Array)
#42 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(208): Statamic\\View\\Antlers\\Engine->get('/Users/robdekor...', Array)
#43 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(191): Illuminate\\View\\View->getContents()
#44 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/View.php(160): Illuminate\\View\\View->renderContents()
#45 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/View/View.php(104): Illuminate\\View\\View->render()
#46 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Responses/DataResponse.php(146): Statamic\\View\\View->render()
#47 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Responses/DataResponse.php(42): Statamic\\Http\\Responses\\DataResponse->contents()
#48 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Structures/Page.php(420): Statamic\\Http\\Responses\\DataResponse->toResponse(Object(Illuminate\\Http\\Request))
#49 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(900): Statamic\\Structures\\Page->toResponse(Object(Illuminate\\Http\\Request))
#50 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#51 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Structures\\Page))
#52 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/StaticCaching/Middleware/Cache.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\StaticCaching\\Middleware\\Cache->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/AddViewPaths.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\AddViewPaths->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/Localize.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/HandleToken.php(13): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\HandleToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/StacheLock.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StacheLock->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#73 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#80 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#81 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#82 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#83 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#84 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /Users/robdekort/Sites/connect2id/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#95 /Users/robdekort/Sites/connect2id/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#96 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#99 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#100 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#101 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#102 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#103 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#104 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#105 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#106 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#107 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#108 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#109 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#110 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#111 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#112 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#113 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#114 /Users/robdekort/Sites/connect2id/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1176): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#115 /Users/robdekort/Sites/connect2id/public/index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#116 /Applications/Herd.app/Contents/Resources/valet/server.php(153): require('/Users/robdekor...')
#117 {main}
"}
```

### Environment

```yaml
Environment
Laravel Version: 11.9.1
PHP Version: 8.2.19
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.6.0 PRO

Statamic Addons
rias/statamic-color-swatches: 2.3.0
studio1902/statamic-peak-browser-appearance: 3.4.1
studio1902/statamic-peak-commands: 8.3.1
studio1902/statamic-peak-seo: 8.13.3
studio1902/statamic-peak-tools: 6.1.0
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2024-05-29 11:52
Thanks! Although, this is a duplicate of #10211.

**Closed by duncanmcclean** 2024-05-29 11:52 UTC
