### ISSUE TITLE
Make first column in entry listing clickable

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#1494] opened 2020-03-11 19:05 UTC
I have an Events collection where the entries don't have a title, only a date, it would be nice to have the first column be clickable to edit the entry

<img width="272" alt="image" src="https://user-images.githubusercontent.com/3626559/76453691-98248180-63d3-11ea-9023-e27429d2381d.png">

**Comment by jackmcdade** [comment] 2020-03-11 20:17
It's on our list but just giving you a heads up it's a bit of a low priority item.

**Comment by riasvdv** [comment] 2020-03-12 07:59
To add to this, if an entry **needs** to have a title, it would be nice to be able to generate it from different columns, like `Event on {{ date }}`

**Comment by jasonvarga** [comment] 2020-03-12 13:25
Yeah that's been a long time feature request. https://github.com/statamic/ideas/issues/78

**Comment by arthurperton** [comment] 2020-11-24 21:35
I ran into this one too. One solution would be to make the first column clickable, regardless of its content, as suggested. Another option: in Statamic v2 you could add `link: true` to any field in your blueprint/fieldset and that would make its column clickable. What would be the preferred solution? I'd be glad to make a PR for this one.

**Comment by riasvdv** [comment] 2021-01-24 15:23
Please keep this open 👍

**Comment by jelleroorda** [comment] 2021-12-26 08:13
Since statamic/ideas#78 is now closed, could this one also be closed? Or do we still want the functionality where you can click other columns (through `link: true`) or do we want to always make the first column a link?

**Comment by jasonvarga** [comment] 2021-12-26 16:08
Yeah let's close this. Looking at the discussion here, it seems that the issue is that people don't want to create the title. Since it can be automatic, that should be enough.

Feel free to scream and shout if you disagree.

**Closed by jasonvarga** 2021-12-26 16:08 UTC
Labels: ux

**Comment by arthurperton** [comment] 2021-12-27 11:04
Hmm yeah that makes sense actually 👍🏻.

I was just looking into this issue yesterday, looking for an easy way to implement the `link: true` thing. I'll leave that for now, unless this issue gets reinvigorated of course.
