### ISSUE TITLE
Date format not respected everywhere in the CP

### ISSUE THREAD

**Issue by studio1902** [statamic/cms#2018] opened 2020-07-02 14:26 UTC
## Bug Description
In `config/statamic/system.php` I set `'date_format' => 'd-m-Y'`,. However in the CP I still see American style dates. In `app.php` my `locale` is set to `en` and the timezone to `CET`.

I'm currently seeing the wrong date format in the datepicker field. In the column listing however the format is respected.

## How to Reproduce

Set your config as mentioned above.
Create a date field:

-
        handle: date
        field:
          mode: single
          time_enabled: false
          time_required: false
          earliest_date: '2020-07-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          type: date
          localizable: false
          listable: true
          display: Publish date
          instructions: 'The date when the project should be published.'

## Extra Detail
<img width="1375" alt="Screenshot 2020-07-02 at 16 25 10" src="https://user-images.githubusercontent.com/4067523/86371029-b19e5180-bc80-11ea-8a91-57003c21d539.png">
## Environment

**Statamic version:** 3.0.0.-beta-33

**PHP version:** 7.4.6

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-07-02 14:28
Duplicate of #1310

**Closed by jasonvarga** 2020-07-02 14:28 UTC
