### ISSUE TITLE
Can't limit results on a collection assets when the fieldtype is called `assets`

### ISSUE THREAD

**Issue by tao** [statamic/cms#3687] opened 2021-05-11 11:45 UTC
## Bug Description
You are able to limit assets with the assets tag.

```
  <ul>
    {{ assets container="assets" limit="2" }}
    <li>{{ title }}</li>
    {{ /assets }}
  </ul>
```

If you try this on an Assets field in a collection and the fieldtype is called `images` then it works.

```
    <ul>
      {{ images limit="2" }}
      <li>{{ title }}</li>
      {{ /images }}
    </ul>
```

If you try this when the fieldtype is called `assets`, it breaks and just returns the page title:

```
    <ul>
      {{ assets limit="2" }}
      <li>{{ title }}</li>
      {{ /assets }}
    </ul>
```

## How to Reproduce
I made an example repository: https://github.com/tao/statamic-limit-assets
You can view the http://127.0.0.1:8000/beginnings page to see the results:

## Extra Detail
![Screenshot 2021-05-11 at 13 40 18](https://user-images.githubusercontent.com/1446331/117809414-708eaa80-b25e-11eb-9e1c-9aa6d6525660.png)
![Screenshot 2021-05-11 at 13 43 31](https://user-images.githubusercontent.com/1446331/117809821-edba1f80-b25e-11eb-8cb0-4be47c34e440.png)

## Environment
Statamic 3.1.13 Solo
Laravel 8.40.0
PHP 8.0.3
statamic/ssg 0.4.0

**Install method (choose one):**
- Fresh install from Statamic Starters Creek

**Comment by duncanmcclean** [comment] 2021-05-11 12:01
That's probably happening because `assets` is the name of a tag so it's using the tag, instead of the variable from your field. 

I'm not sure if this is something that can be avoided or whether we should add it as a [reserved word](https://statamic.dev/knowledge-base/reserved-words#as-field-names) in the docs and warn people when they call an assets field `assets`.

**Comment by tao** [comment] 2021-05-11 12:03
The default handle when you add an Assets fieldtype to a blueprint is `assets`.

**Comment by duncanmcclean** [comment] 2023-12-08 17:52
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. 

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-12-08 17:52 UTC
Labels: antlers, assets
