### ISSUE TITLE
API: Scheduled entries will not be shown

### ISSUE THREAD

**Issue by helloiamlukas** [statamic/cms#4378] opened 2021-10-04 08:56 UTC
## Bug Description

When you schedule an collection entry, it will not be shown in the API after it has been published.

## How to Reproduce

1. Set up a fresh `statamic/starter-kit-starters-creek` statamic instance. 
2. Enable the Collection API and disable the API Cache in `config/statamic/api.php`
3. Set the correct Timezone in `config/app.php`
4. Add the Time to the Date field in the `Blog` Blueprint.
5. Modify the publish date/time of a blog entry to the future.
6. `/api/collections/blog/entries?sort=-date` will not show the blog entry anymore now.
7. Wait for the blog entry to be published ⏱
8. `/api/collections/blog/entries?sort=-date` will **still** not show the blog entry.

## Environment

Statamic 3.2.10 Pro
Laravel 8.62.0
PHP 7.4.24
statamic/ssg 0.8.0

**Install method (choose one):**
- `statamic new mysite statamic/starter-kit-starters-creek`

**Comment by jasonvarga** [comment] 2021-10-04 13:49
Sounds like a duplicate of #2217.

If you clear your cache (`php please stache:clear`) does the entry show up?

**Comment by helloiamlukas** [comment] 2021-10-04 14:24
Yes, after running `php please stache:clear` the entry will show up.

**Comment by jasonvarga** [comment] 2021-10-04 14:26
Closing this in favor of #2217 then.

**Closed by jasonvarga** 2021-10-04 14:26 UTC
