### ISSUE TITLE
Taxonomy field seems to break CP under certain conditions

### ISSUE THREAD

**Issue by tao** [statamic/cms#3149] opened 2021-01-24 18:38 UTC
## Bug Description
For ages I've had a taxonomy tag field assigned to a Blueprint, the field was called `type`. Recently it seems that it's causing issues on the Control Panel front-end and I'm having trouble understanding what's causing it.

If the field is called "type" in the Blueprint and the entry has a value for "type" in the file:

![Screenshot 2021-01-24 at 20 13 38](https://user-images.githubusercontent.com/1446331/105639518-829c3700-5e81-11eb-9130-59f1e49b81aa.png)

When the field is called "type" in the Blueprint but the entry has no value for "type":

![Screenshot 2021-01-24 at 20 14 09](https://user-images.githubusercontent.com/1446331/105639520-85972780-5e81-11eb-8fe6-d247ee2019a9.png)

I renamed the field from `type` to `kind` as a test and everything worked fine again.

## How to Reproduce
I'm not quite sure how to reproduce this, I have another field called `type` in another blueprint and it seems to work without this front-end error.

## Environment
Statamic 3.0.38 Pro
Laravel 8.22.1
PHP 7.4.12

**Comment by damcclean** [comment] 2021-01-24 19:02
Duplicate of #2534.

**Closed** 2021-01-24 19:02 UTC
