### ISSUE TITLE
Taxonomy Ghost Entries when Deleting

### ISSUE THREAD

**Issue by gutenberg-digital** [statamic/cms#2627] opened 2020-10-09 12:11 UTC
## Bug Description
Attempting to delete an item within a taxonomy is deleting the .MD file but not deleting it within the CMS page.
This breaks the API and the only way to remove it from the page is to stache:clear or stache:refresh.
## How to Reproduce
This is happening with a clean install. Create a new Taxonomy and link it to a collection, use the tags on the collection. 
Attempt to delete anything from the linked Taxonomy. 

## Extra Detail
There are no errors present within the console and the request is empty.
Video of the problem: 
https://www.youtube.com/watch?v=hqmhk1NYi6o

## Environment

Statamic 3.0.16 Pro
Laravel 8.9.0
PHP 7.4.11
No addons installed
- Fresh install from `statamic/statamic`

**Comment by gutenberg-digital** [comment] 2020-10-09 12:38
Stack Trace: https://flareapp.io/share/Lm8vEKA7#F60

**Comment by piljac1** [comment] 2020-10-09 13:04
Might be related to https://github.com/statamic/cms/issues/2604 (even if 2604 is regarding collection entries)

**Comment by gutenberg-digital** [comment] 2020-10-09 13:46
I have tried deleting all possible links to the taxonomy and problem still occurs.
This is not a multi-site which the other issues seem to be associated with

**Comment by jasonvarga** [comment] 2020-10-09 14:14
Duplicate of #1349

**Closed by jasonvarga** 2020-10-09 14:14 UTC
Labels: taxonomies
