### ISSUE TITLE
Issue on switching between sites while editing page

### ISSUE THREAD

**Issue by peimann** [statamic/cms#1509] opened 2020-03-16 15:07 UTC
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/40042952/76771530-bc59d700-67b4-11ea-9c95-e30c7557dcfe.png">

I've converted site to multisite and edited `config/sites.php` file as well. Then tried to edit a page in both sites. But an error occurred wen I wanted to switch between sites:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:8000/cp/structures/pages/entries/c5432651-289a-4a7d-897e-e6f83e73fe69/home/localize

createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:59)

**Comment by jasonvarga** [comment] 2020-03-16 15:53
Duplicate of #1094

**Closed by jasonvarga** 2020-03-16 15:53 UTC
