### ISSUE TITLE
Taxonomy page should throw a 404

### ISSUE THREAD

**Issue by aerni** [statamic/cms#6423] opened 2022-08-02 15:04 UTC
### Bug description

I've got a multi-site with a taxonomy. The taxonomy index page is reachable for all sites, no matter if the site was configured in the taxonomy's config. I expect the taxonomy index page to throw a 404 for all sites that haven't been configured.

### How to reproduce

I prepared and configured a multi-site for you:

1. Clone this repo: https://github.com/aerni/taxonomy-multi-site
2. Visit the localized taxonomy index pages at `/de/tags` and `/de/articles/tags`
3. Both pages work BUT they should throw a 404 because the German site hasn't been added to the sites config of the taxonomy

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.22.1
PHP Version: 8.1.6
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: taxonomy-multi-site.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: regex
Version: 3.3.25 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment] 2023-11-24 16:56
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I have two sites, I configured a taxonomy for one of the two sites. I can only access the taxonomy index page on the site I enabled it on. 

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-24 16:56 UTC
Labels: taxonomies
