### ISSUE TITLE
Renaming handle for replicator sets results in hidden sets in editor

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/cms#9783] opened 2024-03-25 18:10 UTC
### Bug description

Currently if you rename a set while it is in use, the content will remain in the entry file but the set will disappear from the backend.  I would imagine it will do the same if you deleted it.

Renaming replicator (and maybe Bard?) sets should either rename all instances of the set in use, warn you about renaming a set that is in use, or not allow you to rename the set if it is in use (least desirable).

Another solution would be to have a similar UI to the invalid set (ie. red background with a little preview of the content of the invalid set).  This would at least allow one to delete the renamed/deleted set and have a valid set of content again.

Personally I would prefer to have a warning about renaming/deleting in use sets and then have a ui to delete the set's in the entry editor after the fact.

### How to reproduce

1. Create a blueprint with a replicator and at least 2 sets in the replicator
2. Save a new entry using the blueprint and add one of each of the types of sets
3. Go back to the blueprint and rename one of the sets
4. Going back to editing the entry will show the set is gone, saving the entry will not get rid of the hidden set.

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 10.48.4
PHP Version: 8.2.12
Composer Version: 2.6.5
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 20
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.54.0 PRO

Statamic Addons
godismyjudge95/statamic-embera: 1.0.0
godismyjudge95/statamic-tailwind-dev-mode: 1.0.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment] 2024-03-25 18:42
Duplicate of https://github.com/statamic/ideas/issues/143, essentially.

**Closed by jasonvarga** 2024-03-25 18:42 UTC
Labels: fieldtypes, blueprints & fieldsets

**Comment by godismyjudge95** [comment] 2024-03-25 19:01
> Duplicate of [statamic/ideas#143](https://github.com/statamic/ideas/issues/143), essentially.

Would it not be a bug if one expects that renaming/deleting a field should do something?
It is not clear that renaming/deleting a field does nothing to the entries itself - that is the crux of this bug report.

I think following the suggestion [statamic/ideas#143](https://github.com/statamic/ideas/issues/143) (renaming every instance) is one method of solving this bug but is not the bug itself.

The simplest solution for now might be to just place a warning saying something like "Renaming this field does not affect existing content on entries, and that content will still remain (in hidden form) in the entry after renaming."

If you still think this is just a feature request that is ok; I just wanted to clarify.  :)

**Comment by jasonvarga** [comment] 2024-03-25 19:07
Yeah we can add a message saying that it won't update your data. But I don't think we'll be updating data automatically any time soon. It's too heavy handed.

**Comment by godismyjudge95** [comment] 2024-03-25 19:11
100% agree, renaming is on the level of deleting the content if the field is deleted.

My long term suggestion was to include a similar UI to the invalid set in Bard where there is a placeholder that tells you there is content with no matching field/set (giving you the handle and a preview of the content) while also giving you the option to just delete the content entirely.
