### ISSUE TITLE
Entries fieldtype shows different locale entries as separate entries

### ISSUE THREAD

**Issue by riasvdv** [statamic/cms#2449] opened 2020-09-17 09:25 UTC
## Bug Description

When using multisite (multiple locales) and you have an entry translated, the entries fieldtype shows each version of the entry in the dropdown

## How to Reproduce

- Have a multisite setup
- Add an entries fieldtype to relate entries

## Extra Detail

![image](https://user-images.githubusercontent.com/3626559/93452147-5cb1c500-f8d8-11ea-927e-dff7a8d616fe.png)

## Environment

Statamic 3.0.9 Pro
Laravel 7.28.1
PHP 7.4.8

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment] 2020-09-18 20:51
Duplicate of #1835

**Closed by jasonvarga** 2020-09-18 20:51 UTC
Labels: multisite
