### ISSUE TITLE
Moving an asset wipes associated metadata (i.e. alt text, captions,...)

### ISSUE THREAD

**Issue by peterkelm** [statamic/cms#4190] opened 2021-08-28 15:49 UTC
## Bug Description
Moving an asset via the Control Panel recreates the metadata associated with it. This leads to **data loss**, e.g. of alt text, captions,... 

## How to Reproduce
- Using the Statamic "creek" starter kit
- Add an alt text to one of the existing assets
- Create a subfolder in the assets container (or move it to the existing "site" folder)
- Move the asset with the alt text there
- Open the asset again, the alt text is gone...

## Extra Detail
Nothing in particular...

## Environment
Statamic 3.1.35 Pro
Laravel 8.55.0
PHP 7.3.11
statamic/ssg 0.4.0

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment] 2021-08-29 18:31
Duplicate of #3896

**Closed by jasonvarga** 2021-08-29 18:31 UTC
