### ISSUE TITLE
Drag'n'Drop in Replicator always at end of sets

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#7838] opened 2023-04-05 10:09 UTC
### Bug description

1. Set is moved to end
2. Change is not getting saved

https://user-images.githubusercontent.com/38906163/230050416-b3807720-e44a-474a-8115-bfc7d42f2e09.mov

### How to reproduce

See video above. 

### Environment

```yaml
Version: 4.0.0-alpha.2 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment] 2023-04-06 21:18
@jackmcdade this was caused by the Replicator changes in #7819
Has to do with the set's draggable bit now being nested in another div. I'd fix it but I think you may be in the middle of some other replicator tweaks.

![CleanShot 2023-04-06 at 17 18 12](https://user-images.githubusercontent.com/105211/230495855-78a3d659-9363-4182-a5a2-0d4a4e0c7150.png)

**Comment by jackmcdade** [comment] 2023-04-06 22:31
Ahhh, should have realized that would have side effects. I don’t have anything else on the works at the moment.

**Comment by jasonvarga** [comment] 2023-04-07 13:56
Fixed by #7867

**Closed by jasonvarga** 2023-04-07 13:56 UTC
Labels: ui, fieldtypes, 4.0
