### ISSUE TITLE
Duplicate query

### ISSUE THREAD

**Issue by tolawho** [statamic/cms#1974] opened 2020-06-23 15:36 UTC
## Description
![image](https://user-images.githubusercontent.com/12527881/85423722-3adac780-b5a1-11ea-8477-fb428a920403.png)

## Environment

**Statamic version:** 3.0.0.-beta-31

**Comment by jasonvarga** [comment] 2020-06-23 15:37
Duplicate of #1511

**Closed by jasonvarga** 2020-06-23 15:37 UTC
