### ISSUE TITLE
Structures bug str

### ISSUE THREAD

**Issue by Sceko** [statamic/cms#1254] opened 2020-01-23 10:04 UTC
After create

Facade\Ignition\Exceptions\ViewException
Argument 1 passed to Statamic\Support\Str::bool() must be of the type boolean, null given, called in /Users/sceko/code/statamic3/storage/framework/views/d7fa77b430aff4db3570430a909e652063a8cd14.php on line 18 (View: /Users/sceko/code/statamic3/vendor/statamic/cms/resources/views/structures/show.blade.php)

**Comment by jackmcdade** [comment] 2020-01-23 14:24
Thanks for the report! This is actually a duplicate of #1218 though so I'll be closing it.

**Closed by jackmcdade** 2020-01-23 14:24 UTC
