### ISSUE TITLE
Data Loss: Renaming a folder in certain situations deletes all assets

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#5405] opened 2022-03-03 19:57 UTC
### Bug description

Attempting to rename an S3 folder caused all images to be deleted.

### How to reproduce

We use S3 for our assets. In a public container we have a 2022 folder. Inside there we have folders `01`, `02`, `03` etc.

![CleanShot 2022-03-03 at 11 51 22@2x](https://user-images.githubusercontent.com/6069653/156642074-73ac4e4c-eaa8-4050-bfde-01eceb602972.png)

A user went in to the 2022 folder (in the CP) and created a new folder, accidentally naming it `0`. They then used the actions button to Rename it to `04`. In the CP the action never completed:

<img width="1440" alt="CleanShot 2022-03-03 at 11 38 13@2x" src="https://user-images.githubusercontent.com/6069653/156642244-b62d823b-381a-4d51-9e01-43ba630f9f8d.png">

They then refreshed the browser and it looked like all folders were missing in the 2022 folder. 

However on S3, the FOLDERS where there but all the content gone:

![CleanShot 2022-03-03 at 11 54 10@2x](https://user-images.githubusercontent.com/6069653/156642509-76715bc3-12bb-4b4f-869e-f9df87a6e360.png)

Needless to say this was pretty serious and we lost all of our images for the whole 2022 year.

### Versions

Statamic 3.2.35 Pro
Laravel 8.83.3
PHP 8.1.3
aryehraber/statamic-captcha 1.7.0
aryehraber/statamic-uuid 2.0.3
doublethreedigital/duplicator 2.1.1
doublethreedigital/runway 2.3.0
edalzell/forma 1.0
edalzell/private-eye dev-main
jonassiewertsen/statamic-livewire 2.7.1
statamic/seo-pro 2.3.2
transformstudios/events 3.3.3
transformstudios/front 1.9.2
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/memorial dev-main
transformstudios/review 3.2.1
transformstudios/simple dev-main
transformstudios/takeover-redirects dev-main

### Installation

Starter Kit using via CLI

**Comment by duncanmcclean** [comment] 2022-03-04 10:22
I believe this is a duplicate of #5405?

**Comment by arthurperton** [comment] 2022-03-08 11:30
Dev update: I am currently looking into this. I am able to reproduce this issue, but only when the folder is named '0' initially, like in the issue report. When using another name initially, it doesn't happen. First thing that comes to mind is that the string '0' is 'falsy'. Not sure how that would lead to this problem though. Hope to find out more soon.

**Comment by jasonvarga** [comment] 2022-03-08 15:45
Another update: I followed Arthur's steps to reproduce this, and I noticed that the assets didn't get deleted - they all got _moved_ into the newly renamed folder.

**Closed** 2022-03-09 19:30 UTC
Labels: critical
