### ISSUE TITLE
{{ message }} is blank in form email 

### ISSUE THREAD

**Issue by MikeHarrison** [statamic/cms#2313] opened 2020-08-28 10:20 UTC
## Bug Description
When using a custom email template for my contact form, the {{ message }} is coming through as blank.

## How to Reproduce

- Set up a new form with a `message` textarea. Mine is included in the extra details below:
- Create an email template which includes the {{ message }}, and use it as an email for that form.
- Submit the form

## Extra Detail
**Message code from contact form:**
```
<label class="block mb-1 uppercase text-sm tracking-wider" for="message">Message</label>
<textarea class="rounded-none h-32 text-forminput bg-transparent border-b border-shelve-night block w-full p-2 focus:bg-shelve-mist-darker focus:outline-none" name="message" id="message">{{ old:message }}</textarea>
```
I am using {{ message }} to try and display this in my email

## Environment

**Statamic** 3.0.2 Pro
**Laravel** 7.26.1
**PHP** 7.2.1
**Addons:**
austenc/statamic-instagram-feed 2.2.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by edalzell** [comment] 2020-08-28 14:45
Can’t use ‘message’ as a field name. Reserved via Laravel I believe

**Comment by MikeHarrison** [comment] 2020-08-28 15:07
Ah yes that fixed it! Switched from `message` to `message_content` and all worked perfectly.

I was following this blueprint in the docs: [https://statamic.dev/forms#the-blueprint](https://statamic.dev/forms#the-blueprint) which uses `message`. This could probably do with changing

**Comment by jesseleite** [comment] 2020-08-29 00:09
Indeed!  Closing this though, as it's duplicate of https://github.com/statamic/ideas/issues/279

**Closed by jesseleite** 2020-08-29 00:09 UTC
