### ISSUE TITLE
Taxonomy terms field only list the first 15 items in CP

### ISSUE THREAD

**Issue by ockam** [statamic/cms#2335] opened 2020-08-31 14:37 UTC
## Bug Description
I created a Taxonomy with 22 entries. I then use a Taxonomy Terms field on a collection with the Select Dropdown option. It only shows the first 15 items. Typing only find items in those 15 items.

The other 2 modes (type-ahead, stack) work correctly.

**Statamic version:** 3.0.2

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment] 2020-08-31 15:25
That does sound like this issue, but it should be fixed by now: 
https://github.com/statamic/cms/issues/1311

Related? Maybe not?

**Comment by ockam** [comment] 2020-08-31 15:27
Same thing: looks like we may have a regression here.

**Comment by MattRogowski** [comment] 2020-09-13 21:26
The same issue affects the Entries field, when displaying as a select dropdown only.

**Comment by jasonvarga** [comment] 2020-09-30 14:28
Duplicate of #1727

**Closed by jasonvarga** 2020-09-30 14:28 UTC
