### ISSUE TITLE
Error when uploading asset

### ISSUE THREAD

**Issue by freshface** [statamic/cms#2695] opened 2020-10-20 11:47 UTC
## How to Reproduce

Uploading a file.
Got this error: Call to a member function allowUploads() on null

## Environment

**Statamic version:** 3.0.19

**PHP version:** 7.3

**Install method (choose one):**

- Fresh install

**Comment by jasonvarga** [comment] 2020-10-20 17:27
Duplicate of #1663

**Closed by jasonvarga** 2020-10-20 17:27 UTC
