### ISSUE TITLE
"Manage publish state" permission not working

### ISSUE THREAD

**Issue by steveooo1** [statamic/cms#1011] opened 2019-11-27 22:49 UTC
I created a test user with a role that disallows managing publish states. E.g. for authors that only are able to create stuff, but not publish it before a proofreader approves this. I unchecked the "Manage publish state" option but still, I am able as the user to publish entries.

<img width="407" alt="CleanShot 2019-11-27 at 23 46 44@2x" src="https://user-images.githubusercontent.com/58191591/69764396-77ac2080-1170-11ea-93d1-7660a4ace517.png">

<img width="372" alt="CleanShot 2019-11-27 at 23 49 22@2x" src="https://user-images.githubusercontent.com/58191591/69764442-990d0c80-1170-11ea-96f4-3a2c8949b12b.png">

The resources/users/roles.yaml:
```
author:
  title: Author
  permissions:
    - 'access cp'
    - 'view test entries'
    - 'edit test entries'
    - 'create test entries'
```

**Comment by goellner** [comment] 2019-12-03 10:51
I just set up the exact same thing, since I will need it for a project. I can confirm, that the user can manage the publish state, which he shouldn't.

**Comment by taoguangc** [comment] 2019-12-20 12:45
Yes I have this problem too! And at the page list can sort pages.

**Comment by steveooo1** [comment] 2020-02-12 21:55
I hope this gets fixed in a future release!

**Comment by jasonvarga** [comment] 2020-02-12 21:56
It cannot be fixed in a previous release!

**Comment by steveooo1** [comment] 2020-02-14 22:42
Therefore it must be fixed in a future release…or the current.

**Comment by steveooo1** [comment] 2020-02-14 22:43
Wanna fight?! 4pm in the backjard of your school. 1 vs 1.

**Comment by steveooo1** [comment] 2020-02-14 22:44
I bring my bike crib gang..

**Comment by tbruckmaier** [comment] 2020-10-21 16:49
The logic seems to work when revisions are enabled, though there are some UX issues: the user without the publish permission sees the "publish" button, but a click on it returns "error: request failed with status 403" and the entry is (correctly) not published. The user with publish rights can publish afterwards.

Probably the user without publish rights should not see the publish button in the first place. I've also seen that publishing changes the revision's author to the publishing user, I'm not sure if that is intended?

And if the non-publishing user saves a revision, he can no longer edit anything, as the form is displayed as readonly. Only if his changes are published, he can create a new revision. Or am I using this wrong?

**Comment by damcclean** [comment] 2020-12-19 19:05
I've created a pull request which will set the published toggle to be read only if a user doesn't have the correct set of permissions. #3039

**Closed** 2021-01-05 21:51 UTC
Labels: bug
