### ISSUE TITLE
Forge deploy error when using S3 disk

### ISSUE THREAD

**Issue by mynetx** [statamic/cms#9159] opened 2023-12-08 09:27 UTC
### Bug description

When using Laravel Forge to deploy my site, deployment throws this error:

```
In UnableToSetVisibility.php line 33:
                                                         
  Unable to set visibility for file images/1020132.jpg.  
```

### How to reproduce

Push something to my repo, which triggers a deploy.

### Logs

```shell
[2023-12-08 09:21:03] production.ERROR: Unable to set visibility for file images/1020132.jpg. {"exception":"[object] (League\\Flysystem\\UnableToSetVisibility(code: 0): Unable to set visibility for file images/1020132.jpg. at /home/forge/xyxyxyxyxy.com/vendor/league/flysystem/src/UnableToSetVisibility.php:33)
[stacktrace]
#0 /home/forge/xyxyxyxyxy.com/vendor/league/flysystem-local/LocalFilesystemAdapter.php(460): League\\Flysystem\\UnableToSetVisibility::atLocation()
#1 /home/forge/xyxyxyxyxy.com/vendor/league/flysystem-local/LocalFilesystemAdapter.php(358): League\\Flysystem\\Local\\LocalFilesystemAdapter->setPermissions()
#2 /home/forge/xyxyxyxyxy.com/vendor/league/flysystem-local/LocalFilesystemAdapter.php(128): League\\Flysystem\\Local\\LocalFilesystemAdapter->setVisibility()
#3 /home/forge/xyxyxyxyxy.com/vendor/league/flysystem-local/LocalFilesystemAdapter.php(107): League\\Flysystem\\Local\\LocalFilesystemAdapter->writeToFile()
#4 /home/forge/xyxyxyxyxy.com/vendor/league/flysystem/src/Filesystem.php(66): League\\Flysystem\\Local\\LocalFilesystemAdapter->writeStream()
#5 /home/forge/xyxyxyxyxy.com/vendor/league/flysystem/src/MountManager.php(369): League\\Flysystem\\Filesystem->writeStream()
#6 /home/forge/xyxyxyxyxy.com/vendor/league/flysystem/src/MountManager.php(244): League\\Flysystem\\MountManager->copyAcrossFilesystem()
#7 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Imaging/Attributes.php(26): League\\Flysystem\\MountManager->copy()
#8 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Statamic\\Imaging\\Attributes->from()
#9 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Attributes.php(69): Illuminate\\Support\\Facades\\Facade::__callStatic()
#10 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Attributes.php(34): Statamic\\Assets\\Attributes->getImageAttributes()
#11 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Asset.php(273): Statamic\\Assets\\Attributes->get()
#12 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Asset.php(247): Statamic\\Assets\\Asset->generateMeta()
#13 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(438): Statamic\\Assets\\Asset->Statamic\\Assets\\{closure}()
#14 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(429): Illuminate\\Cache\\Repository->rememberForever()
#15 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Cache\\CacheManager->__call()
#16 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Asset.php(242): Illuminate\\Support\\Facades\\Facade::__callStatic()
#17 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Asset.php(173): Statamic\\Assets\\Asset->meta()
#18 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Asset.php(130): Statamic\\Assets\\Asset->hydrate()
#19 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Assets/Asset.php(846): Statamic\\Assets\\Asset->get()
#20 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Searchable.php(17): Statamic\\Assets\\Asset->title()
#21 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Searchables.php(73): Statamic\\Assets\\Asset->getSearchValue()
#22 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(585): Statamic\\Search\\Searchables->Statamic\\Search\\{closure}()
#23 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(825): Illuminate\\Support\\Arr::mapWithKeys()
#24 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Searchables.php(72): Illuminate\\Support\\Collection->mapWithKeys()
#25 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Index.php(82): Statamic\\Search\\Searchables->fields()
#26 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(585): Statamic\\Search\\Index->Statamic\\Search\\{closure}()
#27 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(825): Illuminate\\Support\\Arr::mapWithKeys()
#28 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Index.php(81): Illuminate\\Support\\Collection->mapWithKeys()
#29 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Index.php(60): Statamic\\Search\\Index->insertMultiple()
#30 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(238): Statamic\\Search\\Index->Statamic\\Search\\{closure}()
#31 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Index.php(60): Illuminate\\Support\\LazyCollection->each()
#32 /home/forge/xyxyxyxyxy.com/vendor/statamic/cms/src/Search/Commands/Update.php(25): Statamic\\Search\\Index->update()
#33 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Statamic\\Search\\Commands\\Update->handle()
#34 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#36 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#37 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#38 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#39 /home/forge/xyxyxyxyxy.com/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#40 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#41 /home/forge/xyxyxyxyxy.com/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#42 /home/forge/xyxyxyxyxy.com/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#43 /home/forge/xyxyxyxyxy.com/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#44 /home/forge/xyxyxyxyxy.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#45 /home/forge/xyxyxyxyxy.com/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#46 {main}
"}
```

### Environment

```yaml
AWS_ACCESS_KEY_ID="XXXXXXXXXXXX"
AWS_SECRET_ACCESS_KEY="XXXXXXXXXXXXXXX"
AWS_DEFAULT_REGION=eu-west-1
AWS_BUCKET=xyxyxyxyxy
AWS_URL="https://xyxyxyxyxyxy.s3.eu-west-1.amazonaws.com"
AWS_USE_PATH_STYLE_ENDPOINT=false
```

```php
// filesystem:

        'cloud' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'visibility' => 'public', // https://statamic.dev/assets#visibility
            'throw' => false,
            'cache' => true,
        ],
```

```yaml
**Environment**
Application Name: Statamic
Laravel Version: 10.30.1
PHP Version: 8.3.0
Composer Version: 2.6.5
Environment: production
Debug Mode: OFF
URL: xyxyxyxyxyxy.com
Maintenance Mode: ENABLED

**Cache**
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

**Drivers**
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

**Statamic**
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.39.0 Solo

**Statamic Addons**
doublethreedigital/runway: 5.5.2
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment] 2023-12-08 09:44
Duplicate of #7293.

What does your deployment script look like? Are you running `php please statamic:assets:generate-presets` during deployment?

**Closed by duncanmcclean** 2023-12-08 09:44 UTC

**Comment by mynetx** [comment] 2023-12-08 12:36
```
// git pull here

if [[ $FORGE_DEPLOY_MESSAGE =~ "[BOT]" ]]; then
    echo "Automatically committed on production. Nothing to deploy."
    exit 0
fi

# remove after Static cache is enabled
$FORGE_PHP artisan down

$FORGE_COMPOSER install --no-interaction --prefer-dist --optimize-autoloader --no-dev
npm ci
npm run build
$FORGE_PHP artisan cache:clear
$FORGE_PHP artisan config:cache
$FORGE_PHP artisan route:cache
$FORGE_PHP artisan statamic:stache:warm
# $FORGE_PHP artisan queue:restart
$FORGE_PHP artisan statamic:search:update --all
$FORGE_PHP artisan statamic:static:clear
$FORGE_PHP artisan statamic:static:warm # --queue

( flock -w 10 9 || exit 1
    echo 'Restarting FPM...'; sudo -S service $FORGE_PHP_FPM reload ) 9>/tmp/fpmlock

if [ -f artisan ]; then
    $FORGE_PHP artisan migrate --force
fi

# remove after Static cache is enabled
$FORGE_PHP artisan up
```

**Comment by mynetx** [comment] 2023-12-09 14:53
@duncanmcclean No, I am not. Unless it is called by one of the `artisan` commands above?

**Comment by duncanmcclean** [comment] 2023-12-11 12:28
From reviewing the stack trace, it seems to be happening during the `$FORGE_PHP artisan statamic:search:update` command.

I'd recommend subscribing to #7293 for a notification when the bug is resolved:

![CleanShot 2023-12-11 at 12 28 04](https://github.com/statamic/cms/assets/19637309/42e4c1f6-96d8-4843-8c85-37613ea1cdbe)
