### ISSUE TITLE
SELECT field missing in the pre-rendered form template snippets

### ISSUE THREAD

**Issue by pryley** [statamic/cms#2311] opened 2020-08-27 23:49 UTC
## Bug Description

![image](https://user-images.githubusercontent.com/134939/91505297-e00d6700-e894-11ea-996d-77e81834acce.png)

Running `php artisan vendor:publish --tag=statamic-forms` copies over the form field template snippets, but it is missing a `select.antlers.html` field.

## How to Reproduce

1. Run `php artisan vendor:publish --tag=statamic-forms`
2. Meander over to `/resources/views/vendor/statamic/forms/fields/`
3. Scratch your head as you gaze upon the singularly inadequate `default.antlers.html` who is unsuccessfully masquerading as the missing select field. 

I expect the `select.antlers.html` field, if it existed, would look something like this:

```html
<select name="{{ handle }}" {{ validate | contains:required ?= "required" }}>
    {{ foreach:options }}
        <option value="{{ key }}" {{ old | contains:key ?= "selected" }}>{{ value }}</option>
    {{ /foreach:options }}
</select>
```

## Extra Detail

![image](https://user-images.githubusercontent.com/134939/91505647-b30d8400-e895-11ea-9f71-5b153be25643.png)

## Environment

- Statamic 3.0.1 Pro
- Laravel 7.25.0
- PHP 7.4.8
- aryehraber/statamic-impersonator 2.0.0
- laraluke/statamic-api-select 1.0.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jesseleite** [comment] 2020-08-28 01:34
More fieldtype views coming 👍  Also this is a duplicate of https://github.com/statamic/cms/issues/2311

**Closed by jesseleite** 2020-08-28 01:34 UTC
