### ISSUE TITLE
unusable "hidden" field, as you cannot assign a default value to a field

### ISSUE THREAD

**Issue by verybigelephants** [statamic/cms#2348] opened 2020-09-01 23:33 UTC
## Bug Description
when adding a field to a blueprint, you cannot assign a default value. this makes some inputs, such as "hidden" unusable, as you would usually use such field to add a predefined value to a page/collection (this worked in statamic2)

## How to Reproduce
create a new field in any blueprint and do not add it a default value 

## Extra Detail
before:
![original](https://user-images.githubusercontent.com/3118985/91916092-8a81f180-ecbc-11ea-94cd-567b2683d499.png)
after:
![new](https://user-images.githubusercontent.com/3118985/91916103-8f46a580-ecbc-11ea-8cb8-7516fac9034f.png)

## Environment
all of them

**Statamic version:** 3.0.{?}
3.0.2

**PHP version:** 7.{?}
7.anything

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-09-01 23:37
Duplicate of #672

**Closed** 2020-09-01 23:37 UTC
