### ISSUE TITLE
Renamed asset is not available until page refresh

### ISSUE THREAD

**Issue by adevade** [statamic/cms#5944] opened 2022-04-28 18:24 UTC
### Bug description

When renaming an asset on an entry, you can't open the asset again until you reload the page.

![Screenshot from 2022-04-28 20-14-35](https://user-images.githubusercontent.com/1066486/165819807-f8004938-5f01-457d-b886-6af3f37f70ba.png)

![Screenshot from 2022-04-28 20-15-01](https://user-images.githubusercontent.com/1066486/165819849-9a5defd1-dae5-4d6c-a30b-077dc2ee1f7d.png)

### How to reproduce

Repo: [adevade/statamic-rename-asset-bug](https://github.com/adevade/statamic-rename-asset-bug)

- Open an entry (ex. Page) with an asset field type
- Click on the filename to open inspector
- Rename file
- Change is not reflected in UI, and clicking on the filename again opens forever loading inspector without content.

![Screenshot from 2022-04-28 20-15-21](https://user-images.githubusercontent.com/1066486/165819905-e3e32fc5-7de9-45ea-8683-5466aee5cd32.png)

### Versions

Statamic 3.3.9 Solo
Laravel 9.10.1
PHP 8.1.4
No addons installed

Tested on:
- Chromium on Manjaro Linux
- Edge on Windows 11

### Installation

Fresh statamic/statamic site via CLI

-----

EDIT: Rename reproduction repo.

**Comment by OleksiiBrylin** [comment] 2022-06-13 13:29
Same for me: 
Statamic 3.3.15
PHP 8.1.4

Also user can not Save & Publish after rename. Refreshing of Entry page helps.

**Comment by duncanmcclean** [comment] 2023-11-20 21:06
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. When I rename an asset, the modal closes and I can click back into the asset without any issues:

![CleanShot 2023-11-20 at 21 05 02](https://github.com/statamic/cms/assets/19637309/b8c4b386-a15c-4881-96ab-e38b62a432dc)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-20 21:06 UTC
Labels: assets
