### ISSUE TITLE
Can't put heading after image in Bard properly

### ISSUE THREAD

**Issue by dmgawel** [statamic/cms#4990] opened 2021-12-30 11:28 UTC
### Bug description

Here's a video of my colleague struggling to insert a heading after an image:

https://user-images.githubusercontent.com/1322846/147747448-a09509a8-c011-4b18-9df8-bd076450df90.mp4

It seems to me that the fact that Image Node in Bard is inline interferes with a following heading and results in image being wrapped in heading tag, like so:
```html
<h2><img src="" data-src="asset::assets::donut.jpg">This is a heading</h2>
```

### How to reproduce

1. Create Bard field
2. Insert image
3. Insert heading after image

### Versions

Statamic 3.2.28 Pro
Laravel 8.61.0
PHP 8.0.11
doublethreedigital/duplicator 2.0.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by j3ll3yfi5h** [comment] 2022-09-14 14:30
This could maybe tackled together with https://github.com/statamic/ideas/issues/500

**Comment by duncanmcclean** [comment] 2023-11-21 12:42
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I can add headings after inline images as expected.

![CleanShot 2023-11-21 at 12 41 05](https://github.com/statamic/cms/assets/19637309/a19ecee2-b0ff-4748-83f6-b8c5947d870b)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-21 12:42 UTC
Labels: bard
