### ISSUE TITLE
Unable to store root page

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#3140] opened 2021-01-21 16:17 UTC
## Bug Description
This seems to be related to the latest update. Currently there is an error `Argument 1 passed to
Statamic\Structures\Tree::page() must be of the type string, null given`, when saving the root page. The `EntriesController` is looking for a parent, where there is non.

## How to Reproduce
1. Create a new Statamic project using the CLI `statamic new prj`
2. Create a superuser and login
3. Go to "Collection" -> "Pages" and open "Home"
4. Try to store, you'll get the error message mentioned above.

## Environment
**Statamic version:** 3.0.39

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2021-01-21 16:34
Duplicate of #3135 

Tagging a release now.

**Comment by FlorianMoser** [comment] 2021-01-21 16:40
Sorry, didn't search in the closed issues for a problem with a recent release. May I suggest to leave the issues open until the releases are tagged? That could reduce the duplicates.

**Comment by damcclean** [comment] 2021-01-21 16:46
Released in [v3.0.40](https://github.com/statamic/cms/releases/tag/v3.0.40)

**Closed by damcclean** 2021-01-21 16:46 UTC
