### ISSUE TITLE
Fresh install not working?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#5133] opened 2022-01-26 09:53 UTC
### Bug description

- Installed a new blank site using statamic CLI
- Used valet link
- Visit local website
- Error: InvalidArgumentException Passed value cannot be an array

![Screenshot 2022-01-26 at 09 51 02](https://user-images.githubusercontent.com/72254741/151141254-7f58ae76-269a-4113-879e-758a2270fd9b.png)

### How to reproduce

Install a fresh copy of Statamic 3.2.31

### Logs

```shell
[2022-01-26 09:50:34] local.ERROR: Passed value cannot be an array {"exception":"[object] (InvalidArgumentException(code: 0): Passed value cannot be an array at /Users/stephenmeehan/Repositories/a-test2/vendor/statamic/stringy/src/Stringy.php:45)
```

### Versions

Statamic 3.2.31 Pro
Laravel 8.81.0
PHP 8.0.8
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2022-01-26 10:00
Duplicate of #5126, will be fixed in the next release.

**Closed by duncanmcclean** 2022-01-26 10:00 UTC
