### ISSUE TITLE
Issue with translation file

### ISSUE THREAD

**Issue by MrMooky** [statamic/cms#5116] opened 2022-01-23 14:46 UTC
### Bug description

A while ago I created a translation file `en/dashboard.php`. Today I wanted to log in to the Statamic backend but got the error:

```
htmlspecialchars(): Argument #1 ($string) must be of type string, array given
```

It took me a while to figure it out and it seems to be somewhat Laravel related, but I figured I post this here as the problem only occurs with Statamic routes.

I debugged the core function to figure out what was going on. Apparently, Statamic (Laravel?) uses my dashboard.php language file and wanted to output the array `"metaTitle" => "Dashboard"`, but the function expects `string|null`.

<img width="852" alt="Screenshot 2022-01-23 at 15 43 17" src="https://user-images.githubusercontent.com/3603346/150683966-37192aec-eeb2-4b68-be19-b75a0cf9fd24.png">

Again, I'm not sure if this is the right place to post this error. Of course, I can fix it by renaming my translation file, but it probably should not take any effect at all.

### How to reproduce

Create a language file `en/dashboard.php`, assign a translation and log into the Statamic dashboard.

### Versions

Statamic 3.2.31 Solo
Laravel 8.80.0
PHP 8.0.11
No addons installed

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment] 2022-01-23 14:59
Duplicate of #2341

**Closed by jasonvarga** 2022-01-23 14:59 UTC
