### ISSUE TITLE
Conditions not working in fieldsets

### ISSUE THREAD

**Issue by Oleafeon** [statamic/cms#6836] opened 2022-10-06 07:51 UTC
### Bug description

I was working with conditions and noticed that the fieldsets in the drobdown is not working.

fieldset:
![image](https://user-images.githubusercontent.com/20043831/194246222-26c8e430-4a7c-4254-953b-fa151304a6c4.png)

media type
![image](https://user-images.githubusercontent.com/20043831/194246471-1489855f-2a1a-44bf-bd4f-e8f23246f14a.png)

image (Condition)
![image](https://user-images.githubusercontent.com/20043831/194246610-f8f8842f-e080-4098-93f7-b6cbd193f5e9.png)

When i write in the field the handle of media type then it works fine.

I also noticed that when you use fieldsets in blueprints you get numbers and not the name of the fieldset
![image](https://user-images.githubusercontent.com/20043831/194248174-772b510a-e0a2-4d2a-ac78-27daa6a5129f.png)

### How to reproduce

1. create a fieldset
2. add some fields
3. add an select field with some options
4. add conditions to the first fields

### Environment

```yaml
Environment
Application Name: Playground
Laravel Version: 9.33.0     
PHP Version: 8.1.6
Composer Version: 2.3.5     
Environment: local
Debug Mode: ENABLED
URL: playground.test/       
Maintenance Mode: OFF       

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 11
Antlers: regex
Version: 3.3.42 PRO

Statamic Addons
4rn0/statamic-v3-image-optimizer: 1.0.17
aerni/font-awesome: 1.2.0
aryehraber/statamic-captcha: 1.9.0
ddm-studio/cookie-byte: 1.0.16
doublethreedigital/duplicator: 2.3.2
jacksleight/statamic-bard-mutator: 1.1.2
pecotamic/sitemap: 1.4.0
rias/statamic-link-it: 2.2.3
rias/statamic-redirect: 2.4.0
statamic/seo-pro: 3.1.0
xndbogdan/statamic-bard-text-color: 2.4.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by duncanmcclean** [comment] 2023-12-13 11:41
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. The other fields in the fieldset are showing up as options in the dropdown. 

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-12-13 11:41 UTC
Labels: blueprints & fieldsets
