### ISSUE TITLE
Focal point not saved when blueprint has no fields

### ISSUE THREAD

**Issue by marcusand** [statamic/cms#2954] opened 2020-12-02 12:31 UTC
## Bug Description
When setting a focal point on an image which is connected to an empty blueprint, the focal point is not saved.

## How to Reproduce
- delete all fields in the blueprint of the asset container so that it has no fields
- set a focal point on one of the assets
- look in the meta data file --> only last_modified is updated 

## Environment
Statamic 3.0.31 Pro
Laravel 7.29.3
PHP 7.3.24
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment] 2020-12-08 22:40
Seems to be working fine for me. I removed all the fields from my asset container's blueprint so it was left looking like this:

```yaml
sections:
  main:
    display: Main
    fields: {  }
```

I then opened up one of my asset's meta yaml files in my code editor, and removed its contents. Then I went into the Asset library, set a focal point and saved my changes. I then confirmed that there was data set inside the asset's meta yaml file, including the focal point.

The focal point also changed fine for me when I updated it.

**Comment by jackmcdade** [comment] 2022-03-04 21:43
I can recreate it if i don't save any asset meta data before removing the `alt` tag on a container blueprint. This might be a helpful clue. 🕵️‍♀️

**Comment by joshuablum** [comment] 2022-06-09 13:26
Was able to just reproduce it on a fresh 3.3.14 via CLI.
I had to edit the blueprint from the CP and just hit save without doing anything else to the blueprint for the alt text and focal point to get saved.
If the `assets.yaml` is like @duncanmcclean's it also doesn't save the focal point.

**Comment by ncla** [comment] 2022-09-20 18:50
I looked into this and just wanted to let you know that I have found a fix for this and will open a PR at start of October for Hacktoberfest. Just in case anyone else planned to pick up this issue.

**Closed** 2022-10-03 18:47 UTC
Labels: assets
