### ISSUE TITLE
Multi-site: Custom navigation relationships don't receive site as query parameter

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/cms#7065] opened 2022-11-16 11:01 UTC
### Bug description

When using a custom blueprint for a navigation, any relationship entries don't receive the selected site as a query parameter, resulting in entries from all sites to be shown.

This is from a normal navigation where site is passed correctly:
![image](https://user-images.githubusercontent.com/1186125/202161884-a45af2f2-620e-478a-8b7c-69f93b64ddde.png)

This is from the customized blueprint where site isn't passed:
![image](https://user-images.githubusercontent.com/1186125/202162229-3afb85ad-f828-44a2-aa1f-25f64bed4a94.png)

### How to reproduce

The custom blueprint used can be found here: https://github.com/statamic/ideas/issues/690#issuecomment-1316736791

Sites configuration is pretty simple:
```php
'da' => [
    'name'   => 'Danish',
    'locale' => 'da_DK',
    'url'    => env('APP_URL'),
],

'en' => [
    'name'   => 'English',
    'locale' => 'en_US',
    'url'    => env('APP_URL') . '/en/',
],
```

### Environment

```yaml
Environment
Application Name: Comwell
Laravel Version: 9.40.1
PHP Version: 8.0.19
Composer Version: 2.1.5
Environment: local
Debug Mode: ENABLED
URL: comwell-v2.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Version: 3.3.55 PRO

Statamic Addons
jacksleight/statamic-bard-mutator: 1.1.2
statamic/eloquent-driver: 1.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

This makes it quite hard the use, when we'll end up with 100+ pages

**Comment by FrittenKeeZ** [comment] 2022-12-13 09:07
@jasonvarga I'm really sorry I have to tag you in this

**Comment by duncanmcclean** [comment] 2023-11-21 12:57
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. The `site` parameter is present and correct in the relationship request and is returning the correct set of entries.

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-21 12:57 UTC
Labels: multisite
