### ISSUE TITLE
[feature request] Bard: bring back linking to entries (f.e. pages)

### ISSUE THREAD

**Issue by manogi** [statamic/cms#1110] opened 2019-12-14 10:14 UTC
In V2, when linking text in Bard, you could start typing the title of some entry and it was automatically proposed in a drop down (see attachment), that would be nice in V3 too.

<img width="404" alt="CleanShot 2019-12-14 at 11 13 32@2x" src="https://user-images.githubusercontent.com/1419634/70847264-cb05ba80-1e62-11ea-879a-9a88c8b249ec.png">

**Comment by jasonvarga** [comment] 2019-12-16 19:12
Duplicate of #801

**Closed by jasonvarga** 2019-12-16 19:12 UTC
