### ISSUE TITLE
Asset editor does not scroll

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#4029] opened 2021-07-20 11:47 UTC
## Bug Description

When a tall portrait image overflows the browser window the Asset editor cannot be scrolled, making it impossible to reach the Save button bar.

## Extra Detail
<img width="1440" alt="Screen Shot 2021-07-20 at 9 39 20 pm" src="https://user-images.githubusercontent.com/414211/126318029-a19e3dd1-ac8e-44cb-952d-aa94d944988d.png">

## Environment

Statamic 3.1.27 Pro
Laravel 8.50.0
PHP 8.0.8
mikemartin/helpscout-beacon 1.0.1
rias/statamic-color-swatches 2.0.5
rias/statamic-redirect 1.4.6
spatie/statamic-responsive-images 2.7.1
withcandour/aardvark-seo 2.0.14

**Comment by duncanmcclean** [comment] 2021-07-20 12:01
Duplicate of #4023

**Closed by duncanmcclean** 2021-07-20 12:01 UTC
