### ISSUE TITLE
Link Existing no longer works when adding a fieldset in a fieldset

### ISSUE THREAD

**Issue by francoismajor** [statamic/cms#3937] opened 2021-06-30 20:26 UTC
## Bug Description
The **Link Existing** button in fieldsets and blueprints stops working if you include a fieldset within a fieldset. (see screenshots).

If you import a grid or replicator in a fieldset (workaround I was trying), then the **Link existing** button works, but this causes another error where you can not longer open the linked field and just loads infinitely.

This worked in v3.1.5 and no longer works in v3.1.26, so somewhere along the way 🤷

The Peak starter kit uses this same approach for buttons/button, and is broken there too (tested with fresh install).

## How to Reproduce
1. Install latest statamic.
2. Create a fieldset.
3. Link that fieldset within another fieldset. Link existing still works on this page.
4. Go to any other fieldset or blueprint, Link Existing no longer works.

## Extra Detail
Simple fieldset with text field.
![Screen Shot 2021-06-30 at 4 05 03 PM](https://user-images.githubusercontent.com/8515329/124024286-00c6b180-d9bd-11eb-8755-c7e0ba0c24d7.png)
Includin fieldset1 in fieldset2 causes **Link Existing** to stop working. (actually, the button will work on this page only but no other fieldset or blueprint page)
![Screen Shot 2021-06-30 at 4 05 10 PM](https://user-images.githubusercontent.com/8515329/124024295-02907500-d9bd-11eb-87e4-7db376d43758.png)

![Screen Shot 2021-06-30 at 3 59 59 PM](https://user-images.githubusercontent.com/8515329/124023709-3e770a80-d9bc-11eb-83c4-e14e32338118.png)
```
vue.common.prod.js:6 TypeError: Cannot read property 'display' of undefined
    at LinkFields.vue:116
    at Array.map (<anonymous>)
    at LinkFields.vue:114
    at Array.flatMap (<anonymous>)
    at a.data (LinkFields.vue:114)
    at vue.common.prod.js:6
    at vue.common.prod.js:6
    at vue.common.prod.js:6
    at a.e._init (vue.common.prod.js:6)
    at new a (vue.common.prod.js:6)
```

Error with replicator or grid included as a field (both are the same)

![Screen Shot 2021-06-30 at 4 15 57 PM](https://user-images.githubusercontent.com/8515329/124025484-7c752e00-d9be-11eb-9f81-db7e23079d85.png)
![Screen Shot 2021-06-30 at 4 16 03 PM](https://user-images.githubusercontent.com/8515329/124025490-7da65b00-d9be-11eb-8f8d-d93d599e64c6.png)
Trying to click on replicator here causes an error
![Screen Shot 2021-06-30 at 4 10 36 PM](https://user-images.githubusercontent.com/8515329/124025497-7f701e80-d9be-11eb-80f9-2edb74a4d19a.png)
![Screen Shot 2021-06-30 at 4 10 41 PM](https://user-images.githubusercontent.com/8515329/124025500-80a14b80-d9be-11eb-9fd0-2595397d7cb3.png)

## Environment

Statamic 3.1.26 Solo
Laravel 8.49.0
PHP 8.0.3
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2021-06-30 20:30
Duplicate of #3904. It's fixed for the next release tomorrow. Thank you for the in-depth issue, sorry it was a duplicate!

**Closed by jasonvarga** 2021-06-30 20:30 UTC

**Comment by francoismajor** [comment] 2021-06-30 20:34
> Duplicate of #3904. It's fixed for the next release tomorrow. Thank you for the in-depth issue, sorry it was a duplicate!

Great, I'm glad it's fixed!
I searched quite a bit but couldn't find a related issue (probably since it was closed).
Thanks
