### ISSUE TITLE
Unable to sort assets in control panel

### ISSUE THREAD

**Issue by isratrade** [statamic/cms#2898] opened 2020-11-23 10:36 UTC
## Bug Description
User wants to sort by date_created of asset in order to select the last assets uploaded

## How to Reproduce
Many assets uploaded a month ago. New image uploaded today. Co-worker can't sort to find new image. Search is only by name of image which isn't ready know when uploading files from image bank. 

## Environment

Statamic 3.0.30 Pro
Laravel 7.29.3
PHP 7.4.10
statamic/seo-pro 2.0.14
statamic/ssg 0.2.0

**Comment by johncarter-** [comment] 2020-11-23 10:49
I agree this is a bug.  It makes assets really difficult when you start to work with a lot of assets.

I would also argue that the assets should be sorted by most recently uploaded by default.

Related #2563

And related Ideas issue: https://github.com/statamic/ideas/issues/221

**Comment by jasonvarga** [comment] 2020-11-25 18:38
Not a bug, just not a feature that exists yet. Closing in favor of statamic/ideas#221

**Closed by jasonvarga** 2020-11-25 18:38 UTC
Labels: assets, ux
