### ISSUE TITLE
Passed value cannot be an array at vendor/statamic/stringy/src/Stringy.php:45

### ISSUE THREAD

**Issue by jurrid** [statamic/cms#5132] opened 2022-01-26 09:29 UTC
### Bug description

A InvalidArgumentException is thrown when i created a fresh project. Also in an other project that i'm working on i composer updated the project and it also occurred there.

### How to reproduce

- CLI `statamic new project` 
- create a blank project
- create a new user and then the error will occur

### Logs

```shell
InvalidArgumentException

  Passed value cannot be an array

  at vendor/statamic/stringy/src/Stringy.php:45
     41▕      */
     42▕     public function __construct($str = '', $encoding = null)
     43▕     {
     44▕         if (is_array($str)) {
  ➜  45▕             throw new InvalidArgumentException(
     46▕                 'Passed value cannot be an array'
     47▕             );
     48▕         } elseif (is_object($str) && !method_exists($str, '__toString')) {
     49▕             throw new InvalidArgumentException(

      +7 vendor frames
  8   [internal]:0
      Statamic\Stache\Indexes\Value::Statamic\Stache\Indexes\{closure}(Object(Statamic\Auth\File\User), "8b720a0f-da2e-4225-9225-fe8b804de9d9")

      +27 vendor frames
  36  please:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### Versions

php v8.1.0
Laravel v8.81.0
statamic/cms (v3.2.31)
statamic/stringy (3.1.2)

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2022-01-26 09:59
Duplicate of #5126, will be fixed in the next release.

**Closed by duncanmcclean** 2022-01-26 09:59 UTC
