### ISSUE TITLE
Error: collection does not have any visible blueprints. At least one must not be hidden.

### ISSUE THREAD

**Issue by hlorofos** [statamic/cms#7879] opened 2023-04-10 10:04 UTC
### Bug description

Admin user creates one blueprint and then set it as the "Hidden"
(Hides the blueprint from the create buttons in the CP)

Afterwards there will be no way to create an entity for the collection. There will be exception
`The *** collection does not have any visible blueprints. At least one must not be hidden.`

Additionally you cannot un-hide the collection from the Blueprints editor. Although the save button doesn't display any error, in the result `hide: true` will be still in the collection yaml file.

### How to reproduce

- go to Collections
- press Create collection
- Create Collection with any data
- press Configure Blueprints
- select the blueprint
- Edit Blueprint, set Hidden toggle, press Save
- Navigate to the collections menu and click on the collection you just created

### Environment

```yaml
Environment
Application Name: kapusta
Laravel Version: 9.52.4
PHP Version: 8.2.2
Composer Version: 2.5.2
Environment: local
Debug Mode: ENABLED
URL: kapusta.test/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.7 PRO
```

### Installation

Starter Kit using via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment] 2023-04-10 11:03
If you hide the only blueprint for a collection, this error is to be expected. You need at least one non-hidden blueprint per collection.

Untoggling 'Hidden' when editing a blueprint should work though - that bit is a bug.

**Comment by duncanmcclean** [comment] 2024-01-22 10:13
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. Every time I toggle "Hidden", the toggle state is saved correctly:

![CleanShot 2024-01-22 at 10 12 31](https://github.com/statamic/cms/assets/19637309/3d600896-43a5-4d45-89ba-c9d87b4bb8ee)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2024-01-22 10:13 UTC
Labels: blueprints & fieldsets
