### ISSUE TITLE
Unable to Specify a layout for taxonomy index & show pages

### ISSUE THREAD

**Issue by aadind** [statamic/cms#2571] opened 2020-10-01 10:20 UTC
## Bug Description
Trying to provide a specific layout for a taxonomy index and show pages. However. I have a few layout files in views/layouts folder. However, if i specify them in the taxonomy YAML, entire rendering breaks saying Layout is not found.  this got solved only when i added a laytout.antlers.html in the view folder.  The sole purpose of having more than one layouts is lost in this case. Can someone help? 
## How to Reproduce
1. Create a taxonomy {somename}
2. Create index.antlers.html & show.antlers.html in resources/views/{somename} folder 
3. Specify a layout in {somename} YAML file as a configuration. 

## Environment

**Statamic version:** 3.0.13

**PHP version:** 7.4

**Install method (choose one):**
Migrated from V2 using migrator

**Comment by jasonvarga** [comment] 2020-10-01 15:46
Duplicate of #2003

**Closed by jasonvarga** 2020-10-01 15:46 UTC
