### ISSUE TITLE
Issue with Single Tag and Tag Pair

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2159] opened 2020-07-30 14:49 UTC
## Bug Description
I've got an addon with a tag that can be used both as a single tag or a tag pair. I'm using the `$this->isPair` boolean to make this work. 

When I use the single tag before the tag pair, the tag pair won't work. Only the single tag works. When I switch it around and use the tag pair before the single tag, both tags work as expected.

## How to Reproduce
Create a tag with this method and try to use the single tag before the tag pair in your template.

```php
public function tag()
{
  if ($this->isPair) {
    return [
       'foo' => 'bar'
    ];
  }

  if (! $this->isPair) {    
    return 'bar';
  }
}
```

## Environment

**Statamic version:** 3.0.0.-beta-41

**PHP version:** 7.4.6

**Install method:** Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-07-30 15:29
That's unfortunately just how it works for the forseeable future.

This is because if you have the single tag first, it'll see the closing tag, even though you intend it to close the second one.

You can get around this by using them in different views (eg. use a partial), or by self-closing the single tag.

```
{{ your_tag /}}

{{ your_tag }}
{{ /your_tag }}
```

**Closed by jasonvarga** 2020-07-30 15:29 UTC

**Comment by aerni** [comment] 2020-07-30 15:30
Alright, thanks for clarifying. A hint in the docs would be nice though. 😉

**Comment by ncla** [comment] 2021-05-11 14:47
This should be either documented better or fixed so that the single tags are more self-aware. In bigger layout Antler files with multiple single tags, it takes only one tag pair to screw up and cause unexpected behavior.

**Comment by edalzell** [comment] 2021-05-14 17:30
You can also solve by not using the same spacing, i.e. `{{foo}}` on the single and `{{ foo }} ... {{ /foo }}` on the tag pair (or vice versa).
