### ISSUE TITLE
Bard List Items add nested content with paragraphs

### ISSUE THREAD

**Issue by sheldonkotyk** [statamic/cms#1522] opened 2020-03-20 11:44 UTC
```
content:
      -
        type: list_item
        content:
          -
            type: paragraph
            content:
              -
                type: text
                text: 'To foster and stimulate improvements in all aspects of healthcare of infants, children, and adolescents;'
```

Because of the extra paragraph info it is harder to style properly.

**Comment by jasonvarga** [comment] 2020-03-20 12:02
Duplicate of #1058

**Closed by jasonvarga** 2020-03-20 12:02 UTC
