### ISSUE TITLE
V3.3.10 : The fetch revisions url is broken

### ISSUE THREAD

**Issue by thisJerem** [statamic/cms#5973] opened 2022-05-02 16:49 UTC
### Bug description

Since 3.3.10, at each time I want to get the history revisions items of an entry, I get an error from History.vue at the line 72 "Uncaught (in promise) TypeError: e.data.reverse is not a function"

I put a breakpoint at the issue, and it seems that the indexUrl defined in the props of component is now undefined.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/1255528/166289339-115ad644-dedd-43e3-8e43-ade63b9d2b6a.png">

Going back to 3.3.9 fix the issue.

### How to reproduce

Enable revisions on last version, any collection with revisions on are broken.

### Versions

3.3.10

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by edalzell** [comment] 2022-05-03 03:56
Interestingly, I can't reproduce this on the latest dev version, but can on 3.3.10.

**Comment by staudenmeir** [comment] 2022-05-07 09:19
https://github.com/statamic/cms/pull/5968 fixed this and will be in the next release.

**Closed** 2022-05-07 10:53 UTC
Labels: revisions
