### ISSUE TITLE
Fieldtype UI descriptions shows translation key instead of default

### ISSUE THREAD

**Issue by Christophvh** [statamic/cms#5277] opened 2022-02-14 16:13 UTC
### Bug description

Field types description shows translations keys instead of the default English translation.
![Screenshot 2022-02-14 at 17 08 03](https://user-images.githubusercontent.com/9588070/153901919-e7623d45-75ea-434b-8a5f-a658a0a89001.png)

### How to reproduce

Set statamic language to Dutch.

### Versions

Statamic 3.2.32 Pro
Laravel 8.83.0
PHP 8.1.2
aerni/livewire-forms 2.0.0
edalzell/blade-directives 3.5.2
jonassiewertsen/statamic-livewire 2.7.1

### Installation

Existing Laravel app

**Comment by duncanmcclean** [comment] 2022-02-14 22:39
Confirmed.

It looks like the Dutch translations are out-of-date. Those keys exist in the [English translation file](https://github.com/statamic/cms/blob/3.2/resources/lang/en/fieldtypes.php#L89) but aren't present in the [Dutch translation file](https://github.com/statamic/cms/blob/3.2/resources/lang/nl/fieldtypes.php).

**Comment by ebeauchamps** [comment] 2022-02-15 20:54
@robdekort

**Comment by robdekort** [comment] 2022-02-15 20:56
Ah yeah. It's been a month or two since I last updated strings I think. I was planning on doing another translation run when 3.3 hits. But if anyone wants to beat me to it. Feel free! https://statamic.dev/cp-translations#contributing-a-new-translation

Not a bug so closing for now.

**Comment by robdekort** [comment] 2022-02-15 22:00
However a fallback to English would be nice whenever strings aren’t localized yet. Does that qualify as a bug/fr @jackmcdade?

**Comment by jasonvarga** [comment] 2022-02-16 15:01
Yes it should fall back. Bug.

**Comment by aerni** [comment] 2022-06-15 12:49
This is likely a duplicate of #5610.

**Closed** 2023-11-07 17:48 UTC
Labels: i18n
