### ISSUE TITLE
Call to undefined metod User::id() when adding a new item (Page or Blueprint or whatever)

### ISSUE THREAD

**Issue by maxi032** [statamic/cms#6695] opened 2022-09-12 10:47 UTC
### Bug description

Hello,

I wonder if someone could help me.

I moved users to mysql and since then, I get the error `Call to undefined method App\Models\User::id()` whenever I try to add something. 

I am using v3.3.35
I am testing locally on a domain .local
I have pro mode enabled and multisite configured.

Thank you.

### How to reproduce

Try to add a page, a Blueprint or a Global

### Environment

```yaml
Statamic 3.3.35 Pro
Laravel 8.83.23
PHP 7.4.30
webographen/statamic-admin-log 1.0.6
withcandour/aardvark-seo 2.0.28
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by ryanmitchell** [comment] 2022-09-12 12:40
You need to add that function to your App\Models\User file

```
public function id()
{
    return $this->id;
}
```

**Comment by duncanmcclean** [comment] 2023-11-16 18:17
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. [Insert text]

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-16 18:17 UTC
Labels: database
