### ISSUE TITLE
Asset row disappear after setting the image ALT value

### ISSUE THREAD

**Issue by FR6** [statamic/cms#7136] opened 2022-11-29 03:58 UTC
### Bug description

The asset disappears after setting an ALT text:

https://user-images.githubusercontent.com/286685/204434548-687fe172-4c80-4a1d-ab12-c2b83de355b9.mp4

### How to reproduce

- Install Statamic 3.3.58
- Configure an asset container
- Add an Asset field in "pages" collection
- Create an Entry
- Upload an image
- Set ALT text

The asset row will not be there anymore. Preventing saving the data.

It works on the demo site (that currently use 3.3.54): https://demo.statamic.com/cp/collections/pages/entries/home
It works too on a really old installation (3.3.9), but after updating that instance to 3.3.58), it doesn't work anymore.

### Environment

```yaml
Statamic 3.3.58 Pro
Laravel 8.83.16
PHP 8.1.4
aryehraber/statamic-font-awesome 2.2.0
doublethreedigital/duplicator 2.3.1
joetannenbaum/antlers-stack-tags 0.1.0
jonassiewertsen/statamic-livewire 2.9.0
```

### Installation

Existing Laravel app

**Comment by arthurperton** [comment] 2022-11-29 06:59
Thank you @FR6. This looks like a duplicate of #7109 and #7129, which are fixed by PR #7131. So I am closing this issue as duplicate / completed. 

Feel free to reopen if your issue is different / not solved by the PR mentioned above.

**Closed by arthurperton** 2022-11-29 06:59 UTC
