### ISSUE TITLE
Breadcrum and taxonomy

### ISSUE THREAD

**Issue by freshface** [statamic/cms#2711] opened 2020-10-21 20:24 UTC
## How to Reproduce

Use the breadcrumb in your antlers and filter a collection by taxonomy

## Extra Detail

```
<nav class="breadcrumb">
    <ul>
        {{ nav:breadcrumbs }}
        <li{{ if is_current }} class="selected"{{ /if }}>
            <a href="{{ url }}">{{ title }}</a>
        </li>
        {{ /nav:breadcrumbs }}
    </ul>
</nav>
```

```
Facade\Ignition\Exceptions\ViewException
Call to undefined method Statamic\Taxonomies\Taxonomy::setSupplement() 
```

## Environment

**Statamic version:** 3.0.20

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-10-21 20:38
Duplicate of #1776

**Closed by jasonvarga** 2020-10-21 20:38 UTC
