### ISSUE TITLE
Entries field type (Select Dropdown) not localized - entries from different locale shown

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#2010] opened 2020-06-30 21:26 UTC
## Bug Description
An entry with the mode set to select dropdown is not localized. All entries, including the ones form a different locale are shown. I expect only the ones from the current locale to show up.

## How to Reproduce
1) Create a multisite with two or more locales
2) Create a blueprint with an Entries fieldtype and set the mode to select dropdown
3) See the bug after creating a few entries with each locale

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Used V3 install

**Comment by jasonvarga** [comment] 2020-06-30 21:30
Duplicate of #1835

**Closed by jasonvarga** 2020-06-30 21:30 UTC
