### ISSUE TITLE
Not able to output Avatar of User

### ISSUE THREAD

**Issue by schmidtflo** [statamic/cms#1459] opened 2020-03-02 22:42 UTC
I'm not able to output the avatar of a user within an article, which sets the user as author. Using another Asset-Field with the same settings, except not being called `avatar`, everything works as expected.

To reproduce:

- Create an avatar field and eg. a profilepic field in the user's blueprint, and provide a picture in both fields for your actual user
- Create a Article collection, in the blueprint allow setting (multiple) users as authors, and set your current user as author
- Add the following code in the article template:

```
// not working
{{ author }}
  <img src="{{ glide:avatar width="48" height="48" }}" />
{{ /author }}

// working
{{ author }}
  <img src="{{ glide:profilepic width="48" height="48" }}" />
{{ /author }}
```

**Comment by jackmcdade** [comment] 2020-03-02 22:44
Thanks for the report! It's actually a duplicate of #1434 though :)

**Closed by jackmcdade** 2020-03-02 22:44 UTC

**Comment by vguerrerobosch** [comment] 2020-05-20 13:19
As a workaround I switched to blade partial like

```blade.php
<img src="{{ $author->value()->avatar() }}" alt="{{ $author->value()->get('name') }}">
```
Quite simple but does the job for now.
