### ISSUE TITLE
Non-localizable fields in Multi-site become localizable/ get stuck

### ISSUE THREAD

**Issue by lorenzhirsch** [statamic/cms#6452] opened 2022-08-05 14:02 UTC
### Bug description

After creating a multi-site, I added a taxonomy with a non-localizable asset (icon that stays the same for every language).
Then I went ahead and added content fpr the localized version of the terms first. After that I added content for the origin site. At this point you can always change the origin asset, but that won't propagate to the other sites, which can effectively have different assets.

The only way to fix the inconsistent terms is by editing the blueprint, make the asset localizable and edit the terms to have the same asset on every site.

**Similar problems with slugs that shouldn't be translated at all, yet have different versions on sites**

### How to reproduce

Create multi-site, create taxonomy, add non-localizable asset in the blueprint.
Create new term, before adding any content,  switch to other site (language) and add asset 'B'. 
Switch back to the origin site, change asset to asset 'A' . You now effectively have different assets per site, even though the field is configured as non-localizable.
When you now fill content for the origin site, the asset on the other sites become stuck ('Read-only').

### Environment

```yaml
Statamic 3.3.25 Pro
Laravel 9.17.0
PHP 8.1.8
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by duncanmcclean** [comment] 2023-11-29 12:45
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I'm only able to select any assets on the "origin" version of the entry. When I switch site, the assets field is read-only as expected.

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-29 12:45 UTC
Labels: multisite
