### ISSUE TITLE
Nesting a custom tag breaks things

### ISSUE THREAD

**Issue by MadeByMike** [statamic/cms#3993] opened 2021-07-14 09:24 UTC
## Bug Description

Custom tags with pairs don't work when nested.

## How to Reproduce

1. Create a custom tag
2. Return some data

```php
<?php

namespace App\Tags;

use Statamic\Tags\Tags;

class Anything extends Tags
{
    /**
     * The {{ anything }} tag.
     *
     * @return string|array
     */
    public function index()
    {
      return  ["test"=>'a']; // literally return anything
    }

}
```

3. Nest that tag
```
 {{assign}}
  {{assign}}
    {{test}}
  {{/assign}}
{{/assign}}
```
4. Watch it break

![image](https://user-images.githubusercontent.com/1320567/125598133-b9c91ab3-43bf-4cb6-ae16-3ea4a6955a26.png)

## Environment

Statamic 3.1.27 Pro
Laravel 8.49.0
PHP 7.4.16
statamic/seo-pro 2.2.1

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2021-07-14 13:01
Duplicate of #3099

**Closed by jasonvarga** 2021-07-14 13:01 UTC

**Comment by MadeByMike** [comment] 2021-07-14 22:14
That seems to be about collections and has to do with specific syntax used @jasonvarga are you sure it's the same root cause?

**Comment by MadeByMike** [comment] 2021-07-14 22:14
That seems to be about collections and has to do with specific syntax used @jasonvarga are you sure it's the same root cause?

**Comment by jasonvarga** [comment] 2021-07-14 22:23
Yeah, pretty sure. See in their "variant 2" example, the same closing tag is used for the outer and inner tags.
