### ISSUE TITLE
Error when linking single grid field in blueprint

### ISSUE THREAD

**Issue by marcusand** [statamic/cms#2942] opened 2020-11-30 10:41 UTC
## Bug Description
When linking a grid field trough the "Link a single field" menu the edit pages opens but stays in Loading screen forever. 

## How to Reproduce
- create a fieldset with a grid field
- try to link that grid field in a blueprint

## Extra Detail
<img width="1405" alt="Bildschirmfoto 2020-11-30 um 11 39 14" src="https://user-images.githubusercontent.com/28539818/100599726-ae2af700-3300-11eb-9a3c-9688eb00fdd5.png">

laravel error log:
````
[2020-11-30 10:34:20] local.ERROR: Undefined index: field {"userId":"f34a82ae-5501-4519-9e18-418131f2be95","exception":"[object] (ErrorException(code: 0): Undefined index: field at /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Fields/FieldTransformer.php:61)
[stacktrace]
#0 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Fields/FieldTransformer.php(61): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Volumes/Daten/...', 61, Array)
#1 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Fieldtypes/NestedFields.php(23): Statamic\\Fields\\FieldTransformer::toVue(Array)
#2 [internal function]: Statamic\\Fieldtypes\\NestedFields->Statamic\\Fieldtypes\\{closure}(Array, 0)
#3 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#4 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Fieldtypes/NestedFields.php(24): Illuminate\\Support\\Collection->map(Object(Closure))
#5 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Fields/Field.php(225): Statamic\\Fieldtypes\\NestedFields->preProcess(Array)
#6 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Statamic\\Fields\\Field->preProcess()
#7 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Statamic\\Fields\\Field), 'fields')
#8 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#9 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map(Object(Closure))
#10 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Fields/Fields.php(134): Illuminate\\Support\\HigherOrderCollectionProxy->__call('preProcess', Array)
#11 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Controllers/CP/Fields/FieldsController.php(35): Statamic\\Fields\\Fields->preProcess()
#12 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Statamic\\Http\\Controllers\\CP\\Fields\\FieldsController->edit(Object(Illuminate\\Http\\Request))
#13 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('edit', Array)
#14 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Statamic\\Http\\Controllers\\CP\\Fields\\FieldsController), 'edit')
#15 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#16 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#17 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'configure field...')
#20 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CP/ControlPanel.php(16): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ControlPanel->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#38 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#48 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#49 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#50 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#51 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Volumes/Daten/meso/statamic-v3/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Volumes/Daten/meso/statamic-v3/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Volumes/Daten/meso/statamic-v3/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Volumes/Daten/meso/statamic-v3/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#72 /Volumes/Daten/meso/statamic-v3/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#73 /Volumes/Daten/meso/statamic-v3/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#74 /Users/marcusschreiter/.composer/vendor/laravel/valet/server.php(191): require('/Volumes/Daten/...')
#75 {main}
"}
````
## Environment

Statamic 3.0.30 Pro
Laravel 7.29.3
PHP 7.3.24
statamic/migrator dev-master

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment] 2020-11-30 10:59
May be related to #2924

**Comment by damcclean** [comment] 2020-11-30 18:50
Just attempted to reproduce this error but I didn't seem to see it again, [see screencast](https://www.loom.com/share/742aeb5f84a04ae18713d40230224e77). 

The console error you can see is #2924. However, there are some reports on that issue that when linking fields, it also continues loading for them.... could you try linking another fieldtype to see if the same issue happens? It may be a duplicate.

**Comment by marcusand** [comment] 2020-12-02 11:44
I tried some other fieldtypes - they worked all fine. seems like it only happens for grid. 
but very weird that is works for you  😮 on what statamic/php version are you?
can some else reproduce?

**Comment by damcclean** [comment] 2020-12-02 11:48
I was on the latest (v3.0.31).

**Comment by marcusand** [comment] 2020-12-02 12:08
I noticed one thing. It works when the grid has no fields. Can you try again with a text field in the grid?

**Comment by damcclean** [comment] 2020-12-02 12:56
> I noticed one thing. It works when the grid has no fields. Can you try again with a text field in the grid?

Ah... well noticed. I'll try again in a couple of hours after work 👍

**Comment by damcclean** [comment] 2020-12-02 18:12
Yup, just reproduced. The issue occurs when you have a field inside the Grid field you are importing.

**Comment by damcclean** [comment] 2020-12-02 18:13
In fact, I think this issue is a duplicate of #2924 so I'm closing this issue in favour of that one. Thanks for pointing that out though!

**Closed by damcclean** 2020-12-02 18:13 UTC
Labels: bug

**Comment by marcusand** [comment] 2020-12-02 18:54
@damcclean all right thanks - although I think the vue error described in #2924 is not really connected to that issue, but yeah the described behaviour seems the same.

**Comment by damcclean** [comment] 2020-12-02 19:20
> @damcclean all right thanks - although I think the vue error described in #2924 is not really connected to that issue, but yeah the described behaviour seems the same.

Yeah. I think it's maybe to do with the field in that issue being a replicator and not a grid. However, I've not tested that theory. I'm guessing however that it could be fixed in one place for both of the issues.
