### ISSUE TITLE
Error after deleting user groups

### ISSUE THREAD

**Issue by HazemMohamed252** [statamic/cms#6740] opened 2022-09-18 12:58 UTC
### Bug description

Creating new group and assign some users to it then deleting that group make an issue

### How to reproduce

1 - Login to the system as a super user

2 - Create a user group called “ New group “

3 - Add users to that group

4 - Delete the group

5 - Try to open one of the users that were assigned to that group

“ Call to a member function handle() on null ” error when trying to access one of the users accounts

Same error when trying to login with one of the users from the deleted group

### Environment

```yaml
Statamic 3.2.39 Pro
Laravel 8.83.6
PHP 7.4.11
doublethreedigital/runway 2.3.0
jacksleight/statamic-lazy-logo 0.3.3
vannut/statamic-weather-addon 1.0.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by joshuablum** [comment] 2022-09-19 13:59
Closing this since it's a duplicate of #6192.

Please don't create multiple issues of the same bug, thanks (but also thanks for reporting it in the first place 🙏).

**Closed by joshuablum** 2022-09-19 13:59 UTC
