### ISSUE TITLE
When adding lists to Bard paragraph tags are added within list items

### ISSUE THREAD

**Issue by jaredchesebro** [statamic/cms#1883] opened 2020-05-31 21:35 UTC
## Bug Description
When adding lists to Bard, paragraph tags are added within list items.

## How to Reproduce
Add list to Bard field.

## Extra Detail
![Screen Shot 2020-05-31 at 2 32 06 PM](https://user-images.githubusercontent.com/21958491/83363091-8a83f580-a34b-11ea-851b-cb24299ea05a.png)

## Environment
**Statamic version:** 3.0.0.-beta-28
**PHP version:** 7.4.2
**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jonassiewertsen** [comment] 2020-06-01 07:27
I can confirm this.

**Comment by jasonvarga** [comment] 2020-06-01 12:59
Duplicate of #1805

**Closed by jasonvarga** 2020-06-01 12:59 UTC
