### ISSUE TITLE
Requesting a password reset causes an error

### ISSUE THREAD

**Issue by syntheticminds** [statamic/cms#1332] opened 2020-02-11 11:54 UTC
To reproduce:

1. Go to the control panel login.
2. Click 'Forgot password?'
3. Enter an email address (I used the email address of a super user I had just created).
4. See error `Call to a member function table() on null` in `vendor/laravel/framework/src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php:234`

**Comment by jasonvarga** [comment] 2020-02-11 13:25
Duplicate of #1328

**Closed by jasonvarga** 2020-02-11 13:25 UTC
