### ISSUE TITLE
Entries Fieldtype "Link Existing Item" not loading

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#2123] opened 2020-07-22 17:21 UTC
## Bug Description
Entries fieldtype set up in a blueprint is not returning list of entries when "Link Existing Item" is selected. It does bring up the form to add a new entry.

## How to Reproduce
Initially added an entries field to a fieldset that was being referenced from a Bard field in a blueprint. Tested further with Bard field in blueprint only (not linked to fieldset), then by placing entries field just within the blueprint (no Bard). When I click to link to existing entries, the loading animation comes up, along with the blue progress bar at the top of the screen. Once progress bar completes, "loading" is still displayed.

## Environment

**Statamic version:** 3.0.0.-beta-38

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic` and migrated v2 site (blueprint/fieldset is new/not migrated and I've started with an empty page)

**Comment by theblacksheepltd** [comment] 2020-07-22 17:36
Further testing: Just did a fresh install of beta 38, created a collection and added a record, then added an entries field to the pages blueprint. Getting same results from the entries field, so it doesn't seem to be tied to existing site data.

**Comment by theblacksheepltd** [comment] 2020-07-22 17:46
Sorry, should have clarified — this seems to only be an issue with "Stack Selector" mode.

**Comment by jasonvarga** [comment] 2020-07-22 17:46
Duplicate of #2121

**Comment by jasonvarga** [comment] 2020-07-22 17:47
Fixed for next release.

**Closed by jasonvarga** 2020-07-22 17:46 UTC
