### ISSUE TITLE
Select fieldtypes settings can not move options

### ISSUE THREAD

**Issue by lightbringer93** [statamic/cms#1229] opened 2020-01-18 16:37 UTC
In the select fieldtypes settings I can not move the options to reorder them.
![Screenshot (1)](https://user-images.githubusercontent.com/27002677/72667174-1cccd200-3a19-11ea-81f0-ad9b9c1ba50e.png)

**Comment by jackmcdade** [comment] 2020-01-18 16:45
Duplicate of #1182 :)

**Closed by jackmcdade** 2020-01-18 16:45 UTC
