### ISSUE TITLE
Asset get's overwritten when same name but different letter cases

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#6667] opened 2022-09-08 10:28 UTC
### Bug description

We use a form to let clients upload documents like PDFs. We found that some assets got replaced when they appear to have the 'same' file name.

### How to reproduce

An issue appeared after following situation:
- Someone uploaded a `foo.pdf`
- Someone later uploaded a `Foo.pdf`

Instead of automatically appending some numbers like `foo-1123581321.pdf` to make the file name unique, the newer file replaced the older file.

So I think the issue is the unique check and the issue with case-sensitivity, depending on the OS.

### Environment

```yaml
Statamic 3.3.20 Pro
Laravel 8.83.19
PHP 7.4.30
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

### Additional details

It seems that something was done to prevent this, but it didn't work: https://github.com/statamic/cms/pull/6031

**Comment by duncanmcclean** [comment] 2024-01-09 16:34
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. The existing asset doesn't get overwritten, instead a unique filename is used (like `duncan-1704818064.jpg`).

![CleanShot 2024-01-09 at 16 34 14](https://github.com/statamic/cms/assets/19637309/0ed7ee6a-b8cb-4e15-8aef-681721c61639)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed as completed by duncanmcclean** 2024-01-09 16:34 UTC
Labels: assets
