### ISSUE TITLE
Laravel 8 Notification don't have themes

### ISSUE THREAD

**Issue by GioChocolateBro** [statamic/cms#2760] opened 2020-10-28 18:36 UTC
## Bug Description
Laravel notification themes don't work anymore after upgrading to laravel 8.

## How to Reproduce
I did a fresh install following the steps of the starter creek template.
Also did it with the statamic CLI.

Afterwards i edit the composer file with the steps from the Laravel upgrade guide. Everything works fine.
My mail gets send by mailgun. But it just doesn't apply the default.css theme anymore. I get a blank email

## Extra Detail
![Screenshot 2020-10-28 at 18 19 59](https://user-images.githubusercontent.com/6509276/97481240-cfd93d00-1954-11eb-892d-9753e827b6b3.png)

## Environment

**Statamic version:** 3.0.20

**PHP version:** 7.3.20

**Comment by jasonvarga** [comment] 2020-10-28 18:55
Duplicate of #2747

**Closed by jasonvarga** 2020-10-28 18:55 UTC
