### ISSUE TITLE
[4.x] Creating a GlobalSet Blueprint throws `Undefined array key "fields"`

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7970] opened 2023-04-20 14:34 UTC
### Bug description

When a Global Set initially does not have any Blueprint configured, it throws an error when opening the Blueprint Editor.

![2023-04-20 16 30 30](https://user-images.githubusercontent.com/1102712/233398336-8616cd46-3597-47cc-a9c9-70766071048e.gif)

### How to reproduce

1. Go to "Globals"
2. Click "Create Global Set"
3. Add a Title + Handle, Click "Create Global Set"
4. Click "Cancel"
5. Use the three-dot menu to "Edit Blueprint" or click "Configure" > "Edit" Blueprint.

### Logs

```shell
local.ERROR: Undefined array key "fields" {"userId":"ae7473ff-9e86-415e-9a99-e334ce92bba1","exception":"[object] (ErrorException(code: 0): Undefined array key \"fields\" at /Users/**/cms/src/Http/Controllers/CP/Fields/ManagesBlueprints.php:114)
[stacktrace]
#0 /Users/**/statamic-v4/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/Users/**...', 114)
#1 /Users/**/cms/src/Http/Controllers/CP/Fields/ManagesBlueprints.php(114): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/Users/**...', 114)
#2 /Users/**/cms/src/Http/Controllers/CP/Fields/ManagesBlueprints.php(103): Statamic\\Http\\Controllers\\CP\\Globals\\GlobalsBlueprintController->sectionToVue(Object(Statamic\\Fields\\Section), 0, Object(Statamic\\Fields\\Tab))
#3 [internal function]: Statamic\\Http\\Controllers\\CP\\Globals\\GlobalsBlueprintController->Statamic\\Http\\Controllers\\CP\\Fields\\{closure}(Object(Statamic\\Fields\\Section), 0)
#4 /Users/**/statamic-v4/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#5 /Users/**/statamic-v4/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(768): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#6 /Users/**/cms/src/Http/Controllers/CP/Fields/ManagesBlueprints.php(102): Illuminate\\Support\\Collection->map(Object(Closure))
#7 /Users/**/cms/src/Http/Controllers/CP/Fields/ManagesBlueprints.php(92): Statamic\\Http\\Controllers\\CP\\Globals\\GlobalsBlueprintController->tabToVue(Object(Statamic\\Fields\\Tab))
#8 [internal function]: Statamic\\Http\\Controllers\\CP\\Globals\\GlobalsBlueprintController->Statamic\\Http\\Controllers\\CP\\Fields\\{closure}(Object(Statamic\\Fields\\Tab), 'main')
...
```

### Environment

```yaml
Statamic
Addons: 0
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.0.0-alpha.4 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment] 2023-04-24 19:43
I can't reproduce this. Seems fine? Do you have any leftover blueprints sitting in `resources/blueprints/globals`?

Closing this for now but we can reopen if you can reproduce it.

**Closed by jasonvarga** 2023-04-24 19:43 UTC
Labels: 4.0

**Comment by o1y** [comment] 2023-04-25 13:21
Thanks! It seems there’s another way to trigger this issue: #7993
