### ISSUE TITLE
save option 'lisiting' prevents linking of new entries in relationship fieldtype

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/cms#2860] opened 2020-11-18 13:45 UTC
## Bug Description
If a user wants to create a new entry about a relationship fieldtype and the save option 'listing' is used, the entry will not be linked after the automatic close. This is problematic because 'listing' is the default value.

## How to Reproduce
1. create entry with a relationship fieldtype (collection should have revision disabled)
2. entry is created and saved
3. stack closes and user is linked back
4. there is no link in the relationship fieldtype

## Extra Detail

https://www.dropbox.com/s/pi1uxuyofpvt87c/Bildschirmvideo%20aufnehmen%202020-11-18%20um%2014.33.37.mov?dl=0

## Environment

**Statamic version:** 3.0.26

**PHP version:** 7.3.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jasonvarga** [comment] 2020-11-18 14:18
Duplicate of #2469 
May be fixed by #2827

**Closed by jasonvarga** 2020-11-18 14:18 UTC
