### ISSUE TITLE
Taxonomy tag "published" filter not working

### ISSUE THREAD

**Issue by mehdismekouar** [statamic/cms#10715] opened 2024-08-28 11:34 UTC
### Bug description

```antlers
{{ taxonomy:tags collection="articles" min_count="1" published:is="true" }}
```
This code provides tags containing also unpublished entries within the list and does not filter only the tags with published="true" entries

I even created a scope but it also doesn't work
```antlers
{{ taxonomy:tags collection="articles" min_count="1" query_scope="published" }}
```

Here is the scope code
```php
namespace App\Scopes;

use Statamic\Query\Scopes\Scope;

class Published extends Scope
{
    /**
     * Apply the scope.
     *
     * @param \Statamic\Query\Builder $query
     * @param array $values
     * @return void
     */
    public function apply($query, $values)
    {
        $query->where('published', true);
    }
}
```

### How to reproduce

- create a taxonomy "tags" for example and create some entries
- create a collection "articles" for example and create some entries and make them all unpublished
- assign tags taxonomy to articles collection and add some tags to all articles and save
- in the default antlers page include this code
```antlers
{{ taxonomy:tags collection="articles" min_count="1" published:is="true" }}
<a href="{{ url }}">{{ title }} ( {{ entries_count }} )</a>
{{ /taxonomy:tags }}
```
- you should be able to list the tags with their articles count even if all the articles are unpublished

### Environment

```yaml
Environment
Application Name: Mehdi Mekouar
Laravel Version: 11.21.0
PHP Version: 8.2.12
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 0
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.23.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2024-08-28 11:42
Duplicate of #3539.

**Closed by duncanmcclean** 2024-08-28 11:42 UTC
Labels: taxonomies

**Comment by mehdismekouar** [comment] 2024-08-28 11:56
```antlers
{{ taxonomy:tags collection="articles" min_count="1" status:is="published" }}
```
The above code throws an error
```
Call to undefined method Statamic\Stache\Query\TermQueryBuilder::whereStatus()
```

**Comment by mehdismekouar** [comment] 2024-08-28 14:20
Thanks for the clarification

But i tried *{{ {taxonomy:tags collection="articles" min_count="1"
title:contains="test"} | count }}* and it does affect the count, i tried
other filters and the count gets affected too, only the *"published"*
filter doesn't

Any help on that?

**Comment by mehdismekouar** [comment] 2024-08-28 14:39
Oops! i think it's my bad

The title in *title:contains="test"* refers to the tag title and not to the
articles entries title
I get it now, sorry for that

Now my real question should be, how can can i query the *taxonomy:tags* of
*collection="articles"* where the articles entries are published only?

Any guidance on that? Thanks for your patience
