### ISSUE TITLE
Handle changes to slugified version of `display` when linking

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/cms#5313] opened 2022-02-19 14:03 UTC
### Bug description

When linking a field in fieldset/blueprint in the CP, the handle for the field being created automatically changes to a slugified version of the Display property.

It should stay as the handle of the linked field.

### How to reproduce

Have field:

```
handle: foo
field:
  display: 'Bar'
  type: text
```

Link that field in another fieldset.

Handle loads in as `bar`

### Versions

Statamic 3.2.32

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment] 2023-11-20 20:02
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. Whenever I import a field into a blueprint or fieldset, the handle of the imported field is `foo`, as expected.

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-20 20:02 UTC
Labels: blueprints & fieldsets
