### ISSUE TITLE
Control Panel: Can't reach all tab sections on an entry 

### ISSUE THREAD

**Issue by adamseidtahir** [statamic/cms#1876] opened 2020-05-29 10:40 UTC
## Bug Description
I'm making templates for a client to easier fill in the correct information instead of using a replicator with blocks. So I have made a blueprint with 9 sections, one for each "block". So there's a "hero" section a "faq" section etc... 

Basically what happens is then that when you create an entry with that template blueprint and you try to navigate between the sections using the tabs you can't reach all of them. The list of sections doesn't wrap into two lines basically and isn't scrollable either... So I can't reach my final section "faq" for example.

## How to Reproduce

Create a blueprint with at least 9-10 tab sections. Then create an entry with that blueprint and try to reach all of your tab sections.

## Extra Detail
This is how it looks now:

![Skärmavbild 2020-05-29 kl  12 00 25](https://user-images.githubusercontent.com/37052381/83250790-f67a2880-a1a8-11ea-8530-bcb0b1901853.png)

This is a suggestion of how it could look maybe:

![Skärmavbild 2020-05-29 kl  12 03 39](https://user-images.githubusercontent.com/37052381/83250868-0bef5280-a1a9-11ea-8175-e94769db848c.png)

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment] 2020-05-29 14:53
Duplicate of #1050. We'll get there, it's just a pretty edge case situation overall and it hasn't bubbled to the top yet :)

**Closed by jackmcdade** 2020-05-29 14:53 UTC
