### ISSUE TITLE
Asset alt text is lost when moving folders

### ISSUE THREAD

**Issue by SteveEdson** [statamic/cms#4274] opened 2021-09-16 16:08 UTC
## Bug Description
When an image with alt text is moved to a different folder, the alt text is lost.

## How to Reproduce
- Upload an image (either in asset manager, or through a field). 
- Add and save alt text. 
- Move the asset to a folder. 
- Alt text is gone

## Extra Detail
N/A

## Environment

```
Statamic 3.2.4 Pro
Laravel 8.61.0
PHP 8.0.10
No addons installed
```

**Comment by jasonvarga** [comment] 2021-09-16 16:09
Duplicate of #3896

**Closed by jasonvarga** 2021-09-16 16:09 UTC
