### ISSUE TITLE
Cannot set dynamic reply_to on forms using control panel

### ISSUE THREAD

**Issue by syntheticminds** [statamic/cms#1784] opened 2020-05-05 11:17 UTC
## Bug Description
The documentation correctly says you can set a dynamic reply_to address in the form's YAML file. However, this cannot be done in the control panel. Additionally, once you've set it in the YAML file, you can no longer save the form in the control panel because `{{ email }}` is an invalid email address.

## How to Reproduce
1. Create a form with an email field with the machine name _email_.
2. Try and set reply to address to `{{ email }}`. Note validation error.
3. Set `reply_to: "{{ email }}"` in the YAML file. Not how the form cannot be saved in the control panel any more.

## Extra Detail
This probably affects other fields you wish to be dynamic.

## Environment

**Statamic version:** v3.0.0-beta.27

**PHP version:** PHP 7.3

**Install method:**
Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment] 2020-05-26 22:02
Duplicate of #1651.

**Closed by jackmcdade** 2020-05-26 22:02 UTC
