### ISSUE TITLE
Asset preview on Taxonomies list 

### ISSUE THREAD

**Issue by emran-alhaddad** [statamic/cms#9463] opened 2024-02-06 08:45 UTC
### Bug description

The image preview should shown instead of the json value 

see the attached image for full underestanding 

<img width="1680" alt="image" src="https://github.com/statamic/cms/assets/65433346/0c09c55f-ba53-4c69-a54c-95256afad28f">

### How to reproduce

make taxonomy and add asset field to it then add new taxonomy

### Environment

```yaml
latest statmic version
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment] 2024-02-08 17:26
This seems to be working fine for me.

![CleanShot 2024-02-08 at 17 26 53](https://github.com/statamic/cms/assets/19637309/12f59751-1854-467d-bae7-80dcaff6c16d)

Can you provide the output of `php please support:details` and the blueprint for your Products taxonomy?

**Comment by emran-alhaddad** [comment] 2024-02-14 11:36
Thanks for waiting to my response , appreciate that 



this is the output of `php please support:details`  


Environment
Application Name: Juthor
Laravel Version: 10.43.0
PHP Version: 8.2.14
Composer Version: 2.5.5
Environment: production
Debug Mode: ENABLED
URL: juthor-cms.brackets-tech.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.47.0 PRO

Statamic Addons
statamic/eloquent-driver: 3.0.4

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Taxonomies: eloquent
Terms: eloquent

**Comment by duncanmcclean** [comment] 2024-02-14 11:45
Thanks. Can you share your taxonomy's blueprint too?

**Comment by emran-alhaddad** [comment] 2024-03-03 09:06
**this is the taxonomy**

id	handle	title	sites	settings	created_at	updated_at
1	products	Products	["english","arabic"]	{"revisions":false,"preview_targets":[{"id":"8YmbROb1","label":"Term","format":"{permalink}","refresh":true}]}	2024-02-06 08:30:50	2024-02-06 08:31:34


**This is one of the terms**
id	site	slug	uri	taxonomy	data	created_at	updated_at
1	english	facial	/products/facial	products	{"icon":{"icon_image":"uploads\/images\/home\/product-icon-1.svg"},"type":"none","image_media":{"image":null},"video_media":{"video":[]},"title":"Facial","description":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Reel width: min 40 cm, max 271 cm"},{"type":"hardBreak","marks":[{"type":"bold"}]},{"type":"text","marks":[{"type":"bold"}],"text":"Reel diameter : min 115 cm, max 260 cm"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Basis weight: 13 - 15.5 gsm "},{"type":"hardBreak"},{"type":"text","text":"Ply: 2,3"}]}],"updated_by":"9b412819-a8a3-4735-8f9c-cbea25180cf6","updated_at":1707208876,"blueprint":"product"}	2024-02-06 08:41:16	2024-02-06 08:41:16

**Comment by duncanmcclean** [comment] 2024-03-04 10:15
Thanks! What does the taxonomy's blueprint look like? Can you share the contents of its YAML file?

**Comment by duncanmcclean** [comment] 2024-03-26 18:53
I'm still not able to reproduce this issue on the latest version of Statamic, even alongside the Eloquent Driver.

I'm going to close this issue now. If you're still experiencing this issue on the latest version, please provide the relevant blueprint and we can take another look. Thanks!

**Closed by duncanmcclean** 2024-03-26 18:53 UTC
Labels: can't recreate, needs more info, taxonomies
