### ISSUE TITLE
Navigation and global set with the same title lead to error in control panel

### ISSUE THREAD

**Issue by RobertCordes** [statamic/cms#2439] opened 2020-09-16 11:12 UTC
## Bug Description
I have a multisite installation where I'm using globals. While trying to fix a different bug I thought maybe it would help to clear the cache. So I went to the control panel and did that. Since then I get the following error message when trying to access the globals or navigation page in the control panel:

> htmlspecialchars() expects parameter 1 to be string, array given (View: /Users/robertcordes/Code/hfrc-statamic/vendor/statamic/cms/resources/views/partials/nav-main.blade.php) 

## Extra Detail
Here is the flare link: https://flareapp.io/share/xmNDBO70#F82

## Environment
Statamic 3.0.8 Pro
Laravel 7.25.0
PHP 7.4.2
rias/statamic-color-swatches 2.0.5

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by RobertCordes** [comment] 2020-09-16 12:19
After renaming the title (inside the yaml file) of my navigation from "Footer" to "Footer Navigation", the navigation page started working again. I also had a global set named "Footer". After renaming it to "Footer Globals" the globals page was working again. I don’t really consider that a "fix" though 🤓

**Comment by robdekort** [comment] 2020-09-16 12:23
Can you expand on what you did and how you triggered a possible bug maybe? It's kinda hard to figure out what happened and if you did encountered a bug without a little more information.

**Comment by RobertCordes** [comment] 2020-09-16 13:59
Yeah I understand. This is actually pretty weird and it seems like it may have nothing to do with cache. There seems to be an issue when you have a navigation and a global set with the same name.

The initial issue I was trying to fix was that my footer navigation would throw an error. Then I cleared the cache and after that tried changing my navigation configuration. That’s where this issue came up, so I thought it had something to do with the cache.

After two hours of fiddling around I finally renamed the titles of the of the navigation and the global set from "Footer" to "Footer Navigation" and "Footer Globals". After that the pages in the control panel were working again. They even work when they are both called "Footer XY".

**But:** I still couldn't get my footer navigation to work. Only after renaming the global set from `footer.yaml` to `site_footer.yaml` (the navigation file is called `footer.yaml`) the navigation would show up.

So, there are two weird things going on:

1. Neither the global set nor the navigation can have the title "Footer", otherwise the `htmlspecialchars()` error comes up when opening the globals or navigation in the control panel.
2. The handles of a global and a navigation can't be the same. One can be "footer" (`footer.yaml`) but not both.

**Comment by damcclean** [comment] 2020-09-16 16:25
I'm unable to reproduce this bug.

I created a global set and a navigation, both with `Footer` as the name and `footer` as the handle. I added a field to the global and a link to the navigation and I can't see the issue.

I'd imagine the reason it's converting to an array instead of a string is because there's two `Footer`s. Although, as I can't replicate the issue I can't be sure.

Could you try reproducing on another site and see if you have the same issue. If you do, could you add some steps to reproduce the issue. Thanks 🙂

**Comment by RobertCordes** [comment] 2020-09-16 16:46
Yeah, I will try to reproduce. Although this is already a pretty fresh install. Maybe it’s because I'm using a multisite setup.

**Comment by jasonvarga** [comment] 2020-09-30 15:58
Hey there, we haven’t heard back on this for a while so I’m going to need to close the issue to help us stay organized. You can always reply with more info so we can reopen it.

**Closed by jasonvarga** 2020-09-30 15:58 UTC
Labels: can't recreate, needs more info
