### ISSUE TITLE
Dates are not being displayed properly in collections

### ISSUE THREAD

**Issue by zacksmash** [statamic/cms#2654] opened 2020-10-14 12:35 UTC
## Bug Description
In a collection entry edit page, a date/time field does not display the date that was last saved/entered.

## How to Reproduce
- Create a collection
- Create a blueprint
- Add 2 date/time fields for "start" and "end" to the blueprint, under the Format field use `U`
- Choose a date for each field, where start is one date, and end is a date in the future (any time)
- Reload the page and notice that the fields will not be the same dates you picked previously

## Environment
Statamic 3.0.17 Pro
Laravel 7.28.4
PHP 7.4.11
statamic/seo-pro 2.0.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by zacksmash** [comment] 2020-10-15 01:02
This is also happening in global fields, so it appears it's not specific to Collections.

**Comment by damcclean** [comment] 2020-10-16 21:42
I can reproduce this bug. It seems that when the dates are saved to the YAML, they are saved like this, even if dates are selected initially before save.

```yaml
start: '000000'
end: '000000'
```

When you refresh the entry in the CP after save, the date fieldtypes will show the current date.

**Comment by zacksmash** [comment] 2021-01-18 04:35
I don't think this is resolved yet.

**Comment by sandersjj** [comment] 2021-02-14 20:21
I have just tested this and can't reproduce it anymore.

**Comment by duncanmcclean** [comment] 2021-02-14 20:23
Just had a check over this, doesn't look like it's an issue anymore, here's an example of what's saved to the entry's YAML file.

```yaml
start_date: '1613606400'
end_date: '1614384000'
```

I'm closing this issue as it looks to be fixed. If you're still having this issue on the latest version, let me know and I can re-open this issue.

**Closed by duncanmcclean** 2021-02-14 20:23 UTC
Labels: bug
