### ISSUE TITLE
Apache issue? Client turned on SSL getting mixed content type issue

### ISSUE THREAD

**Issue by Pixney-William** [statamic/cms#2309] opened 2020-08-27 15:47 UTC
## Bug Description
Everything was working fine until client switched on SSL. Then we get the mixed content type issue within the control panel. But only accessing the assets (as far as we have seen).

Tried forcing http through the AppServiceProvider as well as through the htaccess file. No luck so far.

The client is on an apache server it's something with that i expect. Other people has asked about this in the forum:
https://discordapp.com/channels/489818810157891584/489819906540568593/697068813505789992
https://discordapp.com/channels/489818810157891584/489819906540568593/747748480214237264

Locally, on my valet setup it works fine even valet securing the test domain and running this so its something with how it should be setup using apache i think

**Comment by Pixney-William** [comment] 2020-08-27 15:50
Similar: https://github.com/statamic/cms/issues/1299

**Comment by jasonvarga** [comment] 2020-08-27 15:57
Are you using Cloudflare for SSL?

**Comment by Pixney-William** [comment] 2020-08-27 16:15
@jasonvarga no, lets encrypt. And this also failed earlier on nginx/apache hybrid instance i ran earlier on runcloud (this it not on there). As soon as i switched to nginx it worked fine.

![image](https://user-images.githubusercontent.com/31292231/91467746-485a4980-e891-11ea-947b-be88e96f23a3.png)

**Comment by jasonvarga** [comment] 2020-08-27 16:16
Can you post your config/statamic/sites.php ?

**Comment by Pixney-William** [comment] 2020-08-27 16:17
Ill do it in the chat privately @jasonvarga

**Comment by Pixney-William** [comment] 2020-08-27 17:34
Commenting out the following in the htaccess file sorts out the issue. 
![image](https://user-images.githubusercontent.com/31292231/91475800-624d5980-e89c-11ea-89f4-06d36e6cae6e.png)

**Comment by jackmcdade** [comment] 2020-09-01 15:51
👍  Closing as this is a server config issue, not a bug.

**Closed by jackmcdade** 2020-09-01 15:51 UTC

**Comment by gefangenimnetz** [comment] 2020-09-21 18:42
I am sorry to be the bad guy here, but i think this might need some more investigation. Apparently this problem also occurs for MS Azure App Service hosted apps. First I thought that this only happens with the default subdomain SSL (XYZ.azurewebsites.net), however it also happens for custom domains with TLS/SSL certs.

I am very willing to help investigate the issue. Unfortunately I am rather new to both Laravel and Statamic.

.htaccess fix from above will not help.
