### ISSUE TITLE
Error while creating/editing an entry inside an entry

### ISSUE THREAD

**Issue by SteJW** [statamic/cms#7258] opened 2022-12-19 22:12 UTC
https://user-images.githubusercontent.com/88787614/208616596-a2aecf6b-256a-49bc-b462-0fb5bb0a2e69.mov

### Bug description

When I edit a connected entry inside an entry, I get an Vue error in the console log. It also (more importantly) empties a field with the same handle in the entry I'm in or it replaces the image in the field. I think it has something to do with the same handle name.

### How to reproduce

I'm using Statamic 3.3.61. Create a blueprint products with an entry relationship field and an image asset.
Create another blueprint called "banners" where you have the same handle name of the asset as in products.
When I edit the banner entry from the products entry, and change the image of the banner, the image in the product gets emptied.

### Logs

```shell
vue.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'values')
    at a.render (Container.vue:285:1)
    at e._render (vue.common.prod.js:6:35309)
    at a.r (vue.common.prod.js:6:67998)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.run (vue.common.prod.js:6:27480)
    at cn (vue.common.prod.js:6:25588)
    at Array.<anonymous> (vue.common.prod.js:6:12294)
    at Ge (vue.common.prod.js:6:11693)
qe @ vue.common.prod.js:6
$e @ vue.common.prod.js:6
Re @ vue.common.prod.js:6
e._render @ vue.common.prod.js:6
r @ vue.common.prod.js:6
fn.get @ vue.common.prod.js:6
fn.run @ vue.common.prod.js:6
cn @ vue.common.prod.js:6
(anonymous) @ vue.common.prod.js:6
Ge @ vue.common.prod.js:6
vue.common.prod.js:6 TypeError: Cannot read properties of undefined (reading 'hiddenFields')
    at a.shouldForceHiddenField (ValidatorMixin.js:55:71)
    at a.showField (ValidatorMixin.js:17:55)
    at Fields.vue?2c4c:1:243
    at a.vt [as _l] (vue.common.prod.js:6:15921)
    at a.<anonymous> (Fields.vue?2c4c:1:131)
    at e._render (vue.common.prod.js:6:35309)
    at a.r (vue.common.prod.js:6:67998)
    at fn.get (vue.common.prod.js:6:26596)
    at fn.run (vue.common.prod.js:6:27480)
    at cn (vue.common.prod.js:6:25588)
```

### Environment

```yaml
Statamic 3.3.61
PHP 8.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment] 2023-12-08 13:26
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I created a similar setup to the one shown in the video - an image field on two blueprints (both with the same handle), then linking to an entry via a replicator in a bard set. When I clicked into the linked entry and coming back to the "main" entry, the image was still there as expected.

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-12-08 13:26 UTC
