### ISSUE TITLE
Color field: Can no longer set opacity

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#8683] opened 2023-09-08 16:00 UTC
### Bug description

I just noticed that I can no longer set opacity like I could on the old colour picker. I have a couple of sites, originally built on Statamic 3, that rely on opaque colours.

Am I missing something? Thanks!

### How to reproduce

Add a colour field and compare it to Statamic 3

### Environment

```yaml
Version: 4.21.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by jasonvarga** [comment] 2023-09-08 18:48
Duplicate of https://github.com/statamic/ideas/issues/1007

**Closed by jasonvarga** 2023-09-08 18:48 UTC
Labels: fieldtypes
