### ISSUE TITLE
Blueprint builder: Fields added to a blueprint don't display a fieldtype icon anymore

### ISSUE THREAD

**Issue by helloDanuk** [statamic/cms#2482] opened 2020-09-20 14:34 UTC
## Bug Description
In 3.0.10, fieldtype icons are no longer displayed in the blueprint builder when adding new fields to the blueprint. Only the default fieldtypes (Title, Slug, Parent) have an icon.

## How to Reproduce
- Go to blueprints
- Create a new blueprint for pages
- add some more fields to the blueprint

<img width="962" alt="Bildschirmfoto 2020-09-20 um 16 23 01" src="https://user-images.githubusercontent.com/8265902/93713788-79f7c500-fb5e-11ea-9c34-0eb68e455d2e.png">

## Environment

Statamic 3.0.10 Pro
Laravel 7.28.3
PHP 7.4.6
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment] 2020-09-20 14:42
Confirmed. 

This issue seems to only happen when you add a new field. If you refresh the blueprints page, the icon for the field will appear.

**Comment by jackmcdade** [comment] 2020-09-22 20:02
dupe of #1455 and fixed via #a00c1e4afa24e4133eeb4e91f2b518ecb2ee7d56.

**Closed by jackmcdade** 2020-09-22 20:02 UTC
Labels: bug
