### ISSUE TITLE
Error adding entry to navigation due to error with Select field

### ISSUE THREAD

**Issue by kyranb** [statamic/cms#4229] opened 2021-09-07 09:48 UTC
## Bug Description

When trying to "Link to an entry"  for a Navigation 

![Screen Shot 2021-09-07 at 7 39 11 pm](https://user-images.githubusercontent.com/5426926/132322647-1aeb0485-f482-46c5-a0cc-a16607ba7081.png)

The following error occurs:

`return array_get($this->field->get('options'), $value, $value);`

from `Statamic\Fieldtypes\Select.php` 

Adding a try/catch around this line allows it to work correctly 🤷‍♂️

## Extra Detail

`main.yaml`

```
title: Main
collections:
  - pages
root: true

````

`pages.yaml`

```
title: Pages
template: default
layout: layout
revisions: false
route: '{parent_uri}/{slug}'
sort_dir: asc
structure:
  root: true
```

Stacktrace

```
[2021-09-07 09:24:51] local.ERROR: array_key_exists(): The first argument should be either a string or an integer {"userId":"d8b39772-4914-4724-ad70-4445ff2e3056","exception":"[object] (ErrorException(code: 0): array_key_exists(): The first argument should be either a string or an integer at /Users/user/sites/site/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:155)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'array_key_exist...', '/Users/user/si...', 155, Array)
#1 /Users/user/sites/site/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(155): array_key_exists(0.5, Array)
#2 /Users/user/sites/site/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(296): Illuminate\\Support\\Arr::exists(Array, 0.5)
#3 /Users/user/sites/site/vendor/laravel/helpers/src/helpers.php(129): Illuminate\\Support\\Arr::get(Array, 0.5, 0.5)
#4 /Users/user/sites/site/vendor/statamic/cms/src/Fieldtypes/Select.php(100): array_get(Array, 0.5, 0.5)

```

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.23
simonhamp/statamic-heroicons 1.0.1
withcandour/aardvark-seo 2.0.15

Starter kit

**Comment by kyranb** [comment] 2021-09-14 11:37
So it turns out this was due to an old .md file that had set `sitemap_priority` as `0.5` (as a float) rather than `'0.5'`

See these issues here for anyone else facing the same:

https://github.com/statamic/cms/issues/3254

https://github.com/statamic/cms/issues/3819

**Comment by kyranb** [comment] 2021-09-14 11:37
Perhaps throwing an error that the type is not set correctly would be a little user friendly 👍

**Comment by duncanmcclean** [comment] 2023-11-29 10:05
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. 

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-29 10:05 UTC
Labels: navigations
