### ISSUE TITLE
Multisite: {{ parent:url }} not working

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2681] opened 2020-10-19 11:43 UTC
## Bug Description
I have a collection, which is mounted to the overview page. I want to link from the entry site back to the overview with `{{ parent:url }}`. On the default locale, this is working, on the other locales, it is empty.

## Environment

**Statamic version:** 3.0.19

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment] 2020-10-21 17:08
I'm unable to replicate. I added `{{ parent:url }}` in one of my templates and visited one of my entries with a parent entry and it returned the correct URL. I tried on all the sites in my multi-site and they all worked as they should.

**Comment by damcclean** [comment] 2020-10-21 17:54
In fact, this issue looks like a duplicate of #2298.

**Closed by damcclean** 2020-10-21 17:54 UTC
Labels: can't recreate
