### ISSUE TITLE
"Desynced from origin" icon doesn't go away after clicking.

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#4091] opened 2021-08-05 10:13 UTC
## Bug Description

Restoring a localised replicator field to the origin's value works fine but the little icon that says "Desynced from origin. Click to sync..." doesn't go away.

## Extra Detail
![image](https://user-images.githubusercontent.com/20210934/128333359-8706dad8-93bb-45ab-b9ac-4cdab710cc5c.png)

## Environment
Statamic 3.1.29 Pro
Laravel 8.51.0
PHP 7.4.16
Existing Laravel app

**Comment by duncanmcclean** [comment] 2023-12-06 17:40
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. 

When I click the button when the value is de-synced, it restores the field to it's origin value and the icon changes and different tooltip text is displayed ("Synced with origin. Click or edit the field to desync.").

![CleanShot 2023-12-06 at 17 39 03](https://github.com/statamic/cms/assets/19637309/f2c99b94-3547-4520-9ac2-83305000a4d7)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-12-06 17:40 UTC
Labels: multisite
