### ISSUE TITLE
Taxonomies cut off in autocomplete

### ISSUE THREAD

**Issue by philsturgeon** [statamic/cms#1819] opened 2020-05-12 09:59 UTC
## Bug Description

I have 82 entries for a taxonomy, but when I try to associate collection entries via an autocomplete  field it cuts off at 15. 

Neither scrolling.on the dropdown, or searching will work.

## How to Reproduce

<img width="342" alt="Screen Shot 2020-05-12 at 10 52 20" src="https://user-images.githubusercontent.com/67381/81670370-6796ad80-943f-11ea-88c3-fb04a654c3b6.png">
<img width="959" alt="Screen Shot 2020-05-12 at 10 52 44" src="https://user-images.githubusercontent.com/67381/81670375-68c7da80-943f-11ea-9308-0a77a142f52d.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/67381/81670498-a0cf1d80-943f-11ea-9fb7-8864e0a3d46a.png">

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4.4

**Comment by jasonvarga** [comment] 2020-05-12 13:29
Duplicate of #1727

**Closed by jasonvarga** 2020-05-12 13:29 UTC
