### ISSUE TITLE
Can't add link to entry in navigation in beta 29

### ISSUE THREAD

**Issue by jmartsch** [statamic/cms#1901] opened 2020-06-06 11:29 UTC
## Bug Description
When I try to add a link to an entry in a navigation a JavaScript error is thrown:
```
isURLSameOrigin.js:57 Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined
    at isURLSameOrigin.js:57
    at xhr.js:109
    at new Promise (<anonymous>)
    at e.exports (xhr.js:12)
    at e.exports (dispatchRequest.js:50)
```
This problem just occurs in the latest beta. It worked fine in beta 28

## How to Reproduce

- Add a collection with some items in it
- Add a new navigation and allow linking to entries of your collection
- Add a link to an entry
- Error

## Extra Detail

![msedge_2020-06-06_13-16-12](https://user-images.githubusercontent.com/551551/83943141-e0e4ae80-a7f9-11ea-924d-e5fb242b0ad9.png)

## Environment

**Statamic version:** 3.0.0.-beta-29

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-06-06 15:38
Duplicate of #1893

**Closed by jasonvarga** 2020-06-06 15:38 UTC

**Comment by jmartsch** [comment] 2020-06-06 15:40
Yeah, sorry for the duplicate. Searched for the error, but only in open issues.

**Comment by jasonvarga** [comment] 2020-06-06 15:48
All good. It's fixed and will be in the next release. We'll get it out on Monday.
