### ISSUE TITLE
Adding Entry with Bard field to Navigation results in Markdown\Parser::parse() error

### ISSUE THREAD

**Issue by EricBusch** [statamic/cms#3577] opened 2021-04-22 15:01 UTC
## Bug Description

Attempting to "Link to Entry" in a Navigation generates the following error if one of the Entries contains a Bard field:

> Argument 1 passed to Statamic\Markdown\Parser::parse() must be of the type string, array given, called in /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Markdown/Manager.php on line 15

Full error log below.

Hope this helps! Let me know if you have any questions.

## How to Reproduce

1. Create a new Collection called Posts like this:
2. Scaffold the Resource
3. Add a new Bard field to the Post Main blueprint and set the handle to `content`
4. Create a new Post and add some content to the Bard content area.
5. Create a new Navigation named "Main Nav"
6. Click "Link to Entry" option and you will see the error. (see below)

If you remove the `content` field from the post's headmatter, then adding the Entry to the nav works.

### Adding an Entry to Main Nav

<img width="1101" alt="Screen Shot 2021-04-22 at 10 50 04 AM" src="https://user-images.githubusercontent.com/12106436/115735799-c3103180-a358-11eb-94e0-004202bead91.png">

###  Contents of `content/collections/posts/2021-04-22.first-blog-post.md`

This post causes the error to appear....

```
---
id: 1d8949fe-e1c5-44e1-8e46-e00dea56be80
title: 'First Blog Post'
updated_by: 5b36f9d8-f3fd-40e8-b511-9c11f820eede
updated_at: 1619102055
content:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Mattis sodales pellentesque semper habitant torquent.'
---
```

...however this post does **_NOT_** cause the error to appear.

```
---
id: 1d8949fe-e1c5-44e1-8e46-e00dea56be80
title: 'First Blog Post'
updated_by: 5b36f9d8-f3fd-40e8-b511-9c11f820eede
updated_at: 1619102055
---
```

## More Info

I changed the `Statamic\Markdown\Parser::parse()` method to the following to debug:

```php
    public function parse($markdown): string
    {
        Log::info($markdown);

        return $this->converter()->convertToHtml($markdown);
    }
```

That added the following 2 entries to my Log file.

```
[2021-04-22 14:58:01] local.INFO: Welcome to your new Statamic website.  
[2021-04-22 14:58:01] local.INFO: array (
  0 => 
  array (
    'type' => 'paragraph',
    'content' => 
    array (
      0 => 
      array (
        'type' => 'text',
        'text' => 'Mattis sodales pellentesque semper habitant torquent.',
      ),
    ),
  ),
)  
```

## Environment

- Statamic 3.1.9 Solo
- Laravel 8.38.0
- PHP 7.4.9
- No addons installed

**Install method (choose one):**
- Fresh install using `composer create-project --prefer-dist statamic/statamic statamic-playground` 

## Error Log

```
[2021-04-22 14:37:51] local.ERROR: Argument 1 passed to Statamic\Markdown\Parser::parse() must be of the type string, array given, called in /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Markdown/Manager.php on line 15 {"userId":"5b36f9d8-f3fd-40e8-b511-9c11f820eede","exception":"[object] (TypeError(code: 0): Argument 1 passed to Statamic\\Markdown\\Parser::parse() must be of the type string, array given, called in /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Markdown/Manager.php on line 15 at /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Markdown/Parser.php:23)
[stacktrace]
#0 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Markdown/Manager.php(15): Statamic\\Markdown\\Parser->parse(Array)
#1 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Markdown\\Manager->__call('parse', Array)
#2 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Support/Html.php(316): Illuminate\\Support\\Facades\\Facade::__callStatic('parse', Array)
#3 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Fieldtypes/Markdown.php(116): Statamic\\Support\\Html::markdown(Array)
#4 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Fields/Field.php(259): Statamic\\Fieldtypes\\Markdown->preProcessIndex(Array)
#5 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(60): Statamic\\Fields\\Field->preProcessIndex()
#6 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(687): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->Statamic\\Http\\Resources\\CP\\Entries\\{closure}(Object(Statamic\\CP\\Column), 1)
#7 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(64): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#8 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Resources/CP/Entries/ListedEntry.php(41): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->values(Array)
#9 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry->toArray(Object(Illuminate\\Http\\Request))
#10 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(231): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve(Object(Illuminate\\Http\\Request))
#11 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(846): Illuminate\\Http\\Resources\\Json\\JsonResource->jsonSerialize()
#12 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\Traits\\{closure}(Object(Statamic\\Http\\Resources\\CP\\Entries\\ListedEntry))
#13 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(854): array_map(Object(Closure), Array)
#14 [internal function]: Illuminate\\Support\\Collection->jsonSerialize()
#15 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(71): json_encode(Array, 0)
#16 /Users/Eric/Sites/statamic-playground/vendor/symfony/http-foundation/JsonResponse.php(54): Illuminate\\Http\\JsonResponse->setData(Array)
#17 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(31): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array)
#18 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(99): Illuminate\\Http\\JsonResponse->__construct(Array, 200, Array, 0)
#19 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(26): Illuminate\\Routing\\ResponseFactory->json(Array, 200)
#20 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(132): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse(Object(Illuminate\\Http\\Request))
#21 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(112): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse(Object(Illuminate\\Http\\Request))
#22 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Router.php(774): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse(Object(Illuminate\\Http\\Request))
#23 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Router.php(761): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#24 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Statamic\\Http\\Resources\\CP\\Entries\\Entries))
#25 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\CountUsers->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Localize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#44 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#54 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#55 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#56 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#57 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/Eric/Sites/statamic-playground/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /Users/Eric/Sites/statamic-playground/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /Users/Eric/Sites/statamic-playground/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/Eric/Sites/statamic-playground/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#84 /Users/Eric/Sites/statamic-playground/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#85 /Users/Eric/Sites/statamic-playground/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#86 /Users/Eric/.composer/vendor/laravel/valet/server.php(191): require('/Users/Eric/Sit...')
#87 {main}
"} 
```

**Comment by duncanmcclean** [comment] 2021-04-22 15:05
I think `content` may be a reserved word that you can't use for a Bard field.

**Comment by jasonvarga** [comment] 2021-04-22 15:27
It's not reserved, but this is a duplicate of https://github.com/statamic/cms/issues/2862

The workaround for now would be to either:
- Make the `markdown` field a `bard` field. If you're using Bard in one collection, it probably makes sense to also use Bard in the other anyway.
- Name the bard field and markdown fields differently. e.g `content` vs. `body`.

**Closed by jasonvarga** 2021-04-22 15:27 UTC
Labels: bard

**Comment by EricBusch** [comment] 2021-04-22 15:35
> Name the bard field and markdown fields differently. e.g content vs. body.

This worked for me. Thanks!
