### ISSUE TITLE
Looping Locales returns "Call to a member function value() on string"

### ISSUE THREAD

**Issue by JesperWeCode** [statamic/cms#1095] opened 2019-12-12 08:08 UTC
Might be related to #978 

Got this really simple test code, which throws the Call to a member function value() on string:
```
{{ locales }}
    <a class="dropdown-item" href="/dk"><img src='{{ theme:assets src="flags/da.png" }}' /> DA</a>
{{ /locales }}
```
Don't mind me not using any actual locale variable in it, this is just to showcase the error.

My sites.php file looks like the following:
```
'sites' => [

    'default' => [
        'name' => config('app.name'),
        'locale' => 'en_US',
        'url' => '/',
        'flag' => 'en'
    ],
    'dk' => [
        'name' => config('app.name') . ' - DK',
        'locale' => 'da_DK',
        'url' => '/dk/',
        'flag' => 'dk'
    ],
    'de' => [
        'name' => config('app.name') . ' - DE',
        'locale' => 'de_DE',
        'url' => '/de/',
        'flag' => 'de'
    ],

]
```

**Comment by edalzell** [comment] 2019-12-12 16:49
dupe of https://github.com/statamic/cms/issues/978?

**Closed** 2019-12-12 22:25 UTC
