### ISSUE TITLE
Error when "composer install"

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#2975] opened 2020-12-05 21:34 UTC
## Bug Description
I am unsure where to put this bug report. So the initial one, I posted here:
https://github.com/pixelfear/composer-dist-plugin/issues/5

I am using a Statamic project (from the statamic/statamic repo). When deleting the `vendor/` and `composer.lock` and trying to do a `composer install`, I get following error:

![error](https://user-images.githubusercontent.com/13189565/101265783-7af5c700-3749-11eb-9ce9-a0224719ce89.png)

I am using Composer version 1.10.19 and also tested with Composer 2. I am on Homestead and macOS.

Here is my `composer.json`:

```
{
    "name": "statamic/statamic",
    "description": "Statamic",
    "keywords": ["statamic", "cms", "flat file", "laravel"],
    "type": "project",
    "require": {
        "php": "^7.3",
        "aryehraber/statamic-color-extractor": "^1.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "statamic/cms": "^3.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi",
            "@php artisan statamic:install --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by jonassiewertsen** [comment] 2020-12-07 10:13
Could you add your comopser.json as well?

**Comment by felixstoessel** [comment] 2020-12-07 10:16
@jonassiewertsen Added.

**Comment by damcclean** [comment] 2020-12-08 22:16
I was able to use the `composer.json` file you provided just fine when running `composer install`. 

Have you tried running Composer from outside of the Homestead box? I've known it to be funny with things like that. Also, when you upgraded Composer, I'm guessing you did that in the Homestead box and not you're local machine, right?

**Comment by felixstoessel** [comment] 2020-12-08 22:51
Yes, I am running those commands inside the VM/Homestead.

Well, it just worked somehow by doing following: `composer install --no-scripts --no-plugins` (from https://github.com/laravel/homestead/issues/1240#issuecomment-691787229)

I just don't know why this issue only appears with my Statamic project...

**Comment by damcclean** [comment] 2020-12-08 22:58
I think it's due to the `pixelfear/composer-dist-plugin` composer plugin that's used by the Statamic core. Essentially, it compiles the CSS & JS for releases instead of them needing to be in Git. For whatever reason, Homestead doesn't seem to like it after its run.

**Comment by felixstoessel** [comment] 2020-12-08 23:00
Yeah, I also thought that this plugin might be the root cause.

**Comment by jasonvarga** [comment] 2020-12-10 00:17
Closing as the issue isn't in Statamic.

**Closed by jasonvarga** 2020-12-10 00:17 UTC
