### ISSUE TITLE
Editing an entry in Live Preview doesn't update preview.

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#6377] opened 2022-07-25 15:03 UTC
### Bug description

This might be covered in another issue but I'm noticing that editing an entry in a Live Preview doesn't update the preview.

Maybe a simple solution would be to refresh the preview every time the edit entry overlay is closed?

### How to reproduce

- If you click 'Edit' on an entry within an entry field on live preview.
- Make changes in the popup and save.
- Close the popup.
- Live preview does not update.

### Environment

```yaml
Statamic 3.3.20 Pro
Laravel 9.20.0
PHP 8.1.1
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jackmcdade** [comment] 2022-07-25 18:03
I can't recreate this. Do you have any other addons installed or any caching/config going on that might get in the way of Live Preview?

**Comment by jasonvarga** [comment] 2022-08-01 13:58
I can replicate the issue, but it's a duplicate of #1975

**Closed by jasonvarga** 2022-08-01 13:58 UTC
Labels: needs more info, live preview
