### ISSUE TITLE
Not able to use locale's special characters in search query

### ISSUE THREAD

**Issue by aspoet** [statamic/cms#4405] opened 2021-10-06 10:05 UTC
## Bug Description
When using the 'de' locale in _' config/statamic/app.php'_, _' config/statamic/sites.php'_  and _'config/statamic/system.php'_ the search results using the "live-search" addon break when special characters (in this case ä,ö,ü and ß) are introduced to the query. The translations and special character handling e.g in slugs work fine.

So if I live-search for 'Lieblingsbücher' the results are correct up until 'Lieblingsb' and after that no results are displayed anymore.

## How to Reproduce
- Set all locales and fallback locales to 'de'
- php please search:update --all
- enter a search query with a special german character

## Extra Detail
I have openened a corresponding issue at the [live-search addon repo ](https://github.com/jonassiewertsen/statamic-live-search/issues/9) .

## Environment
Statamic 3.2.10 Pro
Laravel 8.62.0
PHP 8.0.11
jonassiewertsen/statamic-live-search 1.2.0

**Comment by aspoet** [comment] 2021-10-06 15:04
> 
> 
> This may be related to #4284

Yep, those changes from the PRs fixed the issue. Thank you!

**Comment by jasonvarga** [comment] 2021-10-06 18:43
Even without the PR, it works fine for me.

Can you create a repo with this problem?

**Comment by arlindmusliu** [comment] 2022-01-24 13:39
Hi,

I'm having the same issue trying to implement search with cyrillic letters in a multisite. After reading this thread, I created a blank project, without multisite, but the problem is the same.

The blank project doesn't have anything fancy. I create a post with a title and content in cyrillic letters, but when I search for the title it won't display anything. The url display the correct query in cyrillic. `http://project.test/search?q=драги`

If I try a combination of cyrillic and english title, it shows the result when I search the english words, but not for cyrillic.

I will try jumping to Fuse.js for this, but a fix on this issue would be helpful.

**Comment by lasseron** [comment] 2022-02-01 16:34
I'm having the same issue with ä,ö,ü characters.

**Comment by K3CK** [comment] 2022-03-31 15:59
In my case the problem came from Statamic's default sanitizing of GET parameters. 

I am not using the default search but built my own collection tag where I also make use of the search index. To my custom tag I was handing over a `query` GET Parameter in an antlers template like so which then is used for performing the search: 

`{{ custom_collection
...
    query="{get:query}"
}}` 

But if you use Statamic's `get` variable (https://statamic.dev/variables/get) you must be aware of the fact that all GET params get sanitized with htmlentities() here: https://github.com/statamic/cms/blob/7ade3d7d3b3032c82badafc84e49c069b17fed08/src/Support/Html.php#L93

This results in special characters to being converted to HTML entities: ü becomes `&uuml;` and ö becomes `&ouml;` and so on. So for example when you were searching for the word `gründen` then what the search engine actually was looking for in the index was `gr&uuml;nden`, which is not there as the index is not built with encoded values, resulting in 0 results.

I fixed the problem by decoding the param again when handing it over to my custom collection using the decode modifier (https://statamic.dev/modifiers/decode):

`{{ custom_collection
...
    query="{ get:query | decode }"
}}` 

With that the search works also for special characters.

**Comment by duncanmcclean** [comment] 2024-04-05 14:38
This has been fixed in Statamic 5, which we're hoping to release in the next few days/weeks.

**Closed by duncanmcclean** 2024-04-05 14:38 UTC
Labels: search
