### ISSUE TITLE
Update user fails on Email: "this value has already been taken"

### ISSUE THREAD

**Issue by dakisan** [statamic/cms#1466] opened 2020-03-03 15:22 UTC
Beta 18

User exists in DB and is super.

Log into CP, edit the user (or not). Click Save.

https://cdn.discordapp.com/attachments/489819906540568593/684363390831034370/unknown.png

**Comment by Konafets** [comment] 2020-06-12 15:37
Sounds like an duplicate of #1408

**Comment by jasonvarga** [comment] 2020-06-29 21:21
Fixed by #1574

**Closed by jasonvarga** 2020-06-29 21:21 UTC
Labels: database
