### ISSUE TITLE
Call to a member function editUrl() on null when accessing globals in multisite

### ISSUE THREAD

**Issue by jurnskie** [statamic/cms#3883] opened 2021-06-20 17:45 UTC
## Bug Description
Accessing globals in multisite produces Call to a member function editUrl() on null. 
  
## How to Reproduce
1. Make single site.
2. Create globals
3. Configure Multisite and add second site
4. Access globals reproduces above error
## Extra Detail

tatamic\Http\Controllers\CP\Globals\GlobalsController::Statamic\Http\Controllers\CP\Globals\{closure}
vendor/statamic/cms/src/Http/Controllers/CP/Globals/GlobalsController.php:31

## Environment

**Statamic version:** 3.1.25
**PHP version:** 8.0.7

**Install method (choose one):**
- Fresh install from statamic/statamic

**Comment by duncanmcclean** [comment] 2021-06-20 17:48
Closing as duplicate of #1636.

**Closed by duncanmcclean** 2021-06-20 17:48 UTC
