### ISSUE TITLE
Adding sites to collection without route throws: Cannot read properties of null (reading 'default')

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/cms#4392] opened 2021-10-05 10:13 UTC
## Bug Description
If you add sites to a collection without routes, you will get a console error and with a page refresh, the route input field is not visible anymore.

## How to Reproduce

- `php please multisite`
- Create collection and try to add sites without defining a route first.

## Extra Detail

![Bildschirmfoto 2021-10-05 um 12 06 28](https://user-images.githubusercontent.com/6337411/136003751-202af8b6-5d81-42c7-b9fa-e795b5d59f21.png)

## Environment
Statamic 3.2.11 Pro
Laravel 8.62.0
PHP 7.4.23
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment] 2022-12-17 09:41
I'm not able to reproduce this on the latest version of Statamic. No console errors for me.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/19637309/208235817-6493c908-ced5-4b49-9555-481e064472c1.png">

I'm going to close this issue for now. However, if you can still re-produce this, leave a comment and the issue can be re-opened.

**Closed by duncanmcclean** 2022-12-17 09:41 UTC
Labels: multisite
