### ISSUE TITLE
Constantly getting duplicated entries in main.yaml

### ISSUE THREAD

**Issue by chrisbjr** [statamic/cms#1515] opened 2020-03-18 16:38 UTC
Hi, we work on Statamic as a team but we find that we always end up getting duplicated entries in our `main.yaml` file no matter how many times we "clean it up". Not sure if there is just something wrong with our set up or is there a way to avoid this that we are missing?

Thanks

**Comment by jackmcdade** [comment] 2020-03-18 16:40
What's the `main.yaml` file? Is that a collection? Structure?

**Comment by chrisbjr** [comment] 2020-03-18 16:56
Oops, sorry - it's a structure, the content looks like this:

```
title: Main
tree:
  -
    entry: 31c045a0-f591-4d9e-a601-35f8e404b7ea
  -
    entry: e798f3c4-5a41-4554-b51b-4412a517e4a6
  -
    entry: 7b49930e-4919-422f-b1c0-746d80058cd0
  -
    entry: 4cdda099-fd88-475c-89d8-adb47ed2c4fd
  -
    entry: 38228250-ceed-48ee-add0-977f2700dc60
  -
    entry: 28c7c735-93cb-4364-901a-59822ed6e863
  -
    entry: a39535ae-b128-463f-b79d-8a60b71c448d
  -
    entry: 2c71dd6d-c888-4217-9698-ac4f1fc070c3
  -
    entry: 50bb2ec5-2d90-49b7-b940-510d19ad7645
  -
    entry: b60bc371-4f5b-4ce9-a16c-509b33cfaa41
  -
    entry: 6e9503b4-0199-46b9-a316-2af39c24c61f
  -
    entry: 8bec95d1-3e65-413d-9c7f-d794e02b1d3a
  -
    entry: 7f6c9d01-377f-4d89-8261-5ab55c103941
  -
    entry: be59d567-5190-4c43-93a5-85d6afc81c9b
  -
    entry: 05f130e0-5d2f-4a57-955c-38f0d2c84376
  -
    entry: 08fe11f5-ea71-489d-ae51-a144c65154a2
```

**Comment by chrisbjr** [comment] 2020-03-18 16:59
Not sure why but git doesn't know when the entries are the same and merges entries from other team members. We constantly have to check our staging branch when we merge our changes.

**Comment by jasonvarga** [comment] 2020-03-18 17:00
It should be a non-issue in the next release with all the structure-related changes.

Sounds like a duplicate of #679 

Please re-open if that doesn't end up being true.

**Closed by jasonvarga** 2020-03-18 17:00 UTC
Labels: needs more info

**Comment by chrisbjr** [comment] 2020-03-18 17:04
Thanks @jasonvarga yes, this issue is definitely a duplicate of #679
