### ISSUE TITLE
Visible header cell tooltip tags bug

### ISSUE THREAD

**Issue by chrisknnedy** [statamic/cms#8282] opened 2023-06-08 03:02 UTC
### Bug description

When using the _Table_ UI mode, HTML tags are visible when viewing any instruction tooltips:
<img width="545" alt="tooltip-bug" src="https://github.com/statamic/cms/assets/78626938/bf48f920-f66e-4090-ae98-46ad5c7b346e">

### How to reproduce

1. Create a new _Grid_ field with the UI mode set to _Table_
2. Populate instructions for a field within the grid
3. Unwanted tooltip tags will be visible when editing an entry using this field

### Environment

```yaml
Statamic 4.5.0 + PHP 8.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment] 2023-06-08 06:20
Duplicate of #8256.

**Closed** 2023-06-08 06:20 UTC
