### ISSUE TITLE
{{ taxonomy:tax-name collection="col-name" }} shows all terms

### ISSUE THREAD

**Issue by wm-simon** [statamic/cms#1993] opened 2020-06-26 17:23 UTC
## Bug Description
If you want to filter for the used terms of a collection, there are shown all terms.

## How to Reproduce
See code

## Extra Detail
```
    {{ taxonomy:tax-name collection="col-name" }}
    {{ title }}
    {{ /taxonomy:tax-name }}
```

## Environment

**Statamic version:** 3.0.0.-beta-31

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by ebeauchamps** [comment] 2020-06-30 15:39
shouldn't you add  min-count="1" ?

**Comment by jasonvarga** [comment] 2020-06-30 19:17
Are you saying terms from all collections are being shown in that loop?

Or that unused terms in that collection are being shown?

**Comment by Pfeifakopf** [comment] 2020-07-01 14:14
Hey, I meant, all the terms from the taxonomy list are shown. The unused terms are shown as well. The `collection="col-name"` has no effect of the result.

**Comment by padders** [comment] 2020-07-29 15:42
I get this too, I think I'm just not quite getting how to do this properly in v3. I have 2 collections, both using the same taxonomy called 'topics'. Topics has a lot of terms in it, so we don't want to display all possible terms in both collections. 

In my collections folder, I have an index.antlers.html that I would like to show a list of all the topics that relate to that collection. I've tried all sorts of ways of trying to do this but I can't get it right. 

My code currently looks like this, but it outputs all of the topics instead of only the ones that relate to the collection (i.e. topics that have been tagged onto an entry in the collection)

```
{{ taxonomy:topics :collection="portfolio" min_count="1" }}
      <a class="rm-simple-link" href="{{url}}">{{title}}</a> 
{{ /taxonomy:topics }}
```

Any idea where I'm going wrong?

**Comment by padders** [comment] 2020-07-30 07:44
Just adding that I've tried it like this too (and all sorts of other ways), which if I look at the docs would seem to be the right way to do it, but the collection option doesn't seem to do anything! Do you need to do something in the taxonomy to apply the tags to the collection, or is it enough to add a tag to an entry in the collection?

https://statamic.dev/tags/taxonomy#parameters

```
{{ taxonomy:topics collection="portfolio" }}
        <a class="rm-simple-link" href="{{url}}">{{title}}</a> 
{{ /taxonomy:topics }}
```

We're trying to get a list of filters, like below, but we only want the ones that apply to that specific collection and it's outputting all of them.

![Screenshot 2020-07-30 at 08 42 37](https://user-images.githubusercontent.com/15945371/88895438-b125b600-d240-11ea-9679-02a333582bdb.png)

**Comment by mikemartin** [comment] 2020-09-15 09:17
Confirmed. This appears to still be happening in the latest release. In my case I'm using a taxonomy called `tags` that's shared between 3 collections. All terms are showing and the collection parameter doesn't have any effect.

**Comment by mikemartin** [comment] 2020-09-15 20:58
@jasonvarga  Can you confirm if this is a bug or the intended design? The only way to show only tags with results is by wrapping them with `{{ if entries }}...{{/if}}`. 

```
{{ taxonomy:tags collection="integrations" }}
  {{ if entries }}
      <a href="{{ url }}" class="badge-spaced badge badge-lg badge-secondary">{{ title }}</a>
  {{ /if }}
{{ /taxonomy:tags }}
```

**Comment by FlorianMoser** [comment] 2021-01-14 17:39
I can confirm this and it is easy to reproduce (and for the sake of stopping the evil bot from closing this issue):

1. Create a taxonomy, for example "tags"
2. Create two collections, for example "news" and "team"
3. Create a `tag`and assign it to two `news` entries and to one `team` entry
4. The following Antlers code should then output `1`, but it outputs `3`

```
{{ taxonomy:tags collection="team" }}
    {{ entries_count }}
{{ /taxonomy:tags }}
```

For the same reason, the attribute `min_count` is also broken, because it counts the count from all collections, and not just from the filtered collection(s?).

**Comment by FlorianMoser** [comment] 2021-03-17 09:24
Still an issue with 3.0.47.

**Comment by FlorianMoser** [comment] 2021-05-18 10:19
What kind of "more info" is needed?

**Comment by zgambs** [comment] 2021-06-14 13:41
This looks related: https://github.com/statamic/cms/issues/1684 

Curious what other information could be given in order to have some motion on either this issue or the one linked above.

**Comment by jasonvarga** [comment] 2021-06-17 20:34
Closing this in favor of #1684. Definitely a duplicate.

**Closed by jasonvarga** 2021-06-17 20:34 UTC
Labels: needs more info
