### ISSUE TITLE
Field's type labels need a dedicated translation key

### ISSUE THREAD

**Issue by billmn** [statamic/cms#2113] opened 2020-07-21 17:35 UTC
## Bug Description
For some languages (like Italian) is not a good idea translate field's type, because it would make difficult for the user to identify the original field type.

An example:
A `select` field does not have a good Italian translation (like "Menu a discesa" 🤮 ). It could keep the name "Select".

Another problem is that the "Link" translation key (e.g. in "it.json") is used for the `Link field` and for the `Link button`(in the section when you can link an existent field).

In italian the `Link field` could be translated to "Collegamento" but the `Link button` is an action, so could be translated to "Collega".

Is it possible to add specific translations for field types?

## Extra Detail
![Schermata 2020-07-21 alle 19 31 39](https://user-images.githubusercontent.com/779534/88087391-1adef980-cb89-11ea-9ec4-1954bb5fb55c.png)

## Environment

**Statamic version:** 3.0.0-beta-37

**Comment by jasonvarga** [comment] 2020-07-21 17:36
Duplicate of #2034

**Closed by jasonvarga** 2020-07-21 17:36 UTC
