### ISSUE TITLE
Taxonomie Handles get mixed up

### ISSUE THREAD

**Issue by alexscro** [statamic/cms#5420] opened 2022-03-07 10:15 UTC
### Bug description

When creating a new taxonomy in the CMS, it applies the name of the latest created taxonomy to all previously created taxonomies. The GraphQL key changes and all queries do not work any longer.

In this case, I created a taxonomy called "Auto" as my third taxonomy and now "_Auto" is applied to every other taxonomy.

Please help as this blocks the usage of taxonomies completely.
 
![Screenshot 2022-03-07 at 11 13 59](https://user-images.githubusercontent.com/36740862/157011811-62a52e96-92e7-4770-bcb4-23d78cc007b7.png)

### How to reproduce

1. Create Taxonomy
2. Check Taxonomy handle in GraphQL data layer
3. Create another Taxonomy
4. Check Taxonomy handle in GraphQL data layer

In this case, I created a taxonomy called "Auto" in the end and now "_Auto" is applied to every other taxonomy. 
![Screenshot 2022-03-07 at 11 13 59](https://user-images.githubusercontent.com/36740862/157011732-f5025a39-80a3-49a4-a882-518f8803d2b7.png)

### Versions

Statamic 3.2.35

### Installation

Fresh statamic/statamic site via CLI

**Comment by alexscro** [comment] 2022-03-11 10:47
@duncanmcclean 

Hey!
We would appreciate it if you could look into that, we are currently blocked on a project because of that.

Thanks, Alex

**Comment by duncanmcclean** [comment] 2022-03-11 10:50
Sorry, I don't work for Statamic, I just triage & label issues. The Core Team will get to it when they find some time.

**Comment by alexscro** [comment] 2022-03-15 15:00
I can confirm that there has been a duplicate handle name for a blueprint and taxonomy that caused this error to happen.
Closing the ticket therefore.

**Comment by alexscro** [comment] 2022-04-01 08:25
Unfortunately, it's really a bug.
I created 2x taxonomies and the name of the first created one get's applied to the second one.

![Screenshot 2022-04-01 at 10 25 06](https://user-images.githubusercontent.com/36740862/161225372-dcf1aa6e-e901-49c2-88be-27a52cc0a751.png)

**Comment by edalzell** [comment] 2022-04-01 16:33
> Unfortunately, it's really a bug. I created 2x taxonomies and the name of the second one created get's applied to the first one.
> 
> @JohnathonKoster can you take a look?

He'd have nothing to do with this, please don't tag people directly. The core team sees all issues and works on them when appropriate.

**Comment by alexscro** [comment] 2022-04-01 16:35
@edalzell 
Sorry, I just saw that he was assigned to a couple of taxonomy related stuff ✌🏻
Thanks! Appreciate it.

**Comment by valschr** [comment] 2022-07-26 07:16
Any update on this? It's still happening and a major blocker!

**Comment by valschr** [comment] 2022-07-29 13:12
Looks like this is coming from here 
https://github.com/statamic/cms/blob/0c8f5a15e829311bfa40a1fd55a190c594a2fdaa/src/GraphQL/Types/TermInterface.php#L54-L61

The `$term->blueprint()` that gets passed to the `buildName` function is the last one that was created, not the one belonging to that term.

**Comment by duncanmcclean** [comment] 2024-01-08 13:11
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. The taxonomy handles seem to be correct to me:

![CleanShot 2024-01-08 at 13 10 09](https://github.com/statamic/cms/assets/19637309/2dad6b15-fe08-43e3-b11e-e517d82fdfca)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2024-01-08 13:11 UTC
Labels: taxonomies, graphql
