### ISSUE TITLE
Slug: Cannot customize conversion rules

### ISSUE THREAD

**Issue by scbing** [statamic/cms#4087] opened 2021-08-04 06:21 UTC
The current Slug field is still empty after entering the Chinese title, and it needs to be manually entered to save it.

My idea is: Either change the Slug in the blueprint field configuration so that its value can be empty, or use Laravel Str::slug($title,'zh') to convert, zh can be to read the configuration file: config( 'app.locale').

The blueprint configuration can be left blank, then I will listen to the save event: EntrySaving detects whether the slug field is empty when the event is saved, and then saves this value according to my idea.

However, the default Slug field of the current blueprint field cannot be changed to a null value, and the current idea cannot be realized.

```php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        \Statamic\Events\EntrySaving::class => [
            \App\Listeners\TranslateEntitySlug::class,
        ]
    ];
}

```

```php
<?php

namespace App\Listeners;

use App\Services\FanYi;
use Statamic\Events\EntrySaving;

class TranslateEntitySlug
{
    protected $fanyi;

    public function __construct(FanYi $fanyi)
    {
        $this->fanyi = $fanyi;
    }

    public function handle(EntrySaving $event)
    {
        /** @var \Statamic\Entries\Entry $entry */
        $entry = $event->entry;

        if ($entry->slug()) {
            return;
        }

        if (!$title = $entry->get('title')) {
            return;
        }

//        if (!$slug = \Str::of($title)->slug('-', config('app.locale'))) {
//            return;
//        }

        if (!$slug = $this->fanyi->translate($title, 'auto', 'zh')) {
            return;
        }

        $entry->slug($slug);
    }
}
```

**Comment by duncanmcclean** [comment] 2021-08-04 06:54
For future notice, please follow the issue template. It really does help with gathering all the information needed to fix your issue. Thanks!

**Comment by duncanmcclean** [comment] 2021-08-04 06:55
Have you seen #2817, is this a duplicate of that?

**Closed** 2021-08-04 08:32 UTC
