### ISSUE TITLE
A missing fieldset does break the cp

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#3771] opened 2021-05-25 17:23 UTC
When a user changes the slug of an imported fieldset via the control panel it breaks. 

## How to Reproduce
1. Create fieldset
2. Import this fieldset into a blueprint using the control panel
3. Rename the fieldset via control panel
(Everything should be done via the cp)

## What will break
1. Fieldsets can't be shown nor edited anymore
2. Any blueprint importing the not existing fieldset can't be shown or edited anymore

## How could this be solved
Instead of returning null and thereby throw an exception when the fieldset could not be found, we could return a html fieldtype with a message, that the imported fieldset does not exist.

A first draft approach (which does not cover everything), can be found here with more explicit information:
https://github.com/statamic/cms/pull/3314

## Environment

**Statamic version:** 3.1

**PHP version:** 7.4 & 8.0

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment] 2021-05-25 17:34
Duplicate of #3061

**Closed** 2021-05-25 17:35 UTC
Labels: error handling, fieldtypes
