### ISSUE TITLE
[Bug]: CP Pages List Empty

### ISSUE THREAD

**Issue by shaykingsbury** [statamic/cms#2566] opened 2020-09-30 18:08 UTC
### Bug Description
Upon loading Collections > Pages, there are no pages displayed. Unable to select to view by tree. Below console error when trying to view by tree:

```
TypeError: Cannot read property 'length' of undefined
    at a.<anonymous> (Statamic.js:66)
    at a.e._render (vue.common.prod.js:6)
    at a.r (vue.common.prod.js:6)
    at fn.get (vue.common.prod.js:6)
    at fn.run (vue.common.prod.js:6)
    at un (vue.common.prod.js:6)
    at Array.<anonymous> (vue.common.prod.js:6)
    at Ge (vue.common.prod.js:6)
```
### How to Reproduce
Video for repro steps & collection settings: https://drive.google.com/file/d/14x9N4rFg6X8rl9Qx-Tzh5llRcgDBJT_u/view

1. Click Collections -> Pages
2. Observe no content
3. Click list view (works fine)
4. Click tree view (console error displays again)

**Environment**
Statamic 3.0.10 Pro
Laravel 7.28.3
PHP 7.4.9
edalzell/mailchimp 2.0.6
statamic/migrator dev-master
statamic/seo-pro 2.0.13

**Comment by jasonvarga** [comment] 2020-09-30 18:12
Does this happen after you upgrade to the latest release? Seems awfully similar to https://github.com/statamic/cms/issues/2408

**Comment by robdekort** [comment] 2020-09-30 19:03
I can see the available update badge so 99% sure it's indeed a duplicate of #2408. Closing until further notice :-).

**Closed by robdekort** 2020-09-30 19:03 UTC

**Comment by shaykingsbury** [comment] 2020-09-30 22:09
Surprise surprise, worked 👍
