### ISSUE TITLE
Taxonomy fieldtype Max Items setting not allowing blank field

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/cms#2155] opened 2020-07-29 19:26 UTC
## Bug Description
Issue 1: Taxonomy field with any mode and "Max Items" set to "1" does not allow for the field to be left blank on the corresponding collection entry form. This forces the user to select a tag even if none is applicable.

If the field has mode set to "Dropdown" or "Typeahead", and Max Items set to any value other than "1", user is able to save an entry without selecting a value. However, the field allows the user to select more than the max items number — an alert on attempted save says, "May not have more than X items."

## How to Reproduce
Add a taxonomy field and set Max Items to "1" and select any mode. Attempt to save entry without selecting a taxonomy value. CP alert says, "Undefined Offset: 0". Setting the Max Items to a higher number allows a blank field, but only the "Stack Selector" mode limits user selections to the max value.

## Extra Detail
"Undefined Offset: 0" when saving entry with blank field.

## Environment

**Statamic version:** 3.0.0.-beta-40

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by damcclean** [comment] 2020-09-16 16:53
I'm closing this issue as I'm unable to reproduce the bug.

**Closed by damcclean** 2020-09-16 16:53 UTC
