### ISSUE TITLE
Table field input bug

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2907] opened 2020-11-24 14:26 UTC
## Bug Description
If you have added multiple rows in a table field, you can't fill just on row with text. The text fills all rows at the same time.
This happens with typing and c/p.
## Extra Detail

https://screencast-o-matic.com/watch/cYXZ2rL5XM
## Environment

**Statamic version:** 3.0.30

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-11-24 15:18
Duplicate of #2470

**Closed by jasonvarga** 2020-11-24 15:18 UTC
