### ISSUE TITLE
Entry actions from list view (Duplicate, unpublish, etc.) should also work from tree view

### ISSUE THREAD

**Issue by tobimori** [statamic/cms#8879] opened 2023-10-25 12:39 UTC
### Bug description

As a user I'd expect the Duplicate, Unpublish and other actions that are only availalbe in the list view to be available in the tree view. This would make editor experience miles better.

### How to reproduce

Click on the three dots in a collection that has tree view enabled

### Environment

```yaml
Statamic 4.30
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment] 2023-10-25 12:40
Duplicate of statamic/ideas#575.

**Closed by duncanmcclean** 2023-10-25 12:40 UTC
