### ISSUE TITLE
Handle name generated again

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1554] opened 2020-03-27 18:36 UTC
![handle](https://user-images.githubusercontent.com/3351449/77788792-26e6fe80-7062-11ea-8f19-863cbf8166ac.gif)

**Comment by jackmcdade** [comment] 2020-03-27 18:37
Thanks for the report! It's actually a duplicate of #1249 though :)

**Closed by jackmcdade** 2020-03-27 18:37 UTC
