### ISSUE TITLE
Same slug in hierarchical structure not possible?

### ISSUE THREAD

**Issue by xyNNN** [statamic/cms#1281] opened 2020-01-30 21:16 UTC
Hey folks,

currently I'm playing with Statamic and I must admit that I'm very impressed from with piece of software, well done! 

For now I'm creating my page structure in two different languages, which works very well. But now I've encountered and issue and I need your help.

I've the following structure:

- Home (/)
- About us (/about-us)
- Contact (/contact)
- Business (/business)
  - About us (/business/about-us)

The problem is that this is not possible because the slug must be unique. I'm wondering if I do something wrong and my usecase it's not possible with this kind of feature from Statamic.

Or is there a workaround for this purpose?

Thanks in advance mates!

Cheers
xyNNN

**Comment by jasonvarga** [comment] 2020-01-30 21:18
No your fault! Duplicate of #714

**Closed** 2020-01-30 21:19 UTC

**Comment by xyNNN** [comment] 2020-01-30 21:24
> Not your fault! Duplicate of #714

This was a quick win, thanks @jasonvarga 
Not the best solution, but very smart and pragmatic ;) great!
