### ISSUE TITLE
Cannot edit/entry Globals for other sites/languages in CP

### ISSUE THREAD

**Issue by studiovlijmscherp** [statamic/cms#3817] opened 2021-06-09 14:54 UTC
## Bug Description
When switching to another site/language in the CP an error is thrown
`Error
Call to a member function editUrl() on null`

## How to Reproduce
- Add a Global in the default language
- Add an entry
- Switch to an other site/locale 

## Extra Detail
<img width="813" alt="Schermafbeelding 2021-06-09 om 16 52 29" src="https://user-images.githubusercontent.com/3353713/121378030-207d3380-c943-11eb-8250-351487c44510.png">
<img width="1072" alt="Schermafbeelding 2021-06-09 om 16 52 40" src="https://user-images.githubusercontent.com/3353713/121378036-21ae6080-c943-11eb-9958-982d032716a4.png">

## Environment
Statamic 3.1.20 Pro
Laravel 8.43.0
PHP 7.4.19

**Install method (choose one):**
- Other (please explain this magic!) -- Upgrade from V2 using statamic/migrator

**Comment by jasonvarga** [comment] 2021-06-09 14:59
Duplicate of #1636

**Closed by jasonvarga** 2021-06-09 14:59 UTC
