### ISSUE TITLE
Alignment of Section Heading and field headings slightly off

### ISSUE THREAD

**Issue by tobimori** [statamic/cms#9050] opened 2023-11-22 11:03 UTC
### Bug description

![CleanShot 2023-11-22 at 12 02 36@2x](https://github.com/statamic/cms/assets/29142128/01b616b8-ab56-4e39-ab52-3f0347a22366)

### How to reproduce

-

### Environment

```yaml
Statamic v4.36.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by duncanmcclean** [comment] 2023-11-22 13:28
Hey 👋

I'm closing this issue as you've left out some of the required fields in the issue template (like how to reproduce the issue & environment details).

Please open a new issue with the required fields. Thanks!

**Comment by tobimori** [comment] 2023-11-22 13:29
the image contains all relevant details

**Comment by robdekort** [comment] 2023-11-22 13:31
What is relevant is up for the maintainers of this repo to decide. For example I can see environment details important to determine in which version of the software this issue was reported.

**Comment by jackmcdade** [comment] 2023-11-22 13:32
@tobimori I'm sorry but it doesn't. We're constantly updating CSS and need to know for sure what exact version of Statamic you're running so we can try to recreate the issue. Because of the volume of requests that come our way we really need that little extra bit of effort on your part so our progress doesn't slow to a crawl trying to recreate issues that no longer exist.

**Comment by robdekort** [comment] 2023-11-22 13:33
That being said: if you do open up a new issue, I noticed the indentation differs for sections in the tabs and in the sidebar. Might be worth mentioning.

**Comment by tobimori** [comment] 2023-11-22 13:36
The issue exists since v4, the only version supported right now.

**Comment by tobimori** [comment] 2023-11-22 13:57
I find it stupid to overaggresively close an issue when you could've just asked what version I'm talking about

**Comment by jackmcdade** [comment] 2023-11-22 13:58
What version of Statamic are you talking about?

**Comment by tobimori** [comment] 2023-11-22 14:00
Statamic v4.36.0

**Comment by jackmcdade** [comment] 2023-11-22 14:04
Great, thank you. I can only recreate this in the sidebar, like Rob mentioned. Is that the case for you too @tobimori? Everywhere else the alignment is spot on in both Chrome and Safari.

**Comment by tobimori** [comment] 2023-11-22 14:06
You're right, the screenshot is from a sidebar because I don't use headings in the main content. Sorry for not mentioning.

**Comment by jackmcdade** [comment] 2023-11-22 14:06
Now were getting somewhere. 👍

**Closed** 2023-11-22 14:20 UTC
Labels: ui
