### ISSUE TITLE
Updates section is blank

### ISSUE THREAD

**Issue by ottz0** [statamic/cms#9462] opened 2024-02-06 03:45 UTC
### Bug description

I'm trying to update statamic via local host but the section is blank. I know there are updates as my prod version has updates in this section but I don't have command line access to be able to update it.

### How to reproduce

I have tried composer dump-autoload and removed the cache but this area is still blank

![Uploading Screenshot 2024-02-06 at 2.45.19 pm.png…]()

### Environment

```yaml
Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.44.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by ottz0** [comment] 2024-02-06 03:46
![sc](https://github.com/statamic/cms/assets/7971800/60466d09-140b-43ab-bf9f-9e87fa803240)

**Comment by jackmcdade** [comment] 2024-02-06 11:15
Are there any JavaScript errors in the console?

**Comment by duncanmcclean** [comment] 2024-02-19 10:38
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic and we haven't had any reports of anyone else running into the same issue.

I'm going to close this issue now. However, if you're still experiencing this issue, it might be worth updating to the latest version and if that doesn't help, please leave a comment with any errors from your browser console or from the Laravel log file.

**Closed by duncanmcclean** 2024-02-19 10:38 UTC
Labels: can't recreate, needs more info
