### ISSUE TITLE
OG filename does not show when renaming asset

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#2525] opened 2020-09-24 07:41 UTC
## Bug Description

When renaming an asset the original filename does not appear in the Rename dialog.

## Extra Detail
<img width="665" alt="Screen Shot 2020-09-24 at 5 37 48 pm" src="https://user-images.githubusercontent.com/414211/94115303-e2131780-fe8c-11ea-9c13-0c0d0815d787.png">

## Environment

Statamic 3.0.12 Pro
Laravel 7.28.3
PHP 7.4.9
statamic/seo-pro 2.0.14

**Comment by jasonvarga** [comment] 2020-09-24 14:17
Duplicate of statamic/ideas#337

**Closed by jasonvarga** 2020-09-24 14:17 UTC
Labels: assets, ux
