### ISSUE TITLE
Using relate tag inside array throws error

### ISSUE THREAD

**Issue by PhilippeGauthier** [statamic/cms#1852] opened 2020-05-21 21:01 UTC
## Bug Description
Using a `relate` tag inside an array throws a `Call to a member function absoluteUrl() on null` error
## How to Reproduce
Using a grid with a taxonomy fieldtype inside would save data like so:
```
specs_grid:
  -
    info: Type
    details: Midcentury
    test_tax: 'tags::hard-work'
  -
    info: 'Key Features'
    details: 'Acid washed concrete'
    test_tax: 'categories::great-project'
```

Trying to view that data with something like: 
```        
{{ specs_grid }}
        <div class="border-b border-textColor py-2">
        <div class="font-medium">{{ relate:test_tax }}{{ title }}{{ /relate:test_tax }}</div>
        <div>{{ details }}</div>
        </div>
{{ /specs_grid }}
```
throws the error. If the `test_tax` field were outside of the array and it's own parent level field doing something like `{{ relate:test_tax }}{{ title }}{{ /relate:test_tax }}` outputs the expected `Hard Work` and `Great Project` data.

## Environment

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.45

**Install method (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit
- Existing Laravel app
- Other (please explain this magic!)

**Comment by jackmcdade** [comment] 2020-05-26 22:01
You should be able to just do `{{ test_tax }}{{ title }}{{ /text_tax }}`, no need for the relate tag.

**Comment by PhilippeGauthier** [comment] 2020-05-27 16:38
The creates the following error:

```
Facade\Ignition\Exceptions\ViewException
Call to a member function absoluteUrl() on null
```

**Comment by jackmcdade** [comment] 2020-08-07 13:55
This looks like a duplicate of #1825.

**Comment by jesseleite** [comment] 2020-08-10 16:31
Should be fixed.  Let us know if still an issue.

**Closed by jesseleite** 2020-08-10 16:31 UTC
Labels: duplicate
