### ISSUE TITLE
Bard list item styling is missing

### ISSUE THREAD

**Issue by mikemartin** [statamic/cms#1780] opened 2020-05-04 08:21 UTC
## Bug Description

It looks like the list item styling has been removed in the Bard fieldtype. 

## How to Reproduce

Add bulleted list or unordered list in Bard field.

## Extra Detail
<img width="885" alt="Screen Shot 2020-05-04 at 6 20 03 pm" src="https://user-images.githubusercontent.com/414211/80947684-0285fb00-8e34-11ea-97cb-9ce6060b1cbe.png">

## Environment

**Statamic version:** 3.0.0.-beta-27

**Comment by JonKaric** [comment] 2020-05-04 09:10
This is a duplicate of #1741

**Closed** 2020-05-04 14:00 UTC
Labels: duplicate
