### ISSUE TITLE
is_parent not working on "link" (redirect @child) collections

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/cms#2359] opened 2020-09-03 15:47 UTC
## Bug Description
When using "link" collections to redirect to first child, the is_parent variable is always false when building a navigation tree.

## How to Reproduce
1. In the "Pages" collection choose "Edit Collection", enable "Links" and save
2. Create a new entry in the "Pages" collection and choose the Blueprint "Link"
3. Set a title and select "First Child" as Redirect. Save.
4. Add a child entry using the Blueprint "Pages"
5. Create a navigation and add those two entries. The "Link" entry is the parent, the "Pages" entry the child. Save.
6. Now create a navigation tree in a template using the `nav` tag (use the "Multi-level Nav Example Recursion" from the docs).

is_parent is always false. Doing the same only with "Pages" Blueprints works.

## Environment

**Statamic version:** 3.0.3

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by FlorianMoser** [comment] 2020-09-03 16:46
The problem seems to be in the [comparison of the parent to the child URL](https://github.com/statamic/cms/blob/f8730ddb9d037ab6c54705955e67adf9d328fba6/src/Tags/Structure.php#L66).

The problem is that the "Link" entry inherits the URL of its first child, ie `/parent/firstchild`. It then always checks if `/parent/firstchild` is the ancestor of `/parent/anything`, which is never the case (apart from the grandchild `/parent/firstchild/grandchild`).

When comparing a "Link" parent, you should remove the last segment from the URL: `/parent/firstchild` should become `/parent` before being used in `URL::isAncestorOf()`.

**Comment by philipboomy** [comment] 2020-10-06 12:56
I can confirm this issue. Its causing problems with the "is_current" too - Not sure if thats intended - but parent is active when child is active. This causes issues with my breadcrumbs for example. I highlight current page.

**Comment by philipboomy** [comment] 2021-01-16 20:26
Still an issue

**Comment by AndreasSchantl** [comment] 2021-01-20 14:44
I've finished the PR and I am hoping for it to be merged soon! Give it a try. In my scenarios it works perfectly. 

As in the previous versions, it relies on the URLs only. That means, the entries need to follow a parent/child structure to work.

**Closed** 2021-04-13 18:54 UTC
Labels: bug, navigations
