### ISSUE TITLE
Validation list should auto complete

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#935] opened 2019-11-22 03:35 UTC
In the Blueprint field builder, under Validation there's a list where you enter the validation rule. When you type in there, it should auto-complete from the rules dropdown below it.

Super++ bonus points for pulling in any custom validations offered by installed addons.

**Comment by jasonvarga** [comment] 2019-11-22 04:11
Duplicate of #699

**Closed by jasonvarga** 2019-11-22 04:11 UTC
