### ISSUE TITLE
Title translations in vendor blade files clashes with name of translation files

### ISSUE THREAD

**Issue by manogi** [statamic/cms#9547] opened 2024-02-19 20:58 UTC
### Bug description

After the update to the newest version I saw this error when trying to open the Blueprints in the CMS:

`htmlspecialchars(): Argument #1 ($string) must be of type string, array given (View: /Users/myusername/Code/some-repo/vendor/statamic/cms/resources/views/blueprints/index.blade.php)`

I can tell you where it comes from: the index file is trying to translate the title of a global set (in my case "Shop"). But I have a translation file named here: `resources/lang/de/shop.php `. So the translation function returns the array from this file, not as actually wanted the string from a translation JSON file.

The only way around this for now is renaming my global sets.

I guess instead of just using the `_()` translation function, maybe a custom function is needed which checks first if an array is returned (or something along those lines).

### How to reproduce

Easy to reproduce:

1. Install a fresh empty Statamic site
2. create a Global Set named "Validation"
3. try to open the Blueprints page in the CMS

This now throws the error, as there is a language file in `lang/en/validation.php`

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.44.0
PHP Version: 8.3.3
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: prove-error.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 0
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.49.0 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by ryanmitchell** [comment] 2024-02-19 22:12
Duplicate of https://github.com/statamic/cms/issues/7672

**Comment by manogi** [comment] 2024-02-19 23:19
Ah ok - sorry, did not look thoroughly enough for existing issues.

**Closed** 2024-02-20 09:13 UTC
