### ISSUE TITLE
Parent field should not shown, when collection is ordered with max depth 1

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#2288] opened 2020-08-25 13:21 UTC
## Bug Description
When max depth is 1, there is not need to chose a parent, right? So the parent field should not be shown.

## How to Reproduce
- Collection => max depth 1
- Edit entry
## Environment

**Statamic version:** 3.0.0

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-08-25 13:48
Duplicate of #2012

**Closed by jasonvarga** 2020-08-25 13:48 UTC
