### ISSUE TITLE
entries_count shows unpublished entries?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/cms#4760] opened 2021-11-17 15:50 UTC
### Bug description

I've got 18 entries tagged as `women`, 17 are published.
![Screenshot 2021-11-17 at 15 33 19](https://user-images.githubusercontent.com/72254741/142231462-3cc53cc0-5508-4973-9308-660d3b8a5ea1.png)

Using this code to display terms with an entry count
```
 {{ taxonomy from="gender" }} 
        {{ if entries_count > 0 }}
            <li> 
                <a href="/{{ segment_1 }}{{ url }}">{{ title }} ({{ entries_count }})</a>
            </li>
        {{ /if }}     
    {{ /taxonomy }}
```

It shows the entry count for `women` as 18? It should read 17.
![Screenshot 2021-11-17 at 15 35 36](https://user-images.githubusercontent.com/72254741/142231568-d88df140-8237-45ab-8143-39db543ae106.png)
 

### How to reproduce

- Create a taxonomy called `gender`
- Create a collection
- Add a taxonomy terms, `men`, `women`
- Publish all but one entry
- Use the code above to list terms and entries count

### Versions

Statamic 3.2.21 Pro
Laravel 8.70.2
PHP 8.0.8
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment] 2021-11-17 15:51
Duplicate of #3539

**Comment by stephenmeehanuk** [comment] 2021-11-17 15:52
Whoops. Sorry I forgot I'd posted that!

Is there a fix on the horizon?

**Closed by jasonvarga** 2021-11-17 15:51 UTC
