### ISSUE TITLE
Update to v3.1.19 fails in post update script

### ISSUE THREAD

**Issue by marcusand** [statamic/cms#3960] opened 2021-07-06 19:38 UTC
## Bug Description

The post update script `Statamic\UpdateScripts\AddUniqueSlugValidation]` fails for me. 
I think it has to do with linked fields in the blueprint. For linked fields a string is getting stored in the blueprint `field: <fieldset>.<field>` instead of array. 

## How to Reproduce
- Create a blueprint with a link to a single field. Maybe it even has to be nested inside a replicator
- Update to v3.1.9 or execute the post install script. 

## Extra Detail
```
Running update script [Statamic\UpdateScripts\AddUniqueSlugValidation]
Unique slug validation added to the schleiermacher-translations collection's schleiermacher-translations blueprint.
Unique slug validation added to the schleiermacher-poems collection's schleiermacher-poems blueprint.

   TypeError 

  array_merge(): Argument #1 must be of type array, string given

  at vendor/statamic/cms/src/Fields/Blueprint.php:470
    466|         // Get existing field config.
    467|         $existingConfig = Arr::get($this->contents['sections'][$section]['fields'][$fieldKey], 'field', []);
    468| 
    469|         // Merge in new field config.
  > 470|         $this->contents['sections'][$section]['fields'][$fieldKey]['field'] = array_merge($existingConfig, $config);
    471| 
    472|         return $this->resetFieldsCache();
    473|     }
    474| 

      +28 vendor frames 
  29  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan statamic:install --ansi handling the post-autoload-dump event returned with error code 1
```

## Environment

Statamic 3.1.27 Pro
Laravel 7.30.4
PHP 8.0.7
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2021-07-06 19:40
Duplicate of #3856

**Closed by jasonvarga** 2021-07-06 19:40 UTC

**Comment by marcusand** [comment] 2021-07-06 19:48
A thanks, did not see that. So I understand, its no big problem that it fails, but I think anyways that should be fix somehow or a lot more people will wonder and will be very annoyed by that.

**Comment by jasonvarga** [comment] 2021-07-06 19:49
Can you confirm - is your `slug` field imported into your blueprint?

**Comment by marcusand** [comment] 2021-07-06 19:51
Yes I have in some blueprints the `slug` field imported from a fieldset. But not only `slug` field. Can't say if it fails exactly there.
