### ISSUE TITLE
Live Preview Renders 404 Page for Drafts/Posts Scheduled in the Future

### ISSUE THREAD

**Issue by ramimassoud** [statamic/cms#3113] opened 2021-01-16 20:17 UTC
## Bug Description
If a post is in the draft state or published and scheduled for a future date, then Live Preview renders the 404 error page instead of the post.
## How to Reproduce
1. Set future posts to be private
2. Create a new post in a collection, saved or unsaved, published or draft
3. Change date to the future
4. Click "Live Preview"
5. Live preview page will render, but instead of the post, you'll see the 404 page

Looking in the network tab, Live Preview is still fetching `cp/collections/articles/entries/<uuid>/<slug>/preview`
## Extra Detail

`content/collections/articles.yaml`
```yaml
title: Articles
template: articles.show
layout: layout
mount: <UUID>
taxonomies:
  - topics
revisions: false
route: '{year}/{month}/{day}/{slug}'
date: true
sort_dir: desc
default_status: draft
date_behavior:
  past: public
  future: private
```

## Environment

```
Statamic 3.0.38 Pro
Laravel 8.21.0
PHP 7.4.13
No addons installed
```

**Install method:**
- Starter kit

**Comment by ericlbarnes** [comment] 2021-02-10 03:57
I can confirm. I do think I found the culprit and it's related to the collection future date settings. 

<img width="498" alt="image" src="https://user-images.githubusercontent.com/116662/107462421-16306180-6b2a-11eb-8894-2e42e6029376.png">

If this is set to private, then it throws a 404 on future dated saved entries. Moving to unlisted shows the preview.

**Comment by duncanmcclean** [comment] 2021-02-25 00:18
For reference: looks like something would need to be updated here in order to support drafts..  https://github.com/statamic/cms/blob/21da308840674cc61c40b1e8630832ba4e11a49e/src/Http/Responses/DataResponse.php#L109-L124

**Closed** 2021-04-15 16:24 UTC
Labels: live preview
