### ISSUE TITLE
Root path issues with S3 filesystem driver

### ISSUE THREAD

**Issue by bryantgillespie** [statamic/cms#5622] opened 2022-03-23 13:59 UTC
## Description
Hi gents,

I've got the S3 driver setup and working ok with the bucket from S3. I'm trying to set a root folder within the bucket so that my client doesn't see or access the other folders within the bucket, but everytime I try to set the root I get an error.

![ScreenShot 2022-03-23 at 09 57 53@2x](https://user-images.githubusercontent.com/23302570/159716509-d6d702b8-e401-4dca-8a5c-714b2b58724a.png)

![ScreenShot 2022-03-23 at 09 57 05@2x](https://user-images.githubusercontent.com/23302570/159716301-ebb846bc-20b4-4a7e-9248-68135f43fb45.png)

`[13:52:10] LOG.error: Undefined array key "dirname" {"userId":"f8a63412-ece2-4050-931f-2aa0992f1845","exception":{}}`

## Screencast
[2022-03-23-BUG-S3 Driver > Root - Watch Video](https://www.loom.com/share/c1684943367e44feb6790f38727ebe66)

### How to reproduce

Configure the S3 driver for an asset container and then try to add a `root` path.

```
  'assets' => [
            'driver' => 's3',
            'root' => 'assets/', // <- issue is here
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'cache' => true,
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'visibility' => 'public',
        ],

```

### Versions

Statamic 3.3.2 Pro
Laravel 9.5.1
PHP 8.0.15

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment] 2022-03-23 14:00
Duplicate of #5535

**Closed by jasonvarga** 2022-03-23 14:00 UTC
