### ISSUE TITLE
New empty asset folders disappear from the UI when stache watcher is disabled

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#4235] opened 2021-09-08 15:49 UTC
## Bug Description

When the stache watcher is disabled and you create a new empty asset folder the folder disappears from the UI if you refresh or leave and come back. The folder is still on the file system however, it just doesn't appear in the UI. You get a "Directory already exists." error if you try to create it again.

As far as I can tell this does not happen with folders that had something in and are later emptied, only folders that never had anything in. This also only seems to happen when the stache watcher is disabled.

## How to Reproduce

1. Disable the stache watcher
2. Go to a local asset container (I've not tested with remote asset containers)
3. Create a new folder
4. Refresh the page
5. The folder has disappeared

If you clear the application cache the missing folder will reappear, however if you then repeat the process the same thing happens again.

## Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.21
doublethreedigital/duplicator 1.3.4

**Comment by jasonvarga** [comment] 2021-09-08 15:56
Duplicate of #3722 and it looks like #4176 is attempting to fix it.

**Closed by jasonvarga** 2021-09-08 15:56 UTC
