### ISSUE TITLE
Cannot localize dynamic form fields in CP

### ISSUE THREAD

**Issue by SimonMauvaisGarcons** [statamic/cms#3082] opened 2021-01-07 13:55 UTC
I'm using the form [dynamic rendering option](https://statamic.dev/tags/form-create#dynamic-rendering) to display my fields on the page.

There is currently no option to localize the fields name inside the form blueprint. 
I have a multisite setup with (English, French, Spanish).
Although the blueprint has the localize button, there's no way to set the fields by site.

A working solution will be to use the {{ handle }} tag mix with the {{ trans:... }} tag. We can manually edit the translation file. 
```
{{ fields }}
    <input type="{{ input_type }}" name="{{ trans:field.handle }}" value="{{ old }}">
{{ /fields }}
```
This is buggy solution and not very dynamic.  But it can work for simple form with data that wont change over time.

### Environment

- Statamic 3.0.37 Pro
- Laravel  8.0
- PHP 7.3.*
- No addons installed

**Comment by jasonvarga** [comment] 2021-01-07 14:31
Duplicate of statamic/ideas#50

**Closed by jasonvarga** 2021-01-07 14:31 UTC
