### ISSUE TITLE
3.1.15 : cannot add any Bard set anymore

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/cms#3749] opened 2021-05-20 21:50 UTC
## Bug Description
I cannot add any Bard set anymore when creating or editing an entry which has a Bard fieldtype. When clicking on the "+" button and then selecting the Bard set, the set is not displayed.
I have been trying with both Safari and Chrome. It was OK in 3.1.14 (I was checking the changes made to the translations)

## Extra Detail

![Capture d’écran 2021-05-20 à 23 51 42](https://user-images.githubusercontent.com/1823359/119053493-6c812c00-b9c6-11eb-8c35-ca132045fe64.png)

## Environment
Statamic 3.1.15 Pro
Laravel 7.30.4
PHP 7.4.2
statamic/ssg 0.4.0

**Install method (choose one):**
- upgrade from 3.1.14

**Comment by ebeauchamps** [comment] 2021-05-20 22:01
Related: existing Bard set are now outputting unformatted code instead of expected output.

Example: "I had a really good idea but got sidetracked and forgot it." entry from the blog starter kit has a code example for which I now get:

![Capture d’écran 2021-05-21 à 00 01 12](https://user-images.githubusercontent.com/1823359/119054310-b4ed1980-b9c7-11eb-9191-b062c0c2c9e9.png)

**Comment by jasonvarga** [comment] 2021-05-20 23:07
Duplicate of #3750

**Closed by jasonvarga** 2021-05-20 23:07 UTC
