### ISSUE TITLE
3.2 Renaming an asset removes (or detaches) meta information

### ISSUE THREAD

**Issue by robdekort** [statamic/cms#4139] opened 2021-08-18 09:48 UTC
## Bug Description
Rename an asset.
Lose meta data (alt / focus)

## How to Reproduce
Add an asset with meta data (alt/focus)
Rename an asset
Be sad

## Environment
Statamic 3.2.0-beta.1 Pro
Laravel 8.55.0
PHP 7.4.13
No addons installed

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment] 2021-08-18 18:57
This is also an issue on 3.1, and duplicate of #3896 

Thanks again for pointing it out.

**Closed by jasonvarga** 2021-08-18 18:57 UTC
Labels: bug, assets
