### ISSUE TITLE
Sidebar buttons do not have enough space in translated control panel

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#1828] opened 2020-05-14 11:47 UTC
<img width="323" alt="Screenshot 2020-05-14 at 13 43 39" src="https://user-images.githubusercontent.com/38906163/81930739-45409380-95e9-11ea-8391-daa12229aabb.png">

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.3

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment] 2020-05-26 21:56
Duplicate of #1463.

**Closed by jackmcdade** 2020-05-26 21:56 UTC
