### ISSUE TITLE
Should be able to set protection via Route::statamic()

### ISSUE THREAD

**Issue by jackmcdade** [statamic/cms#2871] opened 2020-11-19 15:09 UTC
## Bug Description

You should be able to pass a `protect` var into a Statamic route and have it behave just like an entry. Right now nothing happens because all of the Protectable logic is only attached to Entries.

```php
Route::statamic('/secret', 'default', [
    'title' => 'Secret Informations',
    'protect' => 'logged_in'
]);
```

**Comment by damcclean** [comment] 2020-11-19 15:15
Duplicate of statamic/ideas#331.

**Comment by jackmcdade** [comment] 2020-11-19 15:16
Sorry, overreacted. I'm not used to having someone else close my issues when I decide it's time to work on them. 😊  I moved the other one into this repo.

**Closed** 2020-11-19 15:16 UTC
Labels: duplicate

**Comment by damcclean** [comment] 2020-11-19 15:17
No problem Jack!
