### ISSUE TITLE
Bard crashed with sets that have entries fields

### ISSUE THREAD

**Issue by stvnthomas** [statamic/cms#2810] opened 2020-11-05 19:36 UTC
## Bug Description

The control panel/browser tab crashes when a Bard has a set that references an entires fieldtype.

## How to Reproduce

Create a Bard field and add a set that contains an Entries fieldtype. Go to whereever that Bard field is used and use the Entries set. The browser console will immediately complain `Type error: n is undefined`. Save the page. Anytime to you go to edit the page it'll crash.

## Extra Detail

<img width="649" alt="Screen Shot 2020-11-05 at 11 30 09" src="https://user-images.githubusercontent.com/2236267/98287980-ff8ed300-1f5a-11eb-9571-4b54dfee8ebe.png">

<img width="950" alt="Screen Shot 2020-11-05 at 11 31 45" src="https://user-images.githubusercontent.com/2236267/98288027-10d7df80-1f5b-11eb-95bb-731e31c96023.png">

<img width="994" alt="Screen Shot 2020-11-05 at 11 34 17" src="https://user-images.githubusercontent.com/2236267/98288031-133a3980-1f5b-11eb-96ac-969144e4729c.png">

## Environment

Statamic 3.0.24 Solo
Laravel 8.13.0
PHP 7.4.2
No addons installed

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2020-11-05 21:39
Sounds like a duplicate of #2805

**Closed by jasonvarga** 2020-11-05 21:39 UTC
