### ISSUE TITLE
Slug names are only allowed to be unique

### ISSUE THREAD

**Issue by felixstoessel** [statamic/cms#2633] opened 2020-10-11 17:15 UTC
##  Bug Description
When a slug named `contact` and an URI of `/contact`, you can not have another page like `/foobar/contact`.

In a modern CMS, this shouldn't be a restriction.

## Environment
**Statamic version:** 3

**Comment by jasonvarga** [comment] 2020-10-13 14:44
Duplicate of #714

**Closed by jasonvarga** 2020-10-13 14:44 UTC
Labels: enhancement
