### ISSUE TITLE
Empty taxonomy leaves no output in collection tag pair

### ISSUE THREAD

**Issue by axelferdinand** [statamic/cms#2454] opened 2020-09-17 14:54 UTC
## Bug Description
In v2, you can leave a taxonomy empty in a collection tag pair, and get _all the results_. Meaning, this will output all the entries: 

```
{{ collection from="{mount}" taxonomy:brand="" }}
{{ title }}
{{ /collection }}
```

But in v3, the collection tag pair will show _no results_ if you leave a taxonomy empty, like in the example above. That means that this approach will no longer work: 

```
{{ collection from="{mount}" taxonomy:brand="{ get:brand }" }}
              {{ title }}
              {{ /collection }}
```

because when no filters are added to the URL as parameters, the output of the collection tag pair is empty – when the desired effect is to show all entries, like in v2.

## How to Reproduce
1. Create some taxonomies ("brand")
2. Create some posts and connect them to one or more of the brand tags

## Environment

Statamic 3.0.9 Pro
Laravel 7.26.1
PHP 7.4.6
statamic/migrator dev-master
statamic/ssg 0.2.0

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment] 2020-09-17 14:57
Thanks for the issue, but this is a duplicate of #2293

**Closed by jasonvarga** 2020-09-17 14:57 UTC
Labels: taxonomies

**Comment by jasonvarga** [comment] 2020-09-17 15:00
Duplicate of #2293
