### ISSUE TITLE
Sets can't be given a separate handle name

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/cms#1781] opened 2020-05-04 12:56 UTC
## Bug Description
In V2 it was possible to give sets its own variable/handle name. I am missing this option in V3.

## How to Reproduce
Create a new Bard or Replicator Field and try giving sets a handle name, right now, the display name is being converted to a handle name.

## Extra Detail
I have no way to declare a separate display name and handle name
![image](https://user-images.githubusercontent.com/9936988/80967345-8204d180-8e16-11ea-9b86-25d9d439539e.png)

## Environment
Laravel Valet

**Statamic version:** 3.0.0.-beta-27

**PHP version:** 7.4

**Install method:**
- Fresh install from `statamic/statamic`

**Comment by jackmcdade** [comment] 2020-05-04 13:44
Thanks for the report - though it _is_ a duplicate of #1667. :)

**Closed by jackmcdade** 2020-05-04 13:44 UTC
