### ISSUE TITLE
Beta 20: UI bug for collections with max_depth: 1

### ISSUE THREAD

**Issue by taylorcammack** [statamic/cms#1547] opened 2020-03-26 15:22 UTC
![Screen Shot 2020-03-26 at 10 19 31 AM](https://user-images.githubusercontent.com/2514935/77663828-7f77a800-6f4b-11ea-966f-ca0463a23cf6.png)

**Comment by jasonvarga** [comment] 2020-03-26 16:18
Duplicate of #1535

**Closed by jasonvarga** 2020-03-26 16:18 UTC
