### ISSUE TITLE
Can't exclude page from nav

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2314] opened 2020-08-28 12:22 UTC
## Bug Description
I'm trying to exclude a page from a nav like this `{{ nav exclude="imprint" }}`. This doesn't work though. 

## Extra Detail
I'm on a multi-site setup.

## Environment
Statamic 3.0.2 Pro
Laravel 7.26.1
PHP 7.4.9
aerni/imagekit 2.2.0

**Comment by jasonvarga** [comment] 2020-09-01 23:49
Duplicate of #2286

**Closed by jasonvarga** 2020-09-01 23:49 UTC
