### ISSUE TITLE
assets validation fails when using s3

### ISSUE THREAD

**Issue by krokusmoen** [statamic/cms#10859] opened 2024-09-29 18:31 UTC
After recent update I can't upload to my s3 in my Bard.

It works manually directly in assets, but not in creating an entry in any collection.

![image](https://github.com/user-attachments/assets/7022c5ea-74f7-4f00-9665-6231c3a9ca58)

**Comment by ryanmitchell** [comment] 2024-09-29 18:42
Duplicate of https://github.com/statamic/cms/issues/10856 ?

**Comment by krokusmoen** [comment] 2024-09-29 18:44
Ah, yes. Same issue, @ryanmitchell

**Comment by duncanmcclean** [comment] 2024-09-30 12:09
Closing in favour of #10856.

**Closed by duncanmcclean** 2024-09-30 12:09 UTC
Labels: assets
