### ISSUE TITLE
Datepicker with required time, doesn't store time when entry is being created

### ISSUE THREAD

**Issue by jbrhel** [statamic/cms#4067] opened 2021-07-29 19:45 UTC
## Bug Description
When creating a new entry with Date field type (time enabled and required) default time is not stored even though is displayed.

## How to Reproduce

1. Having a blueprint that contains Date fieldtype (time enabled and required) 
2. Create new entry (time is propelly pre populated by current timeú
3. Do not manually change time (leave curent pre populated time)
4. Store entry
5. Time is no part of date

## Extra Detail

- It's happening only when creating a new item. Saving an existing item works as expected.
- Tested on Chrome 92.0.4515.107 / Mac OS Big Sur

## Environment

Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 7.4.19

**Install method (choose one):**
- Fresh install from `statamic/statamic`

![Create_Entry_‹_Články_‹_Collections_‹_Statamic](https://user-images.githubusercontent.com/1133430/127581768-36233d0d-2596-40f5-bdd2-9d78c441694e.jpg)

**Comment by duncanmcclean** [comment] 2021-07-31 08:26
Can reproduce. Only seems to happen on creation of an entry.

**Comment by arthurperton** [comment] 2022-09-07 08:35
This issue has been fixed since it was reported. Works correctly in current version, v3.3.34. It was probably fixed in #3959. Closing as completed!

**Closed by arthurperton** 2022-09-07 08:35 UTC
Labels: bug, fieldtypes
