### ISSUE TITLE
Conditions ignored within grid

### ISSUE THREAD

**Issue by webographen** [statamic/cms#2556] opened 2020-09-29 10:52 UTC
I have created a fieldset ('card') with a whole bunch of conditional fields (all simple checks depending on one select). If I add an element of this type to a bard field, everything works great and I only see the fields I should be depending on my input.

In another fieldset ('cardlist') I am using a grid to allow the user to add multiple elements of 'card'. In this case the conditions are simply ignored, I'm always shown all fields and therefore prompted to fill out all required fields even if they don't apply.

**Comment by damcclean** [comment] 2020-09-29 10:59
Correct me if I'm wrong. I think it's a duplicate of #2289.

**Closed by damcclean** 2020-09-29 10:59 UTC
