### ISSUE TITLE
Taxonomy list when tagging collection doesn't show all tags

### ISSUE THREAD

**Issue by padders** [statamic/cms#2094] opened 2020-07-17 13:08 UTC
#1740  Bug Description
We have a taxonomy called 'topics' which has over 30 topics in (we realise that's a lot and some of that is just testing... I'm asking them to streamline). When we go into our article collection and list topics, it only comes back with the first 15 of them. Is there a limit in the config somewhere?

Here's a screenshot of our taxonomy

![Screenshot 2020-07-17 at 14 04 40](https://user-images.githubusercontent.com/15945371/87789192-8b5ae300-c836-11ea-87fc-71a5f9b528e3.png)

Here's the number that we can select from, it only gets to Marketing

![Screenshot 2020-07-17 at 14 06 46](https://user-images.githubusercontent.com/15945371/87789321-c3fabc80-c836-11ea-8611-ee077f56d390.png)

## Environment

**Statamic version:** v3.0.0-beta.37

**PHP version:** 7.4.4

**Install method (choose one):**
- Starter kit - cool writings

**Comment by jonassiewertsen** [comment] 2020-07-17 14:27
You‘re right!

Its a duplicate of https://github.com/statamic/cms/issues/1727

**Comment by padders** [comment] 2020-07-17 14:38
Ah sorry, I did do a search but couldn't spot it!

Hope it's sorted soon :)

**Comment by jonassiewertsen** [comment] 2020-07-17 15:30
Don't worry. You can quickly overlook related issues.

**Closed** 2020-09-22 19:54 UTC
