### ISSUE TITLE
Blade @nocache recursive dependency error when a global set is in view context

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#6924] opened 2022-10-20 09:17 UTC
### Bug description

If you use the `@nocache` directive while you have a global set in the view context (`$__data` array) it errors with:

```
Nesting level too deep - recursive dependency?
vendor/statamic/cms/src/StaticCaching/NoCache/Region.php: 55
```

This happens with all static caching strategies including null. This happens even if the global set is empty.

### How to reproduce

Create a blade template that uses `@nocache` while you have a global set in the view context:

```blade
@php
$__data['settings'] = Statamic\Facades\GlobalSet::find('settings')->inCurrentSite();
@endphp
@nocache('test')
```

Obviously you wouldn't normally set `$__data` directly, but this situation can easily occur if you've used a global set further up the view hierachy or added with `View::share()`.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.36.3
PHP Version: 8.1.10
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: sandbox-issue.test
Maintenance Mode: OFF

Statamic
Addons: 1
Antlers: runtime
Version: 3.3.47 PRO
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by jacksleight** [comment] 2022-10-20 13:27
A little more on this. I noticed this line:

https://github.com/jacksleight/statamic-cms/blob/98b52924e6ff6499e987860ce31ff69ca6689fc4/src/StaticCaching/NoCache/Region.php#L47

Is checking whether the key is an object, but keys cant be objects. So seems like that might be a mistake? Changing that to `is_object($aValue)` fixes this error but then the tests start failing, so I'm not really sure!

**Comment by godismyjudge95** [comment] 2022-11-11 00:22
I think I just ran into this issue but in Antlers...  Seems to show up most often when I try to add the `nocache` flag to a layout file.  I can spin up a test repo to see if the fix above resolves it.

**Comment by jacksleight** [comment] 2022-11-11 08:35
Yeah I'm not too sure about that fix. It appears to work but it breaks the tests. It might just be avoiding the problem rather than fixing the root issue.

**Comment by jhhazelaar** [comment] 2023-03-31 09:24
I ran into this issue today. Any updates on this issue? Can I helpt to solve something?

**Comment by jacksleight** [comment] 2023-03-31 11:38
@jhhazelaar My current workaround is to override the context with a blank array, by doing this:

```blade
@nocache('my-view', [], [])
```

If you need something from the context in your partial you could pass it through manually.

**Comment by jhhazelaar** [comment] 2023-03-31 12:21
Great thank you! This works.

This morning I spent the hole morning testing to create a workaround. My work around was to load a svg direct en niet with a blade component. The blade component was part of a navigation child element. After the navigation the nocache tag is used.

When I put the nocache tag above the hole navigation it also worked. Is it something to do with blade components?

**Comment by jacksleight** [comment] 2023-03-31 13:11
It seems to happen when there's any object in context that contains recursive references.

I mainly experience it when using global sets, but yeah i have run into with Blade components too. The PHP code that gets generated for a component leaves some variables behind, and I think one of these is an object with recursive references. Which would explain why it works before a component but not after.

**Comment by duncanmcclean** [comment] 2024-01-29 17:07
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. 

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2024-01-29 17:07 UTC
Labels: caching, blade, nocache
