### ISSUE TITLE
Deleting a user group results in error Call to a member function handle() on null

### ISSUE THREAD

**Issue by OleksiiBrylin** [statamic/cms#6407] opened 2022-08-01 08:37 UTC
### Bug description

After removing a group with users I get Call to a member function handle() on null error on users page in CP.
NOTE: users stored in DB

### How to reproduce

I created a Permission
I created a User to which I assigned this Group
I deleted the Group: OK
I clicked on Users in the sidebar: I got a debug bar message Call to a member function handle() on null
Shouldn't it be possible to access users related to a deleted group?

### Environment

```yaml
Users stored in DB
Statamic 3.3.24 Pro
Laravel 8.83.12
PHP 8.1.5
appswithlove/user-manager dev-main
statamic/seo-pro 3.1.0
```

### Installation

Starter Kit using via CLI

### Additional details

This issue was before https://github.com/statamic/cms/issues/1064

**Comment by joshuablum** [comment] 2022-09-19 14:00
Closing this since it's a duplicate of #6192.

But thanks for reporting it! 🙏

**Closed by joshuablum** 2022-09-19 14:00 UTC
