### ISSUE TITLE
Cache tag with scope "site" does not work well with multi site setup

### ISSUE THREAD

**Issue by MariusSpring** [statamic/cms#6241] opened 2022-06-22 17:47 UTC
### Bug description

Hi!

The default scope for the `{{ cache }}` tag is "site". I expect this to cache each site in a multi site setup seperately. Instead, what happens in a multi site setup, is that it caches the first site visited after a cache bust and shows that on all the sites. 

This works extremely poorly where multi site feature is used for translating content, as it will for example show English (/en) content on a German (/de) site.

I believe a new scope should be introduced, "global", which behaves as "site" does today. And then the "site" scope, as suggested by its name, is actually site specific. In a single site setup, both scopes will practically behave no different, but in a multi site setup it will cache per site seperately.

### How to reproduce

1. Create Statamic site.
2. Setup multi site with "english" and "german" sites.
3. Use cache tag in template to cache some dynamic content.
4. Load english version of the page, then the german and see it display cached content from the english one.

### Versions

Statamic 3.3.16 Pro
Laravel 8.83.16
PHP 8.1.4
doublethreedigital/runway 2.3.9
spatie/statamic-health 1.0.0
statamic/collaboration 0.4.0

### Installation

Existing Laravel app

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment] 2022-06-22 19:55
Duplicate of #4127

**Closed by jasonvarga** 2022-06-22 19:55 UTC
Labels: caching
