### ISSUE TITLE
[Forms][Multi-site] Localization not working for form emails

### ISSUE THREAD

**Issue by piljac1** [statamic/cms#2632] opened 2020-10-11 17:08 UTC
## Bug Description
When using the `trans` tag in form settings (in my case, the email subject), the default locale is always used when sending the related email, regardless what site you're currently on.

## How to Reproduce
1. Create a form
1. Create a translation in 2 or more languages
1. Output the created translation in the "Subject" input (ex.: `{{ trans:frontend_forms.form_handle.subject }}`)
1. Make sure you have all email related fields set up
1. Go on the front-end, fill the form and submit it (repeat on 2 or more locales)
1. Look at the email subject (the default locale is always used)

## Environment

Statamic 3.0.14 Pro (multi-site)
Laravel 7.28.1
PHP 7.4.3
doublethreedigital/duplicator 1.1.1

**Install method (choose one):** Fresh install from `statamic/statamic`

**Comment by robdekort** [comment] 2020-10-12 08:02
Duplicate of #2386

**Closed by robdekort** 2020-10-12 08:02 UTC
