### ISSUE TITLE
Symfony package is overwriting Collator class

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/cms#3626] opened 2021-05-01 15:57 UTC
## Bug Description
If using the Symfony Intl Package (like the addon Butik does), an error will appear on the collection index page. 
The symfony package is kind of overwriting the default Collator class. 

![Screenshot 2021-05-01 at 17 48 47](https://user-images.githubusercontent.com/38906163/116787702-e8faac00-aaa5-11eb-9e34-694170499de1.png)

Link to the symfony package:
https://symfony.com/doc/current/components/intl.html

 ## Why is this happening

Instead of loading the default Collator package, the Symfony Collator::class will be loaded. 

This does lead to the error as posted above if having > 1 entries in a collection. 

## How to Reproduce

Use the Symfony Intl Package aside with Statamic or install Butik (which is using the Symfony Package).

**Statamic version:** 3.1.11
**Multi-Site:** Yes

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by MartinVandersteen** [comment] 2021-11-18 13:36
I'm having problems with this as well, did you manage to fix it ?

**Comment by duncanmcclean** [comment] 2024-01-10 11:44
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. After installing `symfon/intl`, I don't experience any errors on the collection index page.

It may be down to the fact the latest version of `symfony/intl` no longer includes a `Collator` class: https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Intl/Collator/Collator.php

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2024-01-10 11:44 UTC
Labels: custom
