### ISSUE TITLE
Search results tag using Blade doesnt work

### ISSUE THREAD

**Issue by DenyEs** [statamic/cms#6063] opened 2022-05-19 10:54 UTC
### Bug description

Submitting a search form and trying to loop over results using Blade throws an error, same issue as on this [https://github.com/statamic/cms/issues/5534](url) and [https://github.com/statamic/cms/pull/5599](url) ticket.

### How to reproduce

`@foreach(Statamic::tag('search:results') as $result)
            @dd($result)
        @endforeach`

### Versions

Statamic 3.3.12 Solo
Laravel 9.13.0
PHP 8.1.5
No addons installed

### Installation

Fresh statamic/statamic site via CLI

### Additional details

Using Blade as templating language

**Comment by duncanmcclean** [comment] 2023-11-20 21:38
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. I've copied your code into a Blade view and a `Result` object was returned - no error:

![CleanShot 2023-11-20 at 21 37 54](https://github.com/statamic/cms/assets/19637309/2855e637-b323-4187-9ed8-583ee96a8a5d)

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-11-20 21:38 UTC
Labels: search, blade
