### ISSUE TITLE
Error when deleting assets "foreach () argument must be of type array object, string given"

### ISSUE THREAD

**Issue by marflow** [statamic/cms#8114] opened 2023-05-11 09:21 UTC
### Bug description

When trying to delete or move one or several images (via checkboxes or dot dropdown option) I got an error `foreach () argument must be of type array object, string given`.

Likely related to https://github.com/statamic/cms/pull/7555, this does not seem an edge case however.

When trying bulk deletion with checkboxes the first image is deleted though. Same when delting a single assets. Reloading the list shows it is gone.

### How to reproduce

Navigate to Assets and delete assets from an assets list. Or click on nav option "move" to move assets to another folder 

### Environment

```yaml
Existing Statamic multisite, updated from 3.4 to 4.0, MacOS Ventura, DDEV.
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by geertjanknapen1** [comment] 2023-05-23 08:44
I can confirm this also happens on 3.4.7 and 4.0 for me as well on Linux.

The exact same error throws when moving an asset in CP. 
And I get a `Call to a member function filename() on null` when renaming the file.

The thing is, after pressing cancel and then reloading CP the actions have been performed. I don't know if you see that behaviour as well @marflow ?

**Comment by marflow** [comment] 2023-05-24 16:39
I don´t get the same message as you @geertjanknapen1 , but the action (renaming, deleting) is done nevertheless on one file. CP is updated with new filename after reload.

**Comment by duncanmcclean** [comment] 2023-09-13 21:45
Duplicate of #7547 - closing in favour of that issue.

**Closed by duncanmcclean** 2023-09-13 21:45 UTC
Labels: assets

**Comment by Swennet** [comment] 2023-09-19 12:05
Same issue here when renaming or deleting assets.
