### ISSUE TITLE
Remove Section Fieldtype from Columns

### ISSUE THREAD

**Issue by aerni** [statamic/cms#2117] opened 2020-07-21 19:52 UTC
## Bug Description
The `Section Fieldtype` is available as a column in the collection overview. This doesn't make sense, as it won't show anything. I suggest removing it from the columns.

## How to Reproduce
Add a `Section Fieldtype` to a blueprint of a collection and check the columns in the collection overview.

## Environment

**Statamic version:** 3.0.0.-beta-38

**PHP version:** 7.4.6

**Install method:** Upgrade from beta-37

**Comment by jasonvarga** [comment] 2020-07-22 18:16
You're right, it doesn't make sense. But in the mean time, you can just make it unlistable.

![image](https://user-images.githubusercontent.com/105211/88212816-dbb2b600-cc25-11ea-8056-a50288cd629a.png)

(or `listable: false` in the yaml)

**Comment by damcclean** [comment] 2020-08-04 20:28
Looks like a duplicate of #2013

**Comment by damcclean** [comment] 2020-09-14 22:15
I've submitted a pull request that should fix this bug: #2425.

**Closed** 2020-09-14 23:35 UTC
