### ISSUE TITLE
Entries fieldtype > modes select and typeahead are always blank

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/cms#8411] opened 2023-07-06 09:52 UTC
### Bug description

With the entries fieldtype, `mode: default` works as expected, `mode: typeahead` and `mode: select` always show no entries and the message "No options to choose from"

### How to reproduce

Make an entries fieldtype with either mode typeahead or select

### Environment

```yaml
latest v4
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by robdekort** [comment] 2023-07-06 09:53
Confirmed. Nasty one.

**Comment by robdekort** [comment] 2023-07-06 09:55
Caused by #8253

**Comment by duncanmcclean** [comment] 2023-07-06 09:56
I've marked this as `critical` as I've seen a few people report this issue recently (both [on Discord](https://discord.com/channels/489818810157891584/489819906540568593/1126448801964625971) and on [this PR](https://github.com/statamic/cms/pull/8253#issuecomment-1620521582)) and it seems pretty big (most people use the entries fieldtype on their site).

I *think* this bug was introduced in #8253.

**Closed** 2023-07-06 15:07 UTC
Labels: bug, critical, fieldtypes
