### ISSUE TITLE
Content API return null for Link fields, when selecting Entry

### ISSUE THREAD

**Issue by psyao** [statamic/cms#4525] opened 2021-10-19 13:58 UTC
### Bug description

When I try to add an entry Link (standalone or in a Replicator), it returns null. I am not absolutely sure about what the result should be, but it could be something like id, title and app_url.

### How to reproduce

- Create a collection
- Add a Link field to the blueprint
- Create an entry
- Make an API request

### Versions

Statamic 3.2.16 Pro / multisite enabled, content API enabled
Laravel 8.64.0
PHP 8.0.10
No addons installed

### Installation

Existing Laravel app

### Additional details

The blueprint
```yaml
title: Pages
sections:
  main:
    display: Principal
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: Titre
          instructions_position: above
          listable: true
          input_type: text
          antlers: false
          localizable: true
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
          display: Slug
          instructions_position: above
          listable: true
          generate: true
      -
        handle: header
        field:
          collapse: false
          max_sets: 1
          sets:
            hero:
              display: Hero
              fields:
                -
                  import: hero
            page_header:
              display: 'Page header'
              fields:
                -
                  import: page_header
          display: Header
          type: replicator
          icon: replicator
          localizable: true
          listable: hidden
          instructions_position: above
          validate:
            - required
      -
        handle: content
        field:
          collapse: false
          sets:
            call_to_action:
              display: 'Call to action'
              fields:
                -
                  import: call_to_action
            content:
              display: Content
              fields:
                -
                  import: content
            content_on_columns:
              display: 'Content on columns'
              fields:
                -
                  import: content_in_columns
            form:
              display: Form
              fields:
                -
                  import: form
            gallery:
              display: Gallery
              fields:
                -
                  import: gallery
            logo_grid:
              display: 'Logo grid'
              fields:
                -
                  import: logo_grid
            video:
              display: Video
              fields:
                -
                  import: video
          display: Content
          type: replicator
          icon: replicator
          localizable: true
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: teaser-image
        field:
          mode: list
          container: medias
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Teaser image'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          validate:
            - 'mimes:jpg,jpeg,png'
  seo:
    display: SEO
    fields:
      -
        import: seo
```

The stored data:
```markdown
---
id: 91940b4b-12a1-4bce-aaaf-ec34f8a9aaa1
blueprint: pages
title: 'My first page'
do_not_index: false
updated_by: 1
updated_at: 1634650701
header:
  -
    image: Capture-du-2021-04-12-11-35-15.png
    image_position: 'top center'
    type: hero
    enabled: true
content:
  -
    link: 'https://www.google.ch'
    image_mode: cover
    text_color: positive
    text_position: left
    background_color: '#2431BB'
    type: call_to_action
    enabled: true
    background_variant: false
  -
    center_title: true
    type: content
    enabled: true
    orientation: fullpage
    text_width: half
    background_variant: false
  -
    center_title: true
    columns:
      -
        type: column
        enabled: true
    number_of_columns: '2'
    type: content_on_columns
    enabled: true
    background_variant: false
  -
    center_title: true
    form: test
    type: form
    enabled: true
    background_variant: false
  -
    center_title: true
    assets:
      - Capture-du-2021-04-12-11-35-15.png
      - littoral.svg
    background_variant: false
    type: gallery
    enabled: true
  -
    center_title: true
    logos:
      -
        image: littoral.svg
        type: logo
        enabled: true
        link: 'entry::21007e32-3368-44ad-a519-683be349f6ea'
        is_external: true
    background_variant: false
    type: logo_grid
    enabled: true
  -
    center_title: true
    source: youtube
    youtube_id: 17AFseaBDgk
    poster: littoral.svg
    background_variant: true
    type: video
    enabled: true
---
```

The response:
```json
{
  "data": {
    "amp_url": null,
    "api_url": "http:\/\/localhost:5000\/api\/collections\/pages\/entries\/91940b4b-12a1-4bce-aaaf-ec34f8a9aaa1",
    "blueprint": {
      "handle": "pages",
      "title": "Pages"
    },
    "collection": {
      "id": null,
      "title": "Pages",
      "api_url": null
    },
    "content": [
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "link": "https:\/\/www.google.ch",
        "image": null,
        "image_mode": {
          "value": "cover",
          "label": "Cover",
          "key": "cover"
        },
        "text_color": {
          "value": "positive",
          "label": "Black",
          "key": "positive"
        },
        "text_position": {
          "value": "left",
          "label": "On the left",
          "key": "left"
        },
        "background_color": "#2431BB",
        "background_variant": false,
        "type": "call_to_action"
      },
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "center_title": true,
        "image": null,
        "text": null,
        "orientation": {
          "value": "fullpage",
          "label": "Image then text",
          "key": "fullpage"
        },
        "text_width": {
          "value": "half",
          "label": "Half the width",
          "key": "half"
        },
        "background_variant": false,
        "type": "content"
      },
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "center_title": true,
        "columns": [
          {
            "text": null,
            "type": "column"
          }
        ],
        "number_of_columns": {
          "value": "2",
          "label": null,
          "key": "2"
        },
        "background_variant": false,
        "type": "content_on_columns"
      },
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "center_title": true,
        "form": {
          "handle": "test",
          "title": "Test",
          "api_url": "http:\/\/localhost:5000\/api\/forms\/test"
        },
        "background_variant": false,
        "type": "form"
      },
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "center_title": true,
        "assets": [
          {
            "id": "medias::Capture-du-2021-04-12-11-35-15.png",
            "url": "http:\/\/localhost:5000\/storage\/Capture-du-2021-04-12-11-35-15.png",
            "permalink": "http:\/\/localhost:5000\/storage\/Capture-du-2021-04-12-11-35-15.png",
            "api_url": "http:\/\/localhost:5000\/api\/assets\/medias\/Capture-du-2021-04-12-11-35-15.png"
          },
          {
            "id": "medias::littoral.svg",
            "url": "http:\/\/localhost:5000\/storage\/littoral.svg",
            "permalink": "http:\/\/localhost:5000\/storage\/littoral.svg",
            "api_url": "http:\/\/localhost:5000\/api\/assets\/medias\/littoral.svg"
          }
        ],
        "background_variant": false,
        "type": "gallery"
      },
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "center_title": true,
        "logos": [
          {
            "image": {
              "id": "medias::littoral.svg",
              "url": "http:\/\/localhost:5000\/storage\/littoral.svg",
              "permalink": "http:\/\/localhost:5000\/storage\/littoral.svg",
              "api_url": "http:\/\/localhost:5000\/api\/assets\/medias\/littoral.svg"
            },
            "link": null,
            "is_external": true,
            "type": "logo"
          }
        ],
        "background_variant": false,
        "type": "logo_grid"
      },
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "center_title": true,
        "source": {
          "value": "youtube",
          "label": "Youtube",
          "key": "youtube"
        },
        "youtube_id": "17AFseaBDgk",
        "vimeo_id": null,
        "poster": {
          "id": "medias::littoral.svg",
          "url": "http:\/\/localhost:5000\/storage\/littoral.svg",
          "permalink": "http:\/\/localhost:5000\/storage\/littoral.svg",
          "api_url": "http:\/\/localhost:5000\/api\/assets\/medias\/littoral.svg"
        },
        "background_variant": true,
        "type": "video"
      }
    ],
    "date": "2021-10-19T13:38:21.000000Z",
    "do_not_index": false,
    "edit_url": "http:\/\/localhost:5000\/cp\/collections\/pages\/entries\/91940b4b-12a1-4bce-aaaf-ec34f8a9aaa1\/my-first-page",
    "header": [
      {
        "suptitle": null,
        "title": null,
        "subtitle": null,
        "buttons": [],
        "image": {
          "id": "medias::Capture-du-2021-04-12-11-35-15.png",
          "url": "http:\/\/localhost:5000\/storage\/Capture-du-2021-04-12-11-35-15.png",
          "permalink": "http:\/\/localhost:5000\/storage\/Capture-du-2021-04-12-11-35-15.png",
          "api_url": "http:\/\/localhost:5000\/api\/assets\/medias\/Capture-du-2021-04-12-11-35-15.png"
        },
        "image_position": {
          "value": "top center",
          "label": "Top center",
          "key": "top center"
        },
        "type": "hero"
      }
    ],
    "id": "91940b4b-12a1-4bce-aaaf-ec34f8a9aaa1",
    "image": null,
    "is_entry": true,
    "last_modified": "2021-10-19T13:38:21.000000Z",
    "link": null,
    "locale": "french",
    "meta_description": null,
    "meta_keywords": null,
    "meta_title": null,
    "mount": null,
    "order": null,
    "permalink": null,
    "private": false,
    "published": true,
    "slug": "my-first-page",
    "status": "published",
    "teaser-image": null,
    "title": "My first page",
    "updated_at": "2021-10-19T13:38:21.000000Z",
    "updated_by": {
      "id": 1,
      "name": "Jacome",
      "email": "jacome@bureauweb.ch",
      "api_url": "http:\/\/localhost:5000\/api\/users\/1"
    },
    "uri": null,
    "url": null
  }
}
```

**Comment by duncanmcclean** [comment] 2023-12-06 15:49
Hey 👋

I'm unable to reproduce this issue on the latest version of Statamic. The link URL is being output as expected. 

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed by duncanmcclean** 2023-12-06 15:49 UTC
Labels: api
