### ISSUE TITLE
Addon is not installed

### ISSUE THREAD

**Issue by yammycode** [statamic/cms#3770] opened 2021-05-25 14:15 UTC
## Bug Description
In the control panel, when you click on the install button, a black window is shown and that's it. Installation fails.

## How to Reproduce
It is new fresh installation

## Extra Detail
See img
https://prnt.sc/13ed4jo

## Environment
Windows 10, Laragon
Statamic 3.1.16 Solo
Laravel 8.42.1
PHP 7.4.14
No addons installed

**Comment by duncanmcclean** [comment] 2021-05-25 14:19
As a workaround, you should be able to install via the command line.

```
composer require edalzell/blade-directives
```

**Comment by jasonvarga** [comment] 2021-05-25 14:22
Duplicate of #1918

**Closed by jasonvarga** 2021-05-25 14:22 UTC
Labels: windows
