### ISSUE TITLE
Can't login to cp when setting statamic guard for cp users

### ISSUE THREAD

**Issue by edulazaro** [statamic/cms#5037] opened 2022-01-07 16:34 UTC
### Bug description

I move it here, as it seems to happen to more users.

The login box does nohing when trying to login. The password check seems to happen, as the login box only trembles with a wrong password. With a correct password, the page refreshes and nothing happens.

Have followed the steps here: https://statamic.dev/tips/using-an-independent-authentication-guard
Also explained here: https://statamic.com/forum/4942-existing-app-with-solo-user-but-multiple-users-in-db

The pro is enabled.

When creating the ser directly using the yaml file, the password gets encrypted and a user id is generated correctly, but can't still login.

No errors into the logs at all.

Thanks : )

### How to reproduce

Install statamic on an existing laravel 8 app and configure statamic guard for cp users.

**config/statamic/users.php**

```php
    'repository' => 'file',

    'repositories' => [

        'file' => [
            'driver' => 'file',
            'paths' => [
                'users' => base_path('users'),
                'roles' => resource_path('users/roles.yaml'),
                'groups' => resource_path('users/groups.yaml'),
            ],
        ],

        'eloquent' => [
            'driver' => 'eloquent',
        ],

    ],
    /* .. */.
    'guards' => [
        'cp' => 'statamic',
        'web' => 'web',
    ],
```
**config/auth.php**
```php
    'guards' => [
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    	'statamic' => [
          'driver' => 'session',
          'provider' => 'statamic',
    	]
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
       'statamic' => [
            'driver' => 'statamic',
        ],
    ],
```

**config/statamic/stache.php**

```
'stores' => [
       /*  ...  */
        'users' => [
            'class' => Stores\UsersStore::class,
            'directory' => base_path('users'),
        ],

]
```

### Versions

Laravel 8
Latest statamic 3 version

### Installation

Existing Laravel app

**Comment by jasonvarga** [comment] 2022-01-07 16:38
Can you provide a repo with this problem reproduced so we can investigate?

**Comment by edulazaro** [comment] 2022-01-07 17:30
> Can you provide a repo with this problem reproduced so we can investigate?

Yes; just a laravel + livewire fresh install + statamic, with the statamic guard

[https://github.com/edulazaro/larastatamic](https://github.com/edulazaro/larastatamic)

**Comment by stuartcusackie** [comment] 2022-09-06 14:23
Same trouble. Fresh Statamic install with statamic-cli. Then i followed this guide exactly:
https://statamic.dev/tips/using-an-independent-authentication-guard

I just opened [an issue](https://github.com/statamic/docs/issues/908) on Statamic docs about it

**Comment by duncanmcclean** [comment] 2024-01-17 12:06
This issue is relatively old now and I'm not able to reproduce this on a fresh site. 

We've recently updated our docs around [configuring independent auth guards](https://statamic.dev/tips/using-an-independent-authentication-guard), which adds some more clarity to some steps in the process.

I'm going to close this issue now. If anyone's still having issues, please open a new issue and we can take a look.

**Closed by duncanmcclean** 2024-01-17 12:06 UTC
