### ISSUE TITLE
Linked Fields and Fieldsets in the Blueprint editor have giant icons

### ISSUE THREAD

**Issue by martyf** [statamic/cms#4299] opened 2021-09-23 03:44 UTC
## Bug Description
When linking to a Field or Fieldset in a Blueprint, the icons are giant. See:
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/1491079/134451556-276f8777-7a76-422e-ac65-d56a29e7c178.png">

Link to a Field is a giant link. 
Link to a Fieldset is an even-bigger trash can.

## How to Reproduce
1. Install Statamic, no Starter Pack
2. Create a Fieldset - just a single Text Field will do
3. In your Blueprint, Link to the Field or Fieldset

## Environment
macOS 11.6, Apache 2.4.46.

**Browser specific behaviour:**
Firefox Developer Edition 93.0b7 (64 bit): Massive icons
Chrome 93.0.4577.82: Big "link" icon, missing trash icon
Safari: missing both icons

Statamic 3.2.6 Solo
Laravel 8.61.0
PHP 8.0.2
No addons installed

**Statamic version:** 3.2.6

**PHP version:** 8.0.2

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment] 2021-09-23 07:16
Have you tried a browser hard refresh?

Probably related to some icon stuff that was merged in #4285.

**Comment by martyf** [comment] 2021-09-23 07:17
Yeah I did - and I even did a clean Statamic install just to double check too. I think it has only started _after_ this update.

**Comment by duncanmcclean** [comment] 2021-09-23 07:17
Nevermind, this is a duplicate of #4297 which has been fixed & closed. The fix will be part of the next release.

**Closed by duncanmcclean** 2021-09-23 07:17 UTC

**Comment by martyf** [comment] 2021-09-23 07:18
I did a search but must have my long weekend hat on already as mustn't have included closed items. Duh. Thanks for following up Duncan.
