### ISSUE TITLE
Multi-Site not working / endless loading

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/cms#1237] opened 2020-01-20 16:32 UTC
Changing the site/language loads endless.

![statamic_lang](https://user-images.githubusercontent.com/3351449/72742836-d313f100-3baa-11ea-861b-980804d54741.gif)

**Comment by jasonvarga** [comment] 2020-01-20 16:34
Duplicate of #1094

**Closed by jasonvarga** 2020-01-20 16:34 UTC
