### ISSUE TITLE
Multisite please command throws an error 

### ISSUE THREAD

**Issue by radovanobal** [statamic/cms#2989] opened 2020-12-09 20:06 UTC
## Bug Description
The php please multisite threw error. It takes down the whole website, once you add a site to the sites.php config file, throwing the same error as below.

## How to Reproduce
Create a bunch of collections then run php please multisite. 

## Extra Detail

`[✓] Collection [events] updated.
[✓] Collection [festival] updated.

   ErrorException 

  Undefined offset: 1

  at vendor/statamic/cms/src/Stache/Stores/CollectionEntriesStore.php:103
     99▕         $collection = pathinfo($path, PATHINFO_DIRNAME);
    100▕         $collection = str_after($collection, $this->parent->directory());
    101▕ 
    102▕         if (Site::hasMultiple()) {
  ➜ 103▕             [$collection, $site] = explode('/', $collection);
    104▕         }
    105▕ 
    106▕         // Support entries within subdirectories at any level.
    107▕         if (Str::contains($collection, '/')) {

      +29 vendor frames 
  30  please:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

## Environment
Docker image php:7-fpm-alpine

Statamic 3.0.33 Pro
Laravel 8.18.1
PHP 7.4.11
No addons installed

- Fresh install from `statamic/statamic` with composer

**Comment by damcclean** [comment] 2020-12-09 22:03
Duplicate of #2802.

**Closed** 2020-12-09 22:03 UTC
