### ISSUE TITLE
Bard in bard image cuasing dirty state in revision

### ISSUE THREAD

**Issue by meandersen** [statamic/cms#9869] opened 2024-04-12 11:10 UTC
### Bug description

https://github.com/statamic/cms/assets/21035145/a14ce370-6240-4b3b-8a47-903ce7a85783

Having a bard in a bard with an inline image causes revisions to show that you always have an unsaved change and therefore you can't publish or make drafts.

### How to reproduce

1. Enable revisions for Statamic
2. Have a basic page with a bard field for content.
3. That bard field have a set.
4. The set have a bard field inside it, with the image button enabled.
5. Create a new basic page, insert the set and add the image.
6. You can save the page, but not publish the page

### Logs

```shell
It don't get logged
```

### Environment

```yaml
Statamic 4.47.0
Laravel Framework 10.48.7
PHP 8.1.26
postgres database
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

### Additional details

Have testet on 2 different Statamic setups both running the same version.

**Comment by duncanmcclean** [comment] 2024-04-12 11:13
This seems like a duplicate of #6340.

**Closed by duncanmcclean** 2024-04-12 11:13 UTC
Labels: bard
