### ISSUE TITLE
Collection separate routing gets stored in Yaml; but doesnt show up in CP.

### ISSUE THREAD

**Issue by vannut** [statamic/cms#3151] opened 2021-01-25 11:35 UTC
## Bug Description
We entring a different URL for each collection. The data does get saved to the .yaml but wont show in the CP.

## How to Reproduce
Create Collection.
Go to /cp/collections/{collection_name}/edit
Go to section "Routing & URLs
Select "Separate route for each site"
Fill out the url's for each site you defined.
Hit save & refresh the page: the inputs are blank. 

Go to `content/collection/{collection_name}.yaml` and see the different routes defined there.

## Extra Detail
The CP-section:
![Schermafbeelding 2021-01-25 om 12 32 17](https://user-images.githubusercontent.com/7419859/105700617-69d76400-5f09-11eb-9f6c-9a865156faa4.png)
The corresponding Yaml:
![Schermafbeelding 2021-01-25 om 12 32 21](https://user-images.githubusercontent.com/7419859/105700647-6fcd4500-5f09-11eb-8678-ff2df89a0e5c.png)

## Environment

Statamic 3.0.34 Pro
Laravel 8.18.1
PHP 7.4.5

**Install method (choose one):**
- Starter kit

**Comment by jasonvarga** [comment] 2021-01-25 17:08
Duplicate of #2447

**Closed by jasonvarga** 2021-01-25 17:08 UTC
Labels: multisite
