### ISSUE TITLE
Removing an Image and selecting a new one throws error (Cannot read property 'id' of undefined)

### ISSUE THREAD

**Issue by mkriegeskorte** [statamic/cms#1581] opened 2020-03-31 17:08 UTC
If I try to remove an previously selected Image on a page in order to select a new one, the asset viewer doesn't load and the Browser Console throws an error:

```
TypeError: Cannot read property 'id' of undefined
    at a.loadAssets (Browser.vue:440)
    at a.container (Browser.vue:386)
    at fn.run (vue.common.prod.js:6)
    at un (vue.common.prod.js:6)
    at Array.<anonymous> (vue.common.prod.js:6)
    at Ge (vue.common.prod.js:6)
```

**Steps to reproduce**
- Go on to a page with an Image
- Remove the image via the trash icon
- Click on "Browse" at the image field
- Error shows in Console

**Comment by sebabal** [comment] 2020-04-06 02:00
I am having the same issue.

I think this other issue #1523 is also related.

**Comment by jackmcdade** [comment] 2020-04-07 02:56
Yep, this is a duplicate of #1523. Hang in there!

**Closed by jackmcdade** 2020-04-07 02:56 UTC
Labels: bug, duplicate
