### ISSUE TITLE
Modifiers not working on dynamically called global collection

### ISSUE THREAD

**Issue by hmalaud** [statamic/cms#3724] opened 2021-05-17 14:03 UTC
## Bug Description
When accessing a global set dynamically (`my_global[var]`), adding a modifier causes the collection to output nothing.

## How to Reproduce

1. Create global set file. E.g. `dev.yaml`
```
title: Dev
data:
  full_images:
    -
      image_width: 1600
      media_query: '(orientation: landscape) and (min-width: 1600px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1920
      media_query: '(orientation: landscape) and (min-width: 1920px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1440
      media_query: '(orientation: landscape) and (min-width: 1440px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1280
      media_query: '(orientation: landscape) and (min-width: 1280px)'
      default_size: true
      type: size
      is_portrait: false
      enabled: true
    -
      image_width: 1152
      image_height: 2050
      media_query: '(orientation: portrait) and (min-width: 1152px)'
      default_size: false
      type: size
      is_portrait: false
      enabled: true
```
3. Create partial. E.g. `picture.antlers.html` 
``` 
   {{ dev:full_images where="default_size:1" }} // or sort/group_by/...
      Not dynamic, this shows in template
   {{ /dev:full_images }}

   {{ dev[gset] }}
      Dynamic, shows in template
   {{ /dev[gset] }}

   {{ dev[gset] where="default_size:1" }} // or sort/group_by/...
      Dynamic, this doesn't show in template
   {{ /dev[gset] }}
```
4. Call partial from template. E.g. `{{ partial:partials/picture gset="full_images" }}`

## Environment
**Statamic version:** 3.1.14
**PHP version:** 8.0.2
**Laravel version:** 8.41.0

**Install method:**
- Fresh install from `statamic/statamic` 
(Statamic's CLI (`statamic new ...`))

**Comment by duncanmcclean** [comment] 2021-05-17 21:10
Does it work if you try a `where` on a non-boolean value? 

If it does, probably just a duplicate of #2208 which you've already commented on?

**Comment by hmalaud** [comment] 2021-05-17 21:13
I think it's a different problem, coming from the use of `dev[gset]` instead of `dev:full_images ` (the latter works).

**Comment by duncanmcclean** [comment] 2021-05-17 21:19
Ah gotcha, that makes sense! 👍

**Comment by morhi** [comment] 2021-05-18 21:31
I added an PR! :)

**Closed** 2021-05-21 16:25 UTC
Labels: parser
