### ISSUE TITLE
command  make:addon broken

### ISSUE THREAD

**Issue by lotarbo** [statamic/cms#5136] opened 2022-01-26 15:46 UTC
### Bug description

i run `php please make:addon test/example-addon`  and have error
![image](https://user-images.githubusercontent.com/1766890/151195498-4e57d939-df21-4ba5-bc57-28112e39670d.png)

### How to reproduce

run `php please make:addon test/example-addon` 

### Logs

```shell
[2022-01-26 15:43:37] local.ERROR: Passed value cannot be an array {"exception":"[object] (InvalidArgumentException(code: 0): Passed value cannot be an array at /Users/some-work/vendor/statamic/stringy/src/Stringy.php:45)
[stacktrace]
#0 /Users/some-work/vendor/statamic/stringy/src/Stringy.php(73): Stringy\\Stringy->__construct(Array, NULL)
#1 /Users/some-work/vendor/statamic/stringy/src/StaticStringy.php(147): Stringy\\Stringy::create(Array, NULL)
#2 /Users/some-work/vendor/statamic/cms/src/Support/Str.php(264): Stringy\\StaticStringy::__callStatic('replace', Array)
#3 /Users/some-work/vendor/laravel/framework/src/Illuminate/Support/Str.php(840): Statamic\\Support\\Str::replace(Array, ' ', 'id')
#4 /Users/some-work/vendor/laravel/framework/src/Illuminate/Support/Str.php(171): Illuminate\\Support\\Str::studly('id')
#5 /Users/some-work/vendor/statamic/cms/src/Extend/Addon.php(183): Illuminate\\Support\\Str::camel('id')
#6 /Users/some-work/vendor/statamic/cms/src/Extend/AddonRepository.php(20): Statamic\\Extend\\Addon::makeFromPackage(Array)
#7 /Users/some-work/vendor/statamic/cms/src/Extend/AddonRepository.php(31): Statamic\\Extend\\AddonRepository->make(Array)
#8 [internal function]: Statamic\\Extend\\AddonRepository->Statamic\\Extend\\{closure}(Array, 'test/example-ad...')
#9 /Users/some-work/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#10 /Users/some-work/vendor/statamic/cms/src/Extend/AddonRepository.php(32): Illuminate\\Support\\Collection->map(Object(Closure))
#11 /Users/some-work/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\Extend\\AddonRepository->all()
#12 /Users/some-work/vendor/statamic/cms/src/Providers/AddonServiceProvider.php(438): Illuminate\\Support\\Facades\\Facade::__callStatic('all', Array)
#13 /Users/some-work/vendor/statamic/cms/src/Providers/AddonServiceProvider.php(426): Statamic\\Providers\\AddonServiceProvider->getAddonByServiceProvider()
#14 /Users/some-work/vendor/statamic/cms/src/Providers/AddonServiceProvider.php(45): Statamic\\Providers\\AddonServiceProvider->getAddon()
#15 /Users/some-work/vendor/statamic/cms/src/Statamic.php(310): Statamic\\Providers\\AddonServiceProvider->Statamic\\Providers\\{closure}()
#16 /Users/some-work/vendor/statamic/cms/src/Providers/AppServiceProvider.php(24): Statamic\\Statamic::runBootedCallbacks()
#17 /Users/some-work/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(967): Statamic\\Providers\\AppServiceProvider->Statamic\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application))
#18 /Users/some-work/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#19 /Users/some-work/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#20 /Users/some-work/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#21 /Users/some-work/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#22 /Users/some-work/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#23 /Users/some-work/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"}
[2022-01-26 15:43:37] local.ERROR: Composer Process: Using version dev-master for test/example-addon
./composer.json has been updated
Running composer update test/example-addon --with-dependencies
> Statamic\Console\Composer\Scripts::preUpdateCmd
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking test/example-addon (dev-master)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
- Installing test/example-addon (dev-master):
Symlinking from addons/test/example-addon
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
> @php artisan statamic:install --ansi
Script @php artisan statamic:install --ansi handling the post-autoload-dump event returned with error code 1
```

### Versions

Statamic 3.2.31 Pro
Laravel 8.81.0
PHP 8.1.1
No addons installed

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment] 2022-01-26 15:50
Please search for your error message before posting.

Duplicate of #5126, #5133

**Closed by jasonvarga** 2022-01-26 15:50 UTC
