### ISSUE TITLE
Frotnend form file mimes validation is broken

### ISSUE THREAD

**Issue by radovanobal** [statamic/cms#3219] opened 2021-02-09 18:06 UTC
## Bug Description
If a from has a asset upload defined and you set the mimes:jpg filter it will fail all file uploads regardles if they are of the type jpg

## How to Reproduce
- create a from in the cp
- add field with asset file upload
- set mimes:jpg under validation
- save
- go to fronted form
- attach a jpg file
- submit form

## Extra Detail
part of yaml:
```
        handle: photo
        field:
          mode: grid
          container: applications
          folder: photos
          restrict: true
          allow_uploads: true
          max_files: 1
          display: 'Vaša slika (jpg format) *'
          type: assets
          icon: assets
          listable: hidden
          validate:
            - required
            - 'mimes:jpg,jpeg,png'
          localizable: true
```

frontend:
```
                {{ form:online_prijava_za_volontere files="true" }}
                <h2 class="big mb-6">{{ form_title }}</h2>

                {{ if success }}
                <div class="bg-green-300 text-white p-2">
                    {{ success }}
                </div>
                {{ else }}

                    {{ fields }}
                    <div class="p-2 {{ fieldtype }}">
                        <label>{{ display }}</label>
                        <div class="w-full">{{ field }}</div>
                        {{ if error }}
                        <p class="text-gray-500">{{ error }}</p>
                        {{ /if }}
                    </div>
                    {{ /fields }}

                    {{ if errors }}
                    <div class="errors mt-8">
                        {{ errors }}
                            <div class="error">{{ value }}</div>
                        {{ /errors }}
                    </div>
                    {{ /if }}

                    <button type="submit" class="w-full mt-11">{{ trans key="Pošalji" }}</button>
                {{ /if }}

                <input type="text" name="honeypot" class="honeypot" />
                {{ /form:online_prijava_za_volontere }}
```

screen capture of the error thrown when form with jpg file is submited:
![Screenshot from 2021-02-09 19-04-44](https://user-images.githubusercontent.com/60649057/107407282-c346b200-6b09-11eb-87d2-da977e356943.png)

## Environment
Statamic version: 3.0.42 Pro
PHP version: 7.4.9
Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment] 2021-02-09 18:13
This issue is pretty much the same as #1956 but in a form instead. 

Essentially, the issue is that when you upload an image, technically it validates the filename rather than the contents of the file itself.

**Comment by radovanobal** [comment] 2021-02-09 19:17
> This issue is pretty much the same as #1956 but in a form instead.
> 
> Essentially, the issue is that when you upload an image, technically it validates the filename rather than the contents of the file itself.

the issue in the cp is not entirely the same as this. Since in the CP it's also an issue where if the image is already saved it will validate it's id against the mime instead of it's filename or file content. Or that's what I gather from what's going on there.

**Comment by duncanmcclean** [comment] 2021-02-09 19:34
Yeah, I believe it works the same way under the hood. They're both just using the asset fieldtype. 

(Bearing in mind, I've not tested it yet to confirm but I'm pretty confident it's the same)

**Comment by radovanobal** [comment] 2021-02-09 19:41
are there any suggested workarounds for this? Or should I route the submission to a custom controller?

**Comment by duncanmcclean** [comment] 2021-02-09 19:42
I've not heard of any workarounds for it. Using a custom controller may be the best way to go about doing it.

I'm going to close this issue now as it's a duplicate of the issue I mentioned earlier. 😅

**Closed by duncanmcclean** 2021-02-09 19:42 UTC
Labels: assets
