### ISSUE TITLE
`site:clear` uses old config defaults

### ISSUE THREAD

**Issue by edalzell** [statamic/cms#2399] opened 2020-09-10 17:38 UTC
## Bug Description

If you create a new Statamic site, then run `php please site:clear` you will find it revert several config files (git, user, stache) back to old (pre release) versions.

## How to Reproduce

1. create Statamic site
2. commit site to git
3. run `php please clear:site`
4. Note the config file changes.

**Statamic version:** 3.0.7

**Comment by jasonvarga** [comment] 2020-09-10 17:39
Duplicate of #1880

**Closed** 2020-09-10 17:39 UTC

**Comment by jasonvarga** [comment] 2020-09-10 17:50
I mean #2305
