### ISSUE TITLE
Can’t sort alphabetically by Taxonomy in control panel collection list

### ISSUE THREAD

**Issue by fitzage** [statamic/cms#2466] opened 2020-09-18 17:47 UTC
## Bug Description
1. I added a column in one of my collection lists to display one of the taxonomy tags.
2. I clicked the header for that column in the resulting list.
  - Sort order changed, but not so the taxonomy column was alphabetically sorted. Not sure exactly what sort order is happening.
3. I clicked the header again
  - Sort order did not change
4. Sorting by the default columns (Title and Slug), work as expected. Sorting by the taxonomy column doesn’t sort alphabetically, and gives the same sort order whether ascending or descending.

## Extra Detail
Notice these two screenshots have identical sort orders, despite the caret indicating ascending vs descending, and neither order is what you would expect for this column.

<img width="110" alt="Screen Shot 2020-09-18 at 10 43 12 AM" src="https://user-images.githubusercontent.com/1958/93628921-3e150200-f99c-11ea-8694-508d82747e60.png">
<img width="110" alt="Screen Shot 2020-09-18 at 10 43 21 AM" src="https://user-images.githubusercontent.com/1958/93628925-42d9b600-f99c-11ea-86ba-9e9d06cb4c52.png">

## Environment
Statamic 3.0.10 Pro
Laravel 7.28.2
PHP 7.3.17
No addons installed
Fresh install from `statamic/statamic`, then migrated from v2 using official migrator

**Comment by robdekort** [comment] 2020-10-21 18:51
Hmm, I can't reproduce. Seems to sort here (using a taxonomy limited to one term per entry). Can you zip this is up maybe? If you don't want to put it here you can mail it to support@statamic.com together with a URL to this entry. Or tell more about how the taxonomy/collection/blueprint is set up?

**Comment by fitzage** [comment] 2020-10-23 16:47
Hmm…I think the problem is that it has to be limited to one term per entry in order to sort. I have one collection where it is limited to 1 term per entry, and that sorts as expected.

So I’d say that’s still a bug? I mean, I know it’s harder to sort if there are multiple terms, but it should at least sort by the first term I would think. Maybe not. ¯\_(ツ)_/¯

**Comment by robdekort** [comment] 2020-10-24 18:36
When having multiple taxonomies on entries it should sort on _something more obvious_ when sorting in CP listing views.

**Comment by robdekort** [comment] 2021-01-17 10:04
🦭

**Comment by thisJerem** [comment] 2021-03-04 11:25
I can confirm the same problem here for one of my project, as soon as a taxonomy field can contain more than one term and if just only one entry has 2 terms, there sorting is buggy.
Here is a video of one of my many taxonomy field, first my collection is ordered by date, but as soon as I want to sort them by "departement" field it does'nt work and do not change to any sorting order.
https://www.loom.com/share/c1f35e27f31f4387ba3920f1978f465c

Other taxonomy fields set to max_items: 1 are OK

Maybe related to this issue : https://github.com/statamic/cms/issues/2995

**Comment by jasonvarga** [comment] 2021-07-14 13:51
We can probably make it sort by the first taxonomy term, if you have multiple.
I don't think that really makes sense though, but I guess it's better than nothing.

**Comment by thisJerem** [comment] 2021-07-16 16:10
Maybe it don't make sense, but this solution could really save the ordering, because actually it feel weird.
After that I could reorder automatically a term field values programmatically for one collection every night for example, and it will be fixed totally the issue. 
It could even an enhancement to Statamic to add an option to the blueprint to reorder automatically a term field values after each saving of entries.

**Closed** 2022-01-05 21:30 UTC
Labels: ui, taxonomies
