### ISSUE TITLE
Order if sortable pages is not respected after save

### ISSUE THREAD

**Issue by freshface** [statamic/cms#3191] opened 2021-02-03 08:46 UTC
## Bug Description

I have a pages collection that is draggable.
When i save a page in the tree the order changes

## Extra Detail

Video on https://jmp.sh/GzUY72t

## Environment

Statamic 3.0.40 Pro
Laravel 7.30.4
PHP 7.4.14

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by jasonvarga** [comment] 2021-02-03 16:12
Duplicate of #3148 

Will be released in a moment.

**Closed by jasonvarga** 2021-02-03 16:12 UTC
