### ISSUE TITLE
Search:update not working after update to Statamic 4.41.0

### ISSUE THREAD

**Issue by SteJW** [statamic/cms#9391] opened 2024-01-25 13:17 UTC
### Bug description

When I run php please search:update, the meilisearch connection is getting settings calls like:
string(8) "/indexes"
array(2) {
  ["primaryKey"]=>
  string(2) "id"
  ["uid"]=>
  string(27) "quadwinkel_development_news"
}
string(45) "/indexes/quadwinkel_development_news/settings"
array(2) {
  ["filterableAttributes"]=>
  array(1) {
    [0]=>
    string(10) "news_types"
  }
  ["sortableAttributes"]=>
  array(1) {
    [0]=>
    string(14) "published_date"
  }
}

Only receiving settingsUpdate.
4.40.0 is working.

### How to reproduce

1. Update to statamic 4.41.0
2. Run php please search:update in console
3. There are no items in Meilisearch

### Environment

```yaml
Environment
Application Name: Quadwinkel
Laravel Version: 10.42.0
PHP Version: 8.2.1-dev
Composer Version: 2.4.4
Environment: development
Debug Mode: ENABLED
URL: quadwinkel-corporate-backend.loc
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.41.0 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

**Comment by ryanmitchell** [comment] 2024-01-26 11:47
What version of the meilisearch addon are you using?

**Comment by duncanmcclean** [comment] 2024-02-13 14:51
I'm unable to reproduce this issue with the latest version of Statamic and the latest version of the [Meilisearch addon](https://github.com/statamic-rad-pack/meilisearch), the `search:update` command updates my search index as expected.

The `support:details` output you provided doesn't include any information about which version of the Meilisearch addon you're using, or even if you have it installed at all. 

I'm going to close this issue for now. If you're still experiencing this issue, please provide some more information about the version of the addon you're using and we can look at re-opening. Thanks!

**Closed by duncanmcclean** 2024-02-13 14:51 UTC
Labels: needs more info, search
