### ISSUE TITLE
Live Preview Replicator Issues

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/cms#3297] opened 2021-02-23 17:35 UTC
Two features of live preview don't seem to be working with my replicator field.

Please bear in mind that I am using [edalzell/statamic-blade](https://github.com/edalzell/statamic-blade) directive's so the issue might originate from there.

## Extra Detail

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/20210934/108883116-f7879b80-75fc-11eb-9475-7ada7fa317dd.gif)

- Replicator ordering has no effect in Live Preview (see video) (works on front-end)
- 'Included in output'  toggle has no effect in Live Preview (not shown in video) (works on front-end)
- Clicking 'Save & Publish' will update the preview, but only after I change something again.

## Environment

**Statamic version:** 3.0.45

**Install method (choose one):**
- Installed as package into new Laravel project

**Comment by duncanmcclean** [comment] 2021-02-24 23:13
Sorry but I'm unable to reproduce this issue, [see video](https://www.loom.com/share/4ad6a87758c4448ea3553b457a2a73eb) (bearing in mind I'm using Antlers).

It's almost defiantly to do with the Blade Directives addon, when you use the directive, it gets the entry from the `Entry` facade behind the scenes, which means the changes won't show up, as they haven't been saved yet.

I'm closing this issue as it's not really a Statamic issue, probably best to create it on the addon's repository instead so the developer can look into it.

**Closed by duncanmcclean** 2021-02-24 23:13 UTC
Labels: can't recreate, live preview

**Comment by stuartcusackie** [comment] 2021-02-25 10:02
Thanks for looking into it. I've got an issue open on the addons repo.
